import type { SeedQuizOption } from "./reference-data-types";

// Seed data - IMTA Programs
export const SEED_IMTA_PROGRAMS = [
	{
		id: "sage_femme",
		name: "Midwife",
		nameFr: "Sage-Femme",
		field: "healthcare",
		duration: "3 Years",
		durationFr: "3 Ans",
		requirements: "Baccalaureate Required",
		requirementsFr: "Bac Requis",
		description:
			"Support women through the most precious moments of their lives. A noble vocation with exceptional employment rates.",
		descriptionFr:
			"Accompagnez les femmes dans les moments les plus précieux de leur vie. Une vocation noble avec un taux d'emploi exceptionnel.",
		successRate: 98,
		avgSalary: 6000,
		employmentRate: 100,
		skills: [
			"Obstetrics",
			"Prenatal care",
			"Postnatal care",
			"Emergency childbirth",
			"Patient communication",
			"Medical monitoring",
		],
		certifications: ["State Diploma in Midwifery"],
	},
	{
		id: "infirmier_polyvalent",
		name: "General Nurse",
		nameFr: "Infirmier Polyvalent",
		field: "healthcare",
		duration: "3 Years",
		durationFr: "3 Ans",
		requirements: "Baccalaureate Required",
		requirementsFr: "Bac Requis",
		description:
			"The pillar of hospital care. Excellent versatile training that opens doors to all healthcare facilities.",
		descriptionFr:
			"Le pilier des soins hospitaliers. Formation polyvalente d'excellence qui ouvre les portes de tous les établissements de santé.",
		successRate: 97,
		avgSalary: 5500,
		employmentRate: 100,
		skills: [
			"Patient care",
			"Medication administration",
			"Vital signs monitoring",
			"Wound care",
			"IV therapy",
			"Emergency response",
		],
		certifications: ["State Nursing Diploma"],
	},
	{
		id: "aide_soignant",
		name: "Nursing Assistant",
		nameFr: "Aide Soignant",
		field: "healthcare",
		duration: "1 Year",
		durationFr: "1 An",
		requirements: "9th Grade (3eme AS)",
		requirementsFr: "3eme AS",
		description:
			"Accelerated training for rapid entry into the medical sector. Ideal for starting a career in healthcare.",
		descriptionFr:
			"Formation accélérée pour une insertion rapide dans le secteur médical. Idéal pour commencer une carrière dans la santé.",
		successRate: 95,
		avgSalary: 3500,
		employmentRate: 98,
		skills: [
			"Basic patient care",
			"Hygiene assistance",
			"Mobility support",
			"Vital signs",
			"Patient comfort",
			"Team collaboration",
		],
		certifications: ["Nursing Assistant Certificate"],
	},
	{
		id: "hse_specialist",
		name: "HSE Specialist",
		nameFr: "Spécialiste HSE",
		field: "hse",
		duration: "2 Years",
		durationFr: "2 Ans",
		requirements: "Baccalaureate Required",
		requirementsFr: "Bac Requis",
		description:
			"Become the safety guardian in strategic industries. An essential profession with attractive salaries.",
		descriptionFr:
			"Devenez le garant de la sécurité dans les industries stratégiques. Un métier indispensable avec des salaires attractifs.",
		successRate: 96,
		avgSalary: 7000,
		employmentRate: 95,
		skills: [
			"Risk assessment",
			"Safety audits",
			"Emergency planning",
			"Regulatory compliance",
			"Training delivery",
			"Incident investigation",
		],
		certifications: ["HSE Technician Diploma", "ISO 45001"],
	},
	{
		id: "conducteur_engins",
		name: "Heavy Equipment Operator",
		nameFr: "Conducteur d'Engins",
		field: "industrial",
		duration: "Certifying",
		durationFr: "Certifiant",
		requirements: "Short Program",
		requirementsFr: "Court",
		description:
			"Master the power of heavy machinery on construction sites. Intensive practical training on real equipment.",
		descriptionFr:
			"Dominez la puissance des machines lourdes sur les chantiers. Formation pratique intensive sur engins réels.",
		successRate: 100,
		avgSalary: 8000,
		employmentRate: 92,
		skills: [
			"Excavator operation",
			"Loader operation",
			"Bulldozer operation",
			"Safety protocols",
			"Site navigation",
			"Equipment inspection",
		],
		certifications: ["Heavy Equipment Operator License", "CACES"],
	},
	{
		id: "electromecanique",
		name: "Electromechanical Technician",
		nameFr: "Technicien Électromécanique",
		field: "industrial",
		duration: "2 Years",
		durationFr: "2 Ans",
		requirements: "Baccalaureate Required",
		requirementsFr: "Bac Requis",
		description: "Master both electrical and mechanical systems. Essential for modern automated industries.",
		descriptionFr:
			"Maîtrisez les systèmes électriques et mécaniques. Essentiel pour les industries automatisées modernes.",
		successRate: 93,
		avgSalary: 6000,
		employmentRate: 94,
		skills: [
			"Electrical systems",
			"Mechanical systems",
			"PLC programming",
			"Automation",
			"Troubleshooting",
			"Preventive maintenance",
		],
		certifications: ["Electromechanical Technician Diploma"],
	},
	{
		id: "soudure",
		name: "Welder",
		nameFr: "Soudeur",
		field: "industrial",
		duration: "1 Year",
		durationFr: "1 An",
		requirements: "9th Grade",
		requirementsFr: "9AF",
		description: "Master welding techniques for construction and industry. High demand skill across multiple sectors.",
		descriptionFr:
			"Maîtrisez les techniques de soudure pour le BTP et l'industrie. Compétence très demandée dans plusieurs secteurs.",
		successRate: 91,
		avgSalary: 5500,
		employmentRate: 92,
		skills: [
			"MIG welding",
			"TIG welding",
			"Arc welding",
			"Blueprint reading",
			"Metal preparation",
			"Quality inspection",
		],
		certifications: ["Welder Certificate", "AWS Certification"],
	},
];

// Seed data - Interview Tips
export const SEED_INTERVIEW_TIPS = [
	{
		id: "prep-1",
		title: "Research the Company",
		titleFr: "Recherchez l'entreprise",
		content: "Learn about the company's mission, values, and recent news before the interview.",
		contentFr: "Renseignez-vous sur la mission, les valeurs et l'actualité de l'entreprise avant l'entretien.",
		category: "preparation",
		field: undefined,
		tags: ["research", "company", "preparation"],
	},
	{
		id: "prep-2",
		title: "Prepare Your Documents",
		titleFr: "Préparez vos documents",
		content: "Bring multiple copies of your resume, diplomas, internship certificates, and other relevant documents.",
		contentFr: "Apportez plusieurs copies de votre CV, diplômes, attestations de stage et certificats.",
		category: "preparation",
		field: undefined,
		tags: ["documents", "resume", "preparation"],
	},
	{
		id: "during-1",
		title: "Listen Carefully",
		titleFr: "Écoutez attentivement",
		content: "Listen to the entire question before answering. Ask for clarification if needed.",
		contentFr: "Écoutez la question en entier avant de répondre. Demandez des précisions si nécessaire.",
		category: "during",
		field: undefined,
		tags: ["listening", "communication", "during"],
	},
	{
		id: "during-2",
		title: "Use Concrete Examples",
		titleFr: "Utilisez des exemples concrets",
		content: "Support your answers with specific examples from your internships or studies.",
		contentFr: "Appuyez vos réponses avec des exemples précis de vos stages ou études à l'IMTA.",
		category: "during",
		field: undefined,
		tags: ["examples", "STAR", "during"],
	},
	{
		id: "after-1",
		title: "Send a Thank You",
		titleFr: "Envoyez un remerciement",
		content: "Send a brief thank-you email within 24 hours of the interview.",
		contentFr: "Envoyez un bref email de remerciement dans les 24 heures suivant l'entretien.",
		category: "after",
		field: undefined,
		tags: ["follow-up", "thank-you", "after"],
	},
	{
		id: "body-1",
		title: "Maintain Eye Contact",
		titleFr: "Maintenez le contact visuel",
		content: "Look at the interviewer when speaking to show confidence and engagement.",
		contentFr: "Regardez le recruteur quand vous parlez pour montrer confiance et engagement.",
		category: "body_language",
		field: undefined,
		tags: ["body-language", "confidence", "eye-contact"],
	},
	{
		id: "body-2",
		title: "Sit Up Straight",
		titleFr: "Tenez-vous droit",
		content: "Good posture shows professionalism and attentiveness.",
		contentFr: "Une bonne posture montre le professionnalisme et l'attention.",
		category: "body_language",
		field: undefined,
		tags: ["body-language", "posture", "professionalism"],
	},
	{
		id: "during-3",
		title: "Stay Calm Under Pressure",
		titleFr: "Restez calme sous pression",
		content: "Breathe before answering difficult questions. It's normal to take time to think.",
		contentFr: "Respirez avant de répondre aux questions difficiles. Il est normal de prendre le temps de réfléchir.",
		category: "during",
		field: undefined,
		tags: ["calm", "pressure", "breathing"],
	},
];

// Seed data - Interview Common Questions
export const SEED_INTERVIEW_QUESTIONS = [
	{
		id: "q-general-1",
		question: "Tell me about yourself.",
		questionFr: "Parlez-moi de vous.",
		type: "general",
		field: "general",
		sampleAnswer:
			"Start with your education, then mention relevant experience, and end with why you're interested in this role.",
		sampleAnswerFr:
			"Commencez par votre formation, puis mentionnez votre expérience pertinente, et terminez par pourquoi ce poste vous intéresse.",
		tips: ["Keep it professional", "Focus on relevant experience", "Be concise (2-3 minutes)"],
		tipsFr: ["Restez professionnel", "Concentrez-vous sur l'expérience pertinente", "Soyez concis (2-3 minutes)"],
		difficulty: "beginner",
	},
	{
		id: "q-general-2",
		question: "What are your strengths and weaknesses?",
		questionFr: "Quelles sont vos forces et faiblesses?",
		type: "general",
		field: "general",
		sampleAnswer:
			"For strengths, give specific examples. For weaknesses, mention one and explain how you're working to improve it.",
		sampleAnswerFr:
			"Pour les forces, donnez des exemples précis. Pour les faiblesses, mentionnez-en une et expliquez comment vous travaillez à l'améliorer.",
		tips: ["Be honest but strategic", "Turn weakness into a growth story", "Provide examples"],
		tipsFr: [
			"Soyez honnête mais stratégique",
			"Transformez la faiblesse en histoire de progrès",
			"Donnez des exemples",
		],
		difficulty: "intermediate",
	},
	{
		id: "q-behavioral-1",
		question: "Tell me about a time you worked in a team.",
		questionFr: "Parlez-moi d'une expérience de travail en équipe.",
		type: "behavioral",
		field: "general",
		sampleAnswer: "Use the STAR method: Situation, Task, Action, Result.",
		sampleAnswerFr: "Utilisez la méthode STAR : Situation, Tâche, Action, Résultat.",
		tips: ["Use STAR method", "Focus on your contribution", "Highlight collaboration skills"],
		tipsFr: ["Utilisez la méthode STAR", "Concentrez-vous sur votre contribution", "Mettez en avant la collaboration"],
		difficulty: "intermediate",
	},
	{
		id: "q-healthcare-1",
		question: "How would you handle a difficult patient?",
		questionFr: "Comment gérer un patient difficile ?",
		type: "situational",
		field: "healthcare",
		sampleAnswer: "Show empathy, remain calm, listen to their concerns, and involve supervisors if needed.",
		sampleAnswerFr:
			"Montrez de l'empathie, restez calme, écoutez leurs préoccupations et impliquez les superviseurs si nécessaire.",
		tips: ["Emphasize empathy", "Show patience", "Know when to escalate"],
		tipsFr: ["Insistez sur l'empathie", "Montrez de la patience", "Sachez quand escalader"],
		difficulty: "intermediate",
	},
	{
		id: "q-industrial-1",
		question: "How do you ensure safety on a worksite?",
		questionFr: "Comment assurez-vous la sécurité sur un chantier ?",
		type: "technical",
		field: "industrial",
		sampleAnswer: "Follow safety protocols, wear PPE, report hazards immediately, and maintain awareness.",
		sampleAnswerFr:
			"Suivez les protocoles de sécurité, portez les EPI, signalez les dangers immédiatement et restez vigilant.",
		tips: ["Know safety regulations", "Give specific examples", "Emphasize prevention"],
		tipsFr: ["Connaissez les réglementations", "Donnez des exemples précis", "Insistez sur la prévention"],
		difficulty: "intermediate",
	},
	{
		id: "q-hse-1",
		question: "What would you do if you discovered a safety violation?",
		questionFr: "Que feriez-vous si vous découvriez une violation de sécurité ?",
		type: "situational",
		field: "hse",
		sampleAnswer:
			"Document it, report to supervisor, ensure immediate danger is addressed, and follow up on corrective actions.",
		sampleAnswerFr:
			"Documentez, signalez au superviseur, assurez-vous que le danger immédiat est traité et suivez les actions correctives.",
		tips: ["Show procedural knowledge", "Emphasize documentation", "Balance urgency with protocol"],
		tipsFr: [
			"Montrez la connaissance des procédures",
			"Insistez sur la documentation",
			"Équilibrez urgence et protocole",
		],
		difficulty: "advanced",
	},
];

// Seed data - Market Insights
export const SEED_MARKET_INSIGHTS = [
	{
		title: "Healthcare Demand",
		titleFr: "Demande en Santé",
		value: "15,000+",
		description: "Open healthcare positions in Morocco",
		descriptionFr: "Postes ouverts dans la santé au Maroc",
		icon: "HeartIcon",
		color: "text-red-500",
		field: "healthcare",
	},
	{
		title: "Industrial Growth",
		titleFr: "Croissance Industrielle",
		value: "+12%",
		description: "Year-over-year growth in industrial jobs",
		descriptionFr: "Croissance annuelle des emplois industriels",
		icon: "WrenchIcon",
		color: "text-blue-500",
		field: "industrial",
	},
	{
		title: "HSE Priority",
		titleFr: "Priorité HSE",
		value: "Top 5",
		description: "HSE among most in-demand roles",
		descriptionFr: "HSE parmi les rôles les plus demandés",
		icon: "ShieldCheckIcon",
		color: "text-green-500",
		field: "hse",
	},
	{
		title: "Average Starting Salary",
		titleFr: "Salaire de Départ Moyen",
		value: "5,500 DH",
		description: "Average starting salary for IMTA graduates",
		descriptionFr: "Salaire de départ moyen des diplômés IMTA",
		icon: "TrendUpIcon",
		color: "text-purple-500",
		field: undefined,
	},
];

// Seed data - Employers
export const SEED_EMPLOYERS = [
	{
		name: "OCP Group",
		sector: "Mining & Phosphates",
		sectorFr: "Mines & Phosphates",
		location: "Casablanca, Khouribga, Safi",
		locationFr: "Casablanca, Khouribga, Safi",
		openPositions: 500,
		website: "https://www.ocpgroup.ma",
		description: "World leader in phosphate production",
		descriptionFr: "Leader mondial de la production de phosphates",
		fields: ["industrial", "hse"],
	},
	{
		name: "CHU Ibn Sina",
		sector: "Healthcare",
		sectorFr: "Santé",
		location: "Rabat",
		locationFr: "Rabat",
		openPositions: 200,
		website: "https://www.chuibnrochd.ma",
		description: "Major university hospital in Morocco",
		descriptionFr: "Hôpital universitaire majeur au Maroc",
		fields: ["healthcare"],
	},
	{
		name: "Renault Morocco",
		sector: "Automotive",
		sectorFr: "Automobile",
		location: "Tangier",
		locationFr: "Tanger",
		openPositions: 300,
		website: "https://www.renault.ma",
		description: "Major automotive manufacturing plant",
		descriptionFr: "Usine automobile majeure",
		fields: ["industrial", "hse"],
	},
];

// Seed data - Skills
export const SEED_SKILLS = [
	{ name: "Patient Care", nameFr: "Soins aux Patients", field: "healthcare", category: "technical" },
	{ name: "Vital Signs Monitoring", nameFr: "Surveillance des Constantes", field: "healthcare", category: "technical" },
	{
		name: "Medication Administration",
		nameFr: "Administration des Médicaments",
		field: "healthcare",
		category: "technical",
	},
	{ name: "First Aid", nameFr: "Premiers Secours", field: "healthcare", category: "technical" },
	{ name: "Empathy", nameFr: "Empathie", field: "healthcare", category: "soft" },
	{ name: "Welding (MIG/TIG)", nameFr: "Soudure (MIG/TIG)", field: "industrial", category: "technical" },
	{ name: "Equipment Operation", nameFr: "Conduite d'Engins", field: "industrial", category: "technical" },
	{ name: "PLC Programming", nameFr: "Programmation Automates", field: "industrial", category: "technical" },
	{ name: "Blueprint Reading", nameFr: "Lecture de Plans", field: "industrial", category: "technical" },
	{ name: "Risk Assessment", nameFr: "Évaluation des Risques", field: "hse", category: "technical" },
	{ name: "Safety Audits", nameFr: "Audits de Sécurité", field: "hse", category: "technical" },
	{ name: "Emergency Response", nameFr: "Réponse d'Urgence", field: "hse", category: "technical" },
	{ name: "ISO Standards", nameFr: "Normes ISO", field: "hse", category: "certifications" },
	{ name: "French (B2+)", nameFr: "Français (B2+)", field: "healthcare", category: "languages" },
	{ name: "Communication", nameFr: "Communication", field: "healthcare", category: "soft" },
	{ name: "Teamwork", nameFr: "Travail d'Équipe", field: "industrial", category: "soft" },
];

// Seed data - Career Quiz Questions
export const SEED_QUIZ_QUESTIONS = [
	// Career Assessment Questions
	{
		id: "ca-q1",
		quizType: "career_assessment" as const,
		question: "How do you react in an emergency situation?",
		questionFr: "Comment réagissez-vous face à une situation d'urgence ?",
		description: "Imagine a stressful work situation requiring immediate action.",
		descriptionFr: "Imaginez une situation stressante au travail nécessitant une action immédiate.",
		category: "personality",
		type: "multiple_choice" as const,
		trait: "stress_tolerance",
		sortOrder: 1,
	},
	{
		id: "ca-q2",
		quizType: "career_assessment" as const,
		question: "Which trait describes you best?",
		questionFr: "Quel trait vous décrit le mieux ?",
		category: "personality",
		type: "multiple_choice" as const,
		trait: "communication",
		sortOrder: 2,
	},
	{
		id: "ca-q3",
		quizType: "career_assessment" as const,
		question: "How comfortable are you with physical work?",
		questionFr: "À quel point êtes-vous à l'aise avec le travail physique ?",
		category: "personality",
		type: "scale" as const,
		trait: "physical_endurance",
		scaleMin: "I prefer desk work",
		scaleMax: "I love physical activities",
		scaleMinFr: "Je préfère le travail de bureau",
		scaleMaxFr: "J'adore les activités physiques",
		sortOrder: 3,
	},
	{
		id: "ca-q4",
		quizType: "career_assessment" as const,
		question: "Which field are you most passionate about?",
		questionFr: "Quel domaine vous passionne le plus ?",
		category: "interests",
		type: "multiple_choice" as const,
		trait: "patient_care",
		sortOrder: 4,
	},
	{
		id: "ca-q5",
		quizType: "career_assessment" as const,
		question: "What type of professional activity attracts you?",
		questionFr: "Quel type d'activité professionnelle vous attire ?",
		category: "interests",
		type: "multiple_choice" as const,
		trait: "technical_aptitude",
		sortOrder: 5,
	},
	// Career Quiz Questions (shorter version)
	{
		id: "cq-q1",
		quizType: "career_quiz" as const,
		question: "What work environment do you prefer?",
		questionFr: "Quel environnement de travail préférez-vous ?",
		category: "environment",
		type: "multiple_choice" as const,
		trait: "technical_aptitude",
		sortOrder: 1,
	},
	{
		id: "cq-q2",
		quizType: "career_quiz" as const,
		question: "Do you prefer working alone or in a team?",
		questionFr: "Préférez-vous travailler seul ou en équipe ?",
		category: "work_style",
		type: "multiple_choice" as const,
		trait: "teamwork",
		sortOrder: 2,
	},
	// Remote Readiness Questions
	{
		id: "rr-q1",
		quizType: "remote_readiness" as const,
		question: "How do you usually communicate with remote colleagues?",
		questionFr: "Comment communiquez-vous habituellement avec vos collègues à distance ?",
		category: "communication",
		type: "multiple_choice" as const,
		trait: "communication",
		sortOrder: 1,
	},
	{
		id: "rr-q2",
		quizType: "remote_readiness" as const,
		question: "How often do you participate in virtual meetings?",
		questionFr: "À quelle fréquence participez-vous à des réunions virtuelles ?",
		category: "communication",
		type: "multiple_choice" as const,
		trait: "communication",
		sortOrder: 2,
	},
	{
		id: "rr-q3",
		quizType: "remote_readiness" as const,
		question: "How do you organize your work day at home?",
		questionFr: "Comment organisez-vous votre journée de travail à domicile ?",
		category: "time_management",
		type: "multiple_choice" as const,
		trait: "self_discipline",
		sortOrder: 3,
	},
];

// Seed data - Career Quiz Options
export const SEED_QUIZ_OPTIONS: SeedQuizOption[] = [
	// Options for ca-q1 (emergency reaction)
	{
		id: "ca-q1-a",
		questionId: "ca-q1",
		text: "I stay calm and act methodically",
		textFr: "Je reste calme et j'agis méthodiquement",
		icon: "SparkleIcon",
		scores: { stress_tolerance: 3, patient_care: 2, leadership: 2, safety_focus: 2 },
		sortOrder: 1,
	},
	{
		id: "ca-q1-b",
		questionId: "ca-q1",
		text: "I immediately take control of the situation",
		textFr: "Je prends immédiatement le contrôle de la situation",
		icon: "RocketLaunchIcon",
		scores: { leadership: 3, stress_tolerance: 2, safety_focus: 1, technical_aptitude: 1 },
		sortOrder: 2,
	},
	{
		id: "ca-q1-c",
		questionId: "ca-q1",
		text: "I first seek help from colleagues",
		textFr: "Je cherche d'abord de l'aide auprès de mes collègues",
		icon: "UsersIcon",
		scores: { teamwork: 3, communication: 2, stress_tolerance: 1, patient_care: 1 },
		sortOrder: 3,
	},
	{
		id: "ca-q1-d",
		questionId: "ca-q1",
		text: "I quickly analyze the situation before acting",
		textFr: "J'analyse rapidement la situation avant d'agir",
		icon: "LightbulbIcon",
		scores: { analytical: 3, safety_focus: 2, technical_aptitude: 2, attention_to_detail: 1 },
		sortOrder: 4,
	},
	// Options for ca-q2 (personality trait)
	{
		id: "ca-q2-a",
		questionId: "ca-q2",
		text: "Empathetic and a good listener",
		textFr: "Empathique et à l'écoute des autres",
		icon: "HeartIcon",
		scores: { patient_care: 3, communication: 3, teamwork: 2, leadership: 0 },
		sortOrder: 1,
	},
	{
		id: "ca-q2-b",
		questionId: "ca-q2",
		text: "Rigorous and detail-oriented",
		textFr: "Rigoureux et attentif aux détails",
		icon: "TargetIcon",
		scores: { attention_to_detail: 3, safety_focus: 2, technical_aptitude: 2, analytical: 1 },
		sortOrder: 2,
	},
	{
		id: "ca-q2-c",
		questionId: "ca-q2",
		text: "Practical and action-oriented",
		textFr: "Pratique et orienté vers l'action",
		icon: "WrenchIcon",
		scores: { technical_aptitude: 3, physical_endurance: 2, stress_tolerance: 1, leadership: 1 },
		sortOrder: 3,
	},
	{
		id: "ca-q2-d",
		questionId: "ca-q2",
		text: "Natural leader and organizer",
		textFr: "Leader naturel et organisateur",
		icon: "MedalIcon",
		scores: { leadership: 3, communication: 2, teamwork: 2, stress_tolerance: 1 },
		sortOrder: 4,
	},
	// Options for ca-q4 (passion field)
	{
		id: "ca-q4-a",
		questionId: "ca-q4",
		text: "Health and well-being of people",
		textFr: "La santé et le bien-être des personnes",
		icon: "FirstAidKitIcon",
		scores: { patient_care: 3, communication: 2, teamwork: 2, stress_tolerance: 1 },
		sortOrder: 1,
	},
	{
		id: "ca-q4-b",
		questionId: "ca-q4",
		text: "Mechanics and industrial technologies",
		textFr: "La mécanique et les technologies industrielles",
		icon: "GearIcon",
		scores: { technical_aptitude: 3, analytical: 2, physical_endurance: 1, attention_to_detail: 1 },
		sortOrder: 2,
	},
	{
		id: "ca-q4-c",
		questionId: "ca-q4",
		text: "Safety and risk prevention",
		textFr: "La sécurité et la prévention des risques",
		icon: "ShieldCheckIcon",
		scores: { safety_focus: 3, leadership: 2, attention_to_detail: 2, communication: 1 },
		sortOrder: 3,
	},
	{
		id: "ca-q4-d",
		questionId: "ca-q4",
		text: "Construction and civil works",
		textFr: "La construction et le BTP",
		icon: "BuildingsIcon",
		scores: { physical_endurance: 3, technical_aptitude: 2, safety_focus: 2, teamwork: 1 },
		sortOrder: 4,
	},
	// Options for cq-q1 (work environment)
	{
		id: "cq-q1-a",
		questionId: "cq-q1",
		text: "Indoor, in a hospital or clinic",
		textFr: "En intérieur, dans un hôpital ou clinique",
		icon: "BuildingsIcon",
		scores: { patient_care: 3, teamwork: 2, safety_focus: 1 },
		sortOrder: 1,
	},
	{
		id: "cq-q1-b",
		questionId: "cq-q1",
		text: "On site, construction or industrial sites",
		textFr: "Sur le terrain, chantiers ou sites industriels",
		icon: "HardHatIcon",
		scores: { technical_aptitude: 3, safety_focus: 2, leadership: 1 },
		sortOrder: 2,
	},
	// Options for remote readiness questions
	{
		id: "rr-q1-a",
		questionId: "rr-q1",
		text: "I prefer phone calls only",
		textFr: "Je préfère les appels téléphoniques uniquement",
		icon: "PhoneIcon",
		scores: { communication: 1 },
		sortOrder: 1,
	},
	{
		id: "rr-q1-b",
		questionId: "rr-q1",
		text: "I mainly use emails",
		textFr: "J'utilise principalement les emails",
		icon: "EnvelopeIcon",
		scores: { communication: 2 },
		sortOrder: 2,
	},
	{
		id: "rr-q1-c",
		questionId: "rr-q1",
		text: "I use a combination of tools (email, chat, video)",
		textFr: "J'utilise une combinaison d'outils (email, chat, video)",
		icon: "ChatCircleIcon",
		scores: { communication: 3 },
		sortOrder: 3,
	},
	{
		id: "rr-q1-d",
		questionId: "rr-q1",
		text: "I adapt my communication based on context and urgency",
		textFr: "J'adapte mon mode de communication selon le contexte et l'urgence",
		icon: "LightningIcon",
		scores: { communication: 4 },
		sortOrder: 4,
	},
];
