const frenchTextReplacements: Array<[string, string]> = [
	["Preparez", "Préparez"],
	["preparez", "préparez"],
	["Preparation", "Préparation"],
	["preparation", "préparation"],
	["Entrainez", "Entraînez"],
	["entrainez", "entraînez"],
	["S'entrainer", "S'entraîner"],
	["entrainement", "entraînement"],
	["Repondez", "Répondez"],
	["repondez", "répondez"],
	["reponse", "réponse"],
	["reponses", "réponses"],
	["Reponse", "Réponse"],
	["Reponses", "Réponses"],
	["recits", "récits"],
	["Revisez", "Révisez"],
	["revisez", "révisez"],
	["Decrivez", "Décrivez"],
	["decrivez", "décrivez"],
	["decrit", "décrit"],
	["gerez", "gérez"],
	["geree", "gérée"],
	["gereriez", "géreriez"],
	["gerereriez", "géreriez"],
	["actualite", "actualité"],
	["diplomes", "diplômes"],
	["methode", "méthode"],
	["Methode", "Méthode"],
	["tache", "tâche"],
	["Tache", "Tâche"],
	["resultat", "résultat"],
	["Resultat", "Résultat"],
	["etape", "étape"],
	["etapes", "étapes"],
	["Etape", "Étape"],
	["adaptee", "adaptée"],
	["adaptees", "adaptées"],
	["adapte", "adapté"],
	["adaptes", "adaptés"],
	["etudiants", "étudiants"],
	["competence", "compétence"],
	["competences", "compétences"],
	["experience", "expérience"],
	["experiences", "expériences"],
	["equipe", "équipe"],
	["equipes", "équipes"],
	["integration", "intégration"],
	["interet", "intérêt"],
	["interesse", "intéressé"],
	["securite", "sécurité"],
	["Sante", "Santé"],
	["sante", "santé"],
	["hygiene", "hygiène"],
	["Hygiene", "Hygiène"],
	["identite", "identité"],
	["tracabilite", "traçabilité"],
	["confidentialite", "confidentialité"],
	["immediat", "immédiat"],
	["immediate", "immédiate"],
	["difficulte", "difficulté"],
	["difficultes", "difficultés"],
	["ameliorer", "améliorer"],
	["ameliore", "amélioré"],
	["annees", "années"],
	["coeur", "cœur"],
	["metier", "métier"],
	["generales", "générales"],
	["generale", "générale"],
	["realiste", "réaliste"],
	["Resumez", "Résumez"],
	["resumez", "résumez"],
	["selection", "sélection"],
	["Selection", "Sélection"],
	["evitez", "évitez"],
	["Evitez", "Évitez"],
	["ecoute", "écoute"],
	["Ecoutez", "Écoutez"],
	["verifier", "vérifier"],
	["Verifiez", "Vérifiez"],
	["presentez", "présentez"],
	["presente", "présenté"],
	["Ou vous", "Où vous"],
	["ou vous", "où vous"],
	["a repondre", "à répondre"],
	["a l'entretien", "à l'entretien"],
	["a reprendre", "à reprendre"],
	["a confirmer", "à confirmer"],
	["a jour", "à jour"],
	["a nous", "à nous"],
	["a un", "à un"],
	["a une", "à une"],
	["a votre", "à votre"],
	["a vos", "à vos"],
	["a la", "à la"],
	["a l'", "à l'"],
];

function escapeRegExp(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function polishFrenchText(text: string): string {
	return frenchTextReplacements.reduce(
		(value, [from, to]) => value.replace(new RegExp(`\\b${escapeRegExp(from)}\\b`, "g"), to),
		text,
	);
}
