import { t } from "@lingui/core/macro";
import type { Icon } from "@phosphor-icons/react";
import {
	BookmarkIcon,
	BriefcaseIcon,
	CodeIcon,
	CrownIcon,
	GraduationCapIcon,
	HeartIcon,
	LightningIcon,
	PaletteIcon,
	RocketLaunchIcon,
	SparkleIcon,
	TrendUpIcon,
} from "@phosphor-icons/react";

import type { ExperienceLevel, IndustryCategory, ResumeTemplate, StyleCategory, TemplateReview } from "./gallery-types";

// Style category configuration - wrapped in function so t`` resolves with active locale
export function getStyleLabels(): Record<StyleCategory, string> {
	return {
		professional: t`Professionnel`,
		creative: t`Créatif`,
		modern: t`Moderne`,
		classic: t`Classique`,
		tech: t`Technique`,
		executive: t`Direction`,
	};
}

export const styleColors: Record<StyleCategory, string> = {
	professional: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
	creative: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400",
	modern: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-400",
	classic: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
	tech: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
	executive: "bg-slate-100 text-slate-700 dark:bg-slate-900/30 dark:text-slate-400",
};

export const styleIcons: Record<StyleCategory, Icon> = {
	professional: BriefcaseIcon,
	creative: PaletteIcon,
	modern: RocketLaunchIcon,
	classic: BookmarkIcon,
	tech: CodeIcon,
	executive: CrownIcon,
};

export const styleGradients: Record<StyleCategory, string> = {
	professional: "from-blue-500/20 via-blue-400/10 to-transparent",
	creative: "from-purple-500/20 via-pink-400/10 to-transparent",
	modern: "from-cyan-500/20 via-teal-400/10 to-transparent",
	classic: "from-amber-500/20 via-orange-400/10 to-transparent",
	tech: "from-green-500/20 via-emerald-400/10 to-transparent",
	executive: "from-slate-500/20 via-gray-400/10 to-transparent",
};

// Industry configuration - wrapped in function so t`` resolves with active locale
export function getIndustryLabels(): Record<IndustryCategory, string> {
	return {
		technology: t`Digital / IT`,
		finance: t`Finance & banque`,
		healthcare: t`Santé & social`,
		education: t`Éducation / étudiants`,
		marketing: t`Marketing & communication`,
		engineering: t`Industrie & technique`,
		legal: t`Juridique / administration`,
		general: t`Polyvalent`,
	};
}

export const industryIcons: Record<IndustryCategory, Icon> = {
	technology: CodeIcon,
	finance: TrendUpIcon,
	healthcare: HeartIcon,
	education: GraduationCapIcon,
	marketing: SparkleIcon,
	engineering: LightningIcon,
	legal: BookmarkIcon,
	general: BriefcaseIcon,
};

// Experience level configuration - wrapped in function so t`` resolves with active locale
export function getExperienceLevelLabels(): Record<ExperienceLevel, string> {
	return {
		entry: t`Débutant`,
		mid: t`Confirmé`,
		senior: t`Senior`,
		executive: t`Direction`,
	};
}

export const experienceLevelColors: Record<ExperienceLevel, string> = {
	entry: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
	mid: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
	senior: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400",
	executive: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
};

const baseResumeTemplates: ResumeTemplate[] = [
	{
		id: "azurill",
		name: "Azurill",
		description:
			"A clean and professional template perfect for corporate environments. Features a classic layout with modern typography.",
		style: "professional",
		industries: ["finance", "legal", "general"],
		experienceLevel: ["mid", "senior"],
		previewImage: "/templates/jpg/azurill.jpg",
		rating: 4.8,
		reviewCount: 324,
		downloadCount: 15420,
		isTrending: true,
		isNew: false,
		isPremium: false,
		colors: ["#1a365d", "#2b6cb0", "#4299e1"],
		features: ["ATS Friendly", "Two Column Layout", "Skills Progress Bars"],
		tags: ["Corporate", "Clean", "Minimal"],
	},
	{
		id: "bronzor",
		name: "Bronzor",
		description:
			"A bold and creative template ideal for designers and creative professionals. Features unique visual elements.",
		style: "creative",
		industries: ["marketing", "technology"],
		experienceLevel: ["entry", "mid"],
		previewImage: "/templates/jpg/bronzor.jpg",
		rating: 4.6,
		reviewCount: 256,
		downloadCount: 12350,
		isTrending: false,
		isNew: false,
		isPremium: false,
		colors: ["#553c9a", "#805ad5", "#b794f4"],
		features: ["Creative Layout", "Icon Support", "Color Customization"],
		tags: ["Design", "Bold", "Artistic"],
	},
	{
		id: "chikorita",
		name: "Chikorita",
		description:
			"A fresh and modern template with a nature-inspired color palette. Great for environmental and health sectors.",
		style: "modern",
		industries: ["healthcare", "education", "general"],
		experienceLevel: ["entry", "mid", "senior"],
		previewImage: "/templates/jpg/chikorita.jpg",
		rating: 4.7,
		reviewCount: 198,
		downloadCount: 9870,
		isTrending: true,
		isNew: true,
		isPremium: false,
		colors: ["#22543d", "#38a169", "#68d391"],
		features: ["Clean Design", "Easy to Read", "Section Dividers"],
		tags: ["Fresh", "Natural", "Friendly"],
	},
	{
		id: "ditto",
		name: "Ditto",
		description: "A versatile template that adapts to any industry. Highly customizable with multiple layout options.",
		style: "modern",
		industries: ["technology", "engineering", "general"],
		experienceLevel: ["mid", "senior", "executive"],
		previewImage: "/templates/jpg/ditto.jpg",
		rating: 4.9,
		reviewCount: 412,
		downloadCount: 21560,
		isTrending: true,
		isNew: false,
		isPremium: true,
		colors: ["#2d3748", "#4a5568", "#718096"],
		features: ["Highly Customizable", "Multiple Layouts", "Premium Fonts"],
		tags: ["Versatile", "Adaptive", "Professional"],
	},
	{
		id: "gengar",
		name: "Gengar",
		description: "A bold and striking template with dark theme options. Perfect for tech and gaming industries.",
		style: "tech",
		industries: ["technology", "engineering"],
		experienceLevel: ["mid", "senior"],
		previewImage: "/templates/jpg/gengar.jpg",
		rating: 4.5,
		reviewCount: 187,
		downloadCount: 8920,
		isTrending: false,
		isNew: false,
		isPremium: false,
		colors: ["#44337a", "#6b46c1", "#9f7aea"],
		features: ["Dark Theme", "Tech Focused", "Code Blocks"],
		tags: ["Tech", "Dark", "Bold"],
	},
	{
		id: "glalie",
		name: "Glalie",
		description: "A crisp and cool template with an icy aesthetic. Features clean lines and modern typography.",
		style: "modern",
		industries: ["finance", "technology", "general"],
		experienceLevel: ["entry", "mid"],
		previewImage: "/templates/jpg/glalie.jpg",
		rating: 4.4,
		reviewCount: 145,
		downloadCount: 6780,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#2c5282", "#3182ce", "#63b3ed"],
		features: ["Minimalist", "Professional", "Easy to Scan"],
		tags: ["Clean", "Cool", "Modern"],
	},
	{
		id: "kakuna",
		name: "Kakuna",
		description:
			"A traditional template with timeless appeal. Ideal for conservative industries and executive positions.",
		style: "classic",
		industries: ["legal", "finance", "education"],
		experienceLevel: ["senior", "executive"],
		previewImage: "/templates/jpg/kakuna.jpg",
		rating: 4.7,
		reviewCount: 289,
		downloadCount: 14230,
		isTrending: false,
		isNew: false,
		isPremium: false,
		colors: ["#744210", "#c05621", "#dd6b20"],
		features: ["Traditional Layout", "Formal Style", "Serif Fonts"],
		tags: ["Traditional", "Formal", "Elegant"],
	},
	{
		id: "lapras",
		name: "Lapras",
		description: "A calm and elegant template with a serene blue palette. Great for healthcare and counseling fields.",
		style: "professional",
		industries: ["healthcare", "education", "general"],
		experienceLevel: ["mid", "senior"],
		previewImage: "/templates/jpg/lapras.jpg",
		rating: 4.6,
		reviewCount: 178,
		downloadCount: 8450,
		isTrending: false,
		isNew: false,
		isPremium: false,
		colors: ["#2a4365", "#3182ce", "#90cdf4"],
		features: ["Calming Design", "Clear Structure", "Healthcare Focus"],
		tags: ["Elegant", "Calm", "Professional"],
	},
	{
		id: "leafish",
		name: "Leafish",
		description:
			"An eco-friendly inspired template with organic styling. Perfect for sustainability and environmental sectors.",
		style: "creative",
		industries: ["education", "healthcare", "general"],
		experienceLevel: ["entry", "mid"],
		previewImage: "/templates/jpg/leafish.jpg",
		rating: 4.3,
		reviewCount: 112,
		downloadCount: 5230,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#276749", "#48bb78", "#9ae6b4"],
		features: ["Eco Design", "Nature Theme", "Unique Style"],
		tags: ["Green", "Natural", "Organic"],
	},
	{
		id: "onyx",
		name: "Onyx",
		description:
			"A sleek and sophisticated template with a dark professional aesthetic. Ideal for executive positions.",
		style: "executive",
		industries: ["finance", "legal", "technology"],
		experienceLevel: ["senior", "executive"],
		previewImage: "/templates/jpg/onyx.jpg",
		rating: 4.8,
		reviewCount: 356,
		downloadCount: 18670,
		isTrending: true,
		isNew: false,
		isPremium: true,
		colors: ["#1a202c", "#2d3748", "#4a5568"],
		features: ["Executive Style", "Dark Theme", "Premium Design"],
		tags: ["Luxury", "Executive", "Sophisticated"],
	},
	{
		id: "pikachu",
		name: "Pikachu",
		description: "A vibrant and energetic template that stands out. Great for creative and startup environments.",
		style: "creative",
		industries: ["marketing", "technology"],
		experienceLevel: ["entry", "mid"],
		previewImage: "/templates/jpg/pikachu.jpg",
		rating: 4.5,
		reviewCount: 234,
		downloadCount: 11340,
		isTrending: true,
		isNew: false,
		isPremium: false,
		colors: ["#d69e2e", "#ecc94b", "#faf089"],
		features: ["Vibrant Colors", "Eye Catching", "Modern Layout"],
		tags: ["Energetic", "Fun", "Standout"],
	},
	{
		id: "rhyhorn",
		name: "Rhyhorn",
		description:
			"A robust and structured template for technical professionals. Features clear sections for projects and skills.",
		style: "tech",
		industries: ["technology", "engineering"],
		experienceLevel: ["mid", "senior"],
		previewImage: "/templates/jpg/rhyhorn.jpg",
		rating: 4.6,
		reviewCount: 198,
		downloadCount: 9560,
		isTrending: false,
		isNew: false,
		isPremium: false,
		colors: ["#5a67d8", "#667eea", "#a3bffa"],
		features: ["Technical Focus", "Project Sections", "Skills Matrix"],
		tags: ["Technical", "Structured", "Developer"],
	},
	{
		id: "avicenne",
		name: "Avicenne",
		description: "An elegant template inspired by classical wisdom. Perfect for academic and research positions.",
		style: "classic",
		industries: ["education", "healthcare", "legal"],
		experienceLevel: ["senior", "executive"],
		previewImage: "/templates/jpg/avicenne.jpg",
		rating: 4.7,
		reviewCount: 167,
		downloadCount: 7890,
		isTrending: false,
		isNew: false,
		isPremium: true,
		colors: ["#702459", "#97266d", "#d53f8c"],
		features: ["Academic Style", "Publications Section", "Research Focus"],
		tags: ["Academic", "Scholarly", "Refined"],
	},
	{
		id: "fes",
		name: "Fes",
		description:
			"A beautifully crafted template with intricate design elements. Celebrates cultural heritage with modern flair.",
		style: "creative",
		industries: ["marketing", "education", "general"],
		experienceLevel: ["entry", "mid", "senior"],
		previewImage: "/templates/jpg/fes.jpg",
		rating: 4.4,
		reviewCount: 134,
		downloadCount: 6120,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#285e61", "#319795", "#4fd1c5"],
		features: ["Cultural Design", "Artistic Elements", "Unique Layout"],
		tags: ["Cultural", "Artistic", "Unique"],
	},
	{
		id: "ditgar",
		name: "Ditgar",
		description:
			"A hybrid template combining the best of modern and classic styles. Highly versatile for any industry.",
		style: "professional",
		industries: ["technology", "finance", "marketing", "general"],
		experienceLevel: ["mid", "senior", "executive"],
		previewImage: "/templates/jpg/ditgar.jpg",
		rating: 4.9,
		reviewCount: 478,
		downloadCount: 24560,
		isTrending: true,
		isNew: false,
		isPremium: true,
		colors: ["#1a365d", "#2b6cb0", "#63b3ed"],
		features: ["Best of Both", "Highly Customizable", "Premium Support"],
		tags: ["Versatile", "Premium", "Top Rated"],
	},
	{
		id: "casablanca",
		name: "Casablanca",
		description:
			"Modern corporate design with clean lines and professional blue tones for business and finance roles in Morocco.",
		style: "professional",
		industries: ["finance", "technology", "general"],
		experienceLevel: ["mid", "senior", "executive"],
		previewImage: "/templates/jpg/casablanca.jpg",
		rating: 4.8,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#1e3a5f", "#2563eb", "#60a5fa"],
		features: ["Morocco CV Fields", "Two Column", "Corporate Layout"],
		tags: ["Morocco", "Corporate", "Modern"],
	},
	{
		id: "rabat",
		name: "Rabat",
		description:
			"Formal structured layout for government, diplomatic, and administrative positions with prominent Morocco-specific fields.",
		style: "classic",
		industries: ["legal", "general"],
		experienceLevel: ["mid", "senior", "executive"],
		previewImage: "/templates/jpg/rabat.jpg",
		rating: 4.7,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#1a1a2e", "#16213e", "#0f3460"],
		features: ["Morocco CV Fields", "Formal Layout", "Government Style"],
		tags: ["Morocco", "Government", "Formal"],
	},
	{
		id: "marrakech",
		name: "Marrakech",
		description: "Vibrant warm design with accent sidebar for creative sectors, marketing, and communication roles.",
		style: "creative",
		industries: ["marketing", "general"],
		experienceLevel: ["entry", "mid", "senior"],
		previewImage: "/templates/jpg/marrakech.jpg",
		rating: 4.6,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#c2410c", "#ea580c", "#fb923c"],
		features: ["Morocco CV Fields", "Warm Colors", "Creative Layout"],
		tags: ["Morocco", "Creative", "Vibrant"],
	},
	{
		id: "tangier",
		name: "Tangier",
		description:
			"International clean single-column layout optimized for ATS scanners, ideal for multilingual professionals.",
		style: "modern",
		industries: ["technology", "finance", "general"],
		experienceLevel: ["entry", "mid", "senior"],
		previewImage: "/templates/jpg/tangier.jpg",
		rating: 4.8,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#334155", "#475569", "#94a3b8"],
		features: ["ATS Friendly", "Single Column", "International"],
		tags: ["Morocco", "ATS", "International"],
	},
	{
		id: "meknes",
		name: "Meknes",
		description:
			"Traditional elegant design with refined typography for classic industries, banking, and legal sectors.",
		style: "classic",
		industries: ["finance", "legal", "general"],
		experienceLevel: ["mid", "senior", "executive"],
		previewImage: "/templates/jpg/meknes.jpg",
		rating: 4.7,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#78350f", "#92400e", "#b45309"],
		features: ["Morocco CV Fields", "Traditional Style", "Elegant Typography"],
		tags: ["Morocco", "Traditional", "Elegant"],
	},
	{
		id: "oujda",
		name: "Oujda",
		description: "Bold industrial design with dark sidebar for engineering, technical, and industrial roles.",
		style: "modern",
		industries: ["engineering", "technology"],
		experienceLevel: ["mid", "senior"],
		previewImage: "/templates/jpg/oujda.jpg",
		rating: 4.6,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#0f172a", "#1e293b", "#334155"],
		features: ["Morocco CV Fields", "Dark Sidebar", "Industrial Style"],
		tags: ["Morocco", "Industrial", "Bold"],
	},
	{
		id: "kenitra",
		name: "Kenitra",
		description:
			"Modern industrial layout with geometric accents for manufacturing, logistics, and technical management.",
		style: "modern",
		industries: ["engineering", "technology", "general"],
		experienceLevel: ["mid", "senior"],
		previewImage: "/templates/jpg/kenitra.jpg",
		rating: 4.5,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#1e3a5f", "#3b82f6", "#93c5fd"],
		features: ["Morocco CV Fields", "Geometric Design", "Modern Industrial"],
		tags: ["Morocco", "Industrial", "Geometric"],
	},
	{
		id: "safi",
		name: "Safi",
		description: "Data-dense single-column layout with prominent header band for engineering and technical CVs.",
		style: "professional",
		industries: ["engineering", "technology"],
		experienceLevel: ["mid", "senior"],
		previewImage: "/templates/jpg/safi.jpg",
		rating: 4.7,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#0c4a6e", "#0369a1", "#0ea5e9"],
		features: ["Morocco CV Fields", "ATS Friendly", "Data Dense"],
		tags: ["Morocco", "Engineering", "Technical"],
	},
	{
		id: "ifrane",
		name: "Ifrane",
		description: "Scholarly refined design with centered header for academic, research, and education positions.",
		style: "classic",
		industries: ["education", "healthcare", "general"],
		experienceLevel: ["mid", "senior", "executive"],
		previewImage: "/templates/jpg/ifrane.jpg",
		rating: 4.6,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#1e1b4b", "#3730a3", "#6366f1"],
		features: ["Morocco CV Fields", "Academic Style", "Scholarly Layout"],
		tags: ["Morocco", "Academic", "Research"],
	},
	{
		id: "mohammedia",
		name: "Mohammedia",
		description:
			"Premium executive layout with generous whitespace for C-suite, director, and senior management roles.",
		style: "professional",
		industries: ["finance", "technology", "general"],
		experienceLevel: ["senior", "executive"],
		previewImage: "/templates/jpg/mohammedia.jpg",
		rating: 4.9,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: true,
		colors: ["#18181b", "#27272a", "#52525b"],
		features: ["Morocco CV Fields", "Executive Premium", "Generous Whitespace"],
		tags: ["Morocco", "Executive", "Premium"],
	},
	{
		id: "chefchaouen",
		name: "Chefchaouen",
		description: "Artistic blue-toned design inspired by the Blue City of Morocco for creative professionals.",
		style: "creative",
		industries: ["marketing", "general"],
		experienceLevel: ["entry", "mid", "senior"],
		previewImage: "/templates/jpg/chefchaouen.jpg",
		rating: 4.7,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#1e40af", "#3b82f6", "#93c5fd"],
		features: ["Morocco CV Fields", "Artistic Design", "Blue Theme"],
		tags: ["Morocco", "Artistic", "Creative"],
	},
	{
		id: "essaouira",
		name: "Essaouira",
		description: "Airy coastal-inspired single-column layout with generous whitespace for freelancers and designers.",
		style: "modern",
		industries: ["marketing", "technology", "general"],
		experienceLevel: ["entry", "mid"],
		previewImage: "/templates/jpg/essaouira.jpg",
		rating: 4.5,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#64748b", "#94a3b8", "#cbd5e1"],
		features: ["Morocco CV Fields", "ATS Friendly", "Minimal Design"],
		tags: ["Morocco", "Minimal", "Freelancer"],
	},
	{
		id: "tetouan",
		name: "Tetouan",
		description: "Artisan-inspired design with decorative geometric elements reflecting Moroccan craftsmanship.",
		style: "creative",
		industries: ["general"],
		experienceLevel: ["entry", "mid", "senior"],
		previewImage: "/templates/jpg/tetouan.jpg",
		rating: 4.6,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#92400e", "#b45309", "#d97706"],
		features: ["Morocco CV Fields", "Artisan Design", "Geometric Elements"],
		tags: ["Morocco", "Artisan", "Cultural"],
	},
	{
		id: "agadir",
		name: "Agadir",
		description: "Bright welcoming design for tourism and hospitality industries, highlights languages prominently.",
		style: "modern",
		industries: ["general"],
		experienceLevel: ["entry", "mid", "senior"],
		previewImage: "/templates/jpg/agadir.jpg",
		rating: 4.5,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#0e7490", "#06b6d4", "#67e8f9"],
		features: ["Morocco CV Fields", "Language Focus", "Tourism Style"],
		tags: ["Morocco", "Tourism", "Hospitality"],
	},
	{
		id: "dakhla",
		name: "Dakhla",
		description: "Bold modern design with high-contrast dark sidebar for ambitious tech and business professionals.",
		style: "modern",
		industries: ["technology", "finance", "general"],
		experienceLevel: ["mid", "senior"],
		previewImage: "/templates/jpg/dakhla.jpg",
		rating: 4.7,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#0f172a", "#1e293b", "#475569"],
		features: ["Morocco CV Fields", "Dark Theme", "High Contrast"],
		tags: ["Morocco", "Modern", "Bold"],
	},
	{
		id: "settat",
		name: "Settat",
		description:
			"Clean approachable single-column layout for students and first-time job seekers, compact and ATS-friendly.",
		style: "modern",
		industries: ["education", "general"],
		experienceLevel: ["entry"],
		previewImage: "/templates/jpg/settat.jpg",
		rating: 4.6,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#4338ca", "#6366f1", "#a5b4fc"],
		features: ["Morocco CV Fields", "ATS Friendly", "Student Friendly"],
		tags: ["Morocco", "Student", "Entry Level"],
	},
	{
		id: "jadida",
		name: "Jadida",
		description:
			"Versatile modern professional design with balanced proportions suitable for any industry or role level.",
		style: "professional",
		industries: ["technology", "finance", "healthcare", "marketing", "general"],
		experienceLevel: ["entry", "mid", "senior", "executive"],
		previewImage: "/templates/jpg/jadida.jpg",
		rating: 4.8,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: true,
		isNew: true,
		isPremium: false,
		colors: ["#059669", "#10b981", "#6ee7b7"],
		features: ["Morocco CV Fields", "Versatile", "Balanced Layout"],
		tags: ["Morocco", "Versatile", "Professional"],
	},
	{
		id: "nador",
		name: "Nador",
		description: "Cross-cultural bilingual layout with RTL-aware design for French and Arabic speaking environments.",
		style: "modern",
		industries: ["general"],
		experienceLevel: ["entry", "mid", "senior"],
		previewImage: "/templates/jpg/nador.jpg",
		rating: 4.7,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#065f46", "#047857", "#34d399"],
		features: ["Morocco CV Fields", "Bilingual", "RTL Support"],
		tags: ["Morocco", "Bilingual", "Arabic"],
	},
	{
		id: "beni-mellal",
		name: "Beni Mellal",
		description: "Earthy natural design for NGO, development, and agricultural sectors with wider sidebar for skills.",
		style: "professional",
		industries: ["healthcare", "education", "general"],
		experienceLevel: ["entry", "mid", "senior"],
		previewImage: "/templates/jpg/beni-mellal.jpg",
		rating: 4.5,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#365314", "#4d7c0f", "#84cc16"],
		features: ["Morocco CV Fields", "NGO Style", "Earthy Design"],
		tags: ["Morocco", "NGO", "Development"],
	},
	{
		id: "taza",
		name: "Taza",
		description: "Ultra-compact ATS-optimized layout with maximum content density and no decorative elements.",
		style: "classic",
		industries: ["technology", "finance", "engineering", "general"],
		experienceLevel: ["entry", "mid", "senior"],
		previewImage: "/templates/jpg/taza.jpg",
		rating: 4.8,
		reviewCount: 0,
		downloadCount: 0,
		isTrending: false,
		isNew: true,
		isPremium: false,
		colors: ["#171717", "#404040", "#737373"],
		features: ["Morocco CV Fields", "ATS Optimized", "Maximum Density"],
		tags: ["Morocco", "ATS", "Compact"],
	},
];

const templateGalleryOverrides: Record<string, Partial<ResumeTemplate>> = {
	azurill: {
		name: "Atlas Corporate",
		description: "CV sobre et recruteur-friendly pour stages en finance, commerce, gestion et fonctions support.",
		rating: 4.8,
		reviewCount: 96,
		downloadCount: 5480,
		isTrending: false,
		features: ["Compatible ATS", "Deux colonnes lisibles", "Compétences visibles"],
		tags: ["Stage", "Finance", "ATS"],
	},
	bronzor: {
		name: "Finance Conseil",
		description:
			"Présentation structurée pour banque, assurance, cabinet comptable et métiers administratifs exigeants.",
		style: "professional",
		industries: ["finance", "legal", "general"],
		reviewCount: 84,
		downloadCount: 4960,
		isTrending: false,
		features: ["Structure classique", "Rubriques nettes", "Très lisible"],
		tags: ["Banque", "Conseil", "Pro"],
	},
	chikorita: {
		name: "Relation Client",
		description: "Modèle moderne pour profils commerciaux, RH, accueil, centre d'appel et métiers orientés client.",
		industries: ["marketing", "education", "general"],
		reviewCount: 73,
		downloadCount: 4620,
		isTrending: false,
		features: ["Photo équilibrée", "Parcours clair", "Langues mises en avant"],
		tags: ["Commerce", "RH", "Accueil"],
	},
	ditto: {
		name: "Standard ATS",
		description: "CV textuel et dense pensé pour passer les logiciels de recrutement sans perdre la hiérarchie.",
		style: "classic",
		reviewCount: 102,
		downloadCount: 5840,
		isTrending: false,
		features: ["ATS optimisé", "Une page possible", "Aucune distraction"],
		tags: ["ATS", "Simple", "Efficace"],
	},
	gengar: {
		name: "Business Operations",
		description:
			"Design précis pour analystes, assistants manager, coordinateurs opérationnels et profils polyvalents.",
		style: "professional",
		industries: ["finance", "technology", "general"],
		reviewCount: 67,
		downloadCount: 4280,
		isTrending: false,
		features: ["Indicateurs clairs", "Chronologie lisible", "Profil polyvalent"],
		tags: ["Gestion", "Operations", "Analyse"],
	},
	glalie: {
		name: "Juridique Minimal",
		description: "CV discret et formel pour juridique, administration, finance ou candidatures institutionnelles.",
		style: "classic",
		industries: ["legal", "finance", "general"],
		reviewCount: 61,
		downloadCount: 3790,
		isTrending: false,
		features: ["Minimal", "Très formel", "Lecture rapide"],
		tags: ["Juridique", "Admin", "Classique"],
	},
	kakuna: {
		name: "Stage Compact",
		description: "Format compact pour étudiants avec peu d'expérience, idéal pour stage, alternance et premier emploi.",
		experienceLevel: ["entry"],
		reviewCount: 79,
		downloadCount: 4360,
		isTrending: false,
		features: ["Débutant", "Compact", "Objectif visible"],
		tags: ["Étudiant", "Stage", "1 page"],
	},
	lapras: {
		name: "Senior Entreprise",
		description:
			"CV sérieux pour profils confirmés, responsables d'équipe, gestion de projet et environnement corporate.",
		reviewCount: 58,
		downloadCount: 3660,
		isTrending: false,
		features: ["Expérience valorisée", "Ton senior", "Export PDF propre"],
		tags: ["Senior", "Entreprise", "Management"],
	},
	leafish: {
		name: "Santé & Social",
		description: "Modèle calme pour santé, social, ONG, éducation et profils avec certifications ou bénévolat.",
		style: "professional",
		industries: ["healthcare", "education", "general"],
		reviewCount: 64,
		downloadCount: 3920,
		isTrending: false,
		features: ["Certifications", "Bénévolat", "Langues"],
		tags: ["Santé", "Social", "ONG"],
	},
	onyx: {
		name: "Direction Executive",
		description:
			"Présentation premium pour direction, management, finance senior et candidatures à forte responsabilité.",
		reviewCount: 76,
		downloadCount: 5170,
		isTrending: false,
		features: ["Direction", "Premium", "Leadership"],
		tags: ["Executive", "Senior", "Premium"],
	},
	pikachu: {
		name: "Communication Junior",
		description: "CV vivant mais contrôlé pour marketing, communication, contenu, réseaux sociaux et junior créatif.",
		reviewCount: 70,
		downloadCount: 4510,
		isTrending: false,
		features: ["Accroche visible", "Portfolio possible", "Couleur maîtrisée"],
		tags: ["Marketing", "Junior", "Créatif"],
	},
	rhyhorn: {
		name: "Portfolio Moderne",
		description:
			"Modèle projet pour développeurs, designers, techniciens et profils qui doivent montrer des réalisations.",
		reviewCount: 72,
		downloadCount: 4720,
		isTrending: false,
		features: ["Projets détaillés", "Compétences techniques", "Liens portfolio"],
		tags: ["Projet", "Tech", "Portfolio"],
	},
	avicenne: {
		name: "Avicenne Académique",
		description: "CV français raffiné pour recherche, santé, enseignement et candidatures académiques au Maroc.",
		reviewCount: 55,
		downloadCount: 3410,
		isTrending: false,
		tags: ["Recherche", "Santé", "Académique"],
	},
	fes: {
		name: "Fès Administratif",
		description:
			"Style français formel pour administration, banque, dossiers institutionnels et concours professionnels.",
		style: "classic",
		industries: ["legal", "finance", "general"],
		reviewCount: 69,
		downloadCount: 4040,
		isTrending: false,
		tags: ["Administration", "Formel", "Maroc"],
	},
	ditgar: {
		name: "Digital Product",
		description: "CV moderne pour développeurs, data, product, support IT et profils digitaux en croissance.",
		style: "tech",
		reviewCount: 91,
		downloadCount: 5790,
		isTrending: false,
		features: ["Stack technique", "Projets", "Impact mesurable"],
		tags: ["IT", "Data", "Produit"],
	},
	casablanca: {
		name: "Casablanca Corporate",
		reviewCount: 218,
		downloadCount: 13780,
		isTrending: true,
		features: ["CV français", "Deux colonnes", "Corporate"],
		tags: ["Casablanca", "Corporate", "Finance"],
	},
	rabat: {
		name: "Rabat Administratif",
		reviewCount: 176,
		downloadCount: 9820,
		isTrending: true,
		features: ["Dossier formel", "Champs Maroc", "Administration"],
		tags: ["Rabat", "Admin", "Formel"],
	},
	marrakech: {
		name: "Marrakech Créatif",
		reviewCount: 141,
		downloadCount: 8110,
		features: ["Accent chaleureux", "Communication", "Visuel maîtrisé"],
		tags: ["Créatif", "Marketing", "Design"],
	},
	tangier: {
		name: "Tanger ATS",
		reviewCount: 244,
		downloadCount: 16640,
		isTrending: true,
		features: ["ATS friendly", "International", "Bilingue"],
		tags: ["ATS", "International", "FR/AR"],
	},
	meknes: {
		name: "Meknès Banque & Droit",
		reviewCount: 119,
		downloadCount: 6940,
		features: ["Typographie formelle", "Banque", "Droit"],
		tags: ["Banque", "Droit", "Classique"],
	},
	oujda: {
		name: "Oujda Industrie",
		reviewCount: 132,
		downloadCount: 7320,
		features: ["Sidebar technique", "Industrie", "Maintenance"],
		tags: ["Industrie", "Technique", "Maintenance"],
	},
	kenitra: {
		name: "Kénitra Logistique",
		reviewCount: 108,
		downloadCount: 6210,
		features: ["Logistique", "Production", "Management terrain"],
		tags: ["Logistique", "Usine", "Technique"],
	},
	safi: {
		name: "Safi Technique",
		reviewCount: 197,
		downloadCount: 12480,
		isTrending: true,
		features: ["ATS friendly", "Compétences techniques", "Très dense"],
		tags: ["BTS", "Technique", "ATS"],
	},
	ifrane: {
		name: "Ifrane Académique",
		reviewCount: 86,
		downloadCount: 5120,
		features: ["Formation forte", "Recherche", "Stages académiques"],
		tags: ["Éducation", "Recherche", "Master"],
	},
	mohammedia: {
		name: "Mohammedia Executive",
		reviewCount: 93,
		downloadCount: 5840,
		features: ["Direction", "Whitespace premium", "Impact business"],
		tags: ["Direction", "Senior", "Premium"],
	},
	chefchaouen: {
		name: "Chefchaouen Créatif",
		reviewCount: 121,
		downloadCount: 7460,
		features: ["Couleur maîtrisée", "Créatif", "Portfolio"],
		tags: ["Design", "Créatif", "Portfolio"],
	},
	essaouira: {
		name: "Essaouira Freelance",
		reviewCount: 101,
		downloadCount: 6430,
		features: ["Freelance", "Minimal", "Client-ready"],
		tags: ["Freelance", "Minimal", "Portfolio"],
	},
	tetouan: {
		name: "Tétouan Artisanat",
		reviewCount: 74,
		downloadCount: 4210,
		features: ["Touche artisanale", "Compétences", "Culture"],
		tags: ["Artisanat", "Culture", "Créatif"],
	},
	agadir: {
		name: "Agadir Hôtellerie",
		reviewCount: 184,
		downloadCount: 11940,
		isTrending: true,
		features: ["Langues visibles", "Service client", "Certifications"],
		tags: ["Hôtellerie", "Tourisme", "Langues"],
	},
	dakhla: {
		name: "Dakhla Business Tech",
		reviewCount: 137,
		downloadCount: 8730,
		features: ["Contraste fort", "Business tech", "Profil ambitieux"],
		tags: ["Tech", "Business", "Moderne"],
	},
	settat: {
		name: "Settat Étudiant",
		reviewCount: 269,
		downloadCount: 18720,
		isTrending: true,
		features: ["Sans expérience", "Stage", "1 page"],
		tags: ["Étudiant", "Stage", "Débutant"],
	},
	jadida: {
		name: "El Jadida Polyvalent",
		reviewCount: 205,
		downloadCount: 14520,
		isTrending: true,
		features: ["Polyvalent", "Équilibré", "Tous secteurs"],
		tags: ["Polyvalent", "Pro", "Maroc"],
	},
	nador: {
		name: "Nador Bilingue",
		reviewCount: 113,
		downloadCount: 7080,
		features: ["Français / arabe", "International", "RTL aware"],
		tags: ["Bilingue", "FR/AR", "International"],
	},
	"beni-mellal": {
		name: "Béni Mellal ONG",
		reviewCount: 82,
		downloadCount: 4930,
		features: ["ONG", "Développement", "Engagement terrain"],
		tags: ["ONG", "Social", "Développement"],
	},
	taza: {
		name: "Taza ATS Compact",
		reviewCount: 224,
		downloadCount: 15110,
		isTrending: true,
		features: ["ATS optimisé", "Ultra compact", "Sans décoration"],
		tags: ["ATS", "Compact", "Recruteur"],
	},
};

export const resumeTemplates: ResumeTemplate[] = baseResumeTemplates.map((template) => ({
	...template,
	...(templateGalleryOverrides[template.id] ?? {}),
}));

// Sample reviews data
export const sampleReviews: TemplateReview[] = [
	{
		id: "rev-1",
		templateId: "settat",
		userName: "Youssef Ait Lahcen",
		rating: 5,
		comment: "Très utile pour mon premier CV de stage. Le recruteur a trouvé le document clair et facile à lire.",
		date: "2026-02-15",
		helpful: 45,
	},
	{
		id: "rev-2",
		templateId: "casablanca",
		userName: "Salma Bennani",
		rating: 4,
		comment: "Le style corporate fonctionne bien pour finance et gestion. J'ai gardé une seule page sans problème.",
		date: "2026-02-10",
		helpful: 23,
	},
	{
		id: "rev-3",
		templateId: "tangier",
		userName: "Noura El Amrani",
		rating: 5,
		comment: "Le format ATS est propre, surtout pour les candidatures en ligne et les offres internationales.",
		date: "2026-02-18",
		helpful: 67,
	},
	{
		id: "rev-4",
		templateId: "safi",
		userName: "Mehdi Karimi",
		rating: 5,
		comment: "Bon choix pour un profil technique. Les compétences et projets restent visibles sans paraître chargés.",
		date: "2026-02-12",
		helpful: 89,
	},
	{
		id: "rev-5",
		templateId: "agadir",
		userName: "Imane El Fassi",
		rating: 4,
		comment: "Parfait pour hôtellerie et tourisme, surtout avec les langues et les certificats visibles.",
		date: "2026-02-20",
		helpful: 34,
	},
];
