import z from "zod";

// Career category schema including technology and management
export const careerCategorySchema = z.enum(["healthcare", "industrial", "hse", "technology", "management"]);

// Career program type
const careerProgramSchema = z.object({
	id: z.string().uuid(),
	name: z.string(),
	nameFr: z.string(),
	category: careerCategorySchema,
	duration: z.string(),
	durationFr: z.string(),
	durationMonths: z.number(),
	cost: z.number(),
	salaryRange: z.object({
		min: z.number(),
		max: z.number(),
		currency: z.string(),
	}),
	employmentRate: z.number(),
	requiredSkills: z.array(z.string()),
	requiredSkillsFr: z.array(z.string()),
	description: z.string(),
	descriptionFr: z.string(),
	prospects: z.array(z.string()),
	prospectsFr: z.array(z.string()),
	certification: z.string(),
	certificationFr: z.string(),
	demandLevel: z.enum(["high", "medium", "low", "very_high"]),
	growthRate: z.number(),
	careerPathways: z.array(
		z.object({
			title: z.string(),
			titleFr: z.string(),
			description: z.string(),
			descriptionFr: z.string(),
			yearsExperience: z.string(),
		}),
	),
	icon: z.string(),
});

// Assessment question type
const assessmentQuestionSchema = z.object({
	id: z.string().uuid(),
	question: z.string(),
	questionFr: z.string(),
	category: z.enum(["environment", "work_style", "interests", "stress", "goals"]),
	options: z.array(
		z.object({
			id: z.string().uuid(),
			text: z.string(),
			textFr: z.string(),
			careerWeights: z.object({
				healthcare: z.number(),
				industrial: z.number(),
				hse: z.number(),
				technology: z.number(),
			}),
		}),
	),
});

// Market insight type
const marketInsightSchema = z.object({
	field: careerCategorySchema,
	employmentRate: z.number(),
	averageSalary: z.number(),
	salaryRange: z.object({
		min: z.number(),
		max: z.number(),
		currency: z.string(),
	}),
	demandLevel: z.enum(["low", "medium", "high", "very_high"]),
	growthProjection: z.object({
		percentage: z.number(),
		period: z.string(),
	}),
	topSkills: z.array(z.string()),
	topSkillsFr: z.array(z.string()),
	jobOpenings: z.number(),
	trends: z.array(
		z.object({
			trend: z.string(),
			trendFr: z.string(),
			impact: z.enum(["positive", "neutral", "negative"]),
		}),
	),
});

// Employer type
const employerSchema = z.object({
	id: z.string().uuid(),
	name: z.string(),
	sector: z.string(),
	sectorFr: z.string(),
	location: z.string(),
	locationFr: z.string(),
	employeeCount: z.string(),
	description: z.string(),
	descriptionFr: z.string(),
	hiringFields: z.array(careerCategorySchema),
	benefits: z.array(z.string()),
	benefitsFr: z.array(z.string()),
	website: z.string().optional(),
	averageSalary: z.object({
		min: z.number(),
		max: z.number(),
		currency: z.string(),
	}),
});

// Salary statistics type
const salaryStatisticsSchema = z.object({
	programId: z.string(),
	averageSalary: z.number(),
	minSalary: z.number(),
	maxSalary: z.number(),
	currency: z.string(),
	experienceLevels: z.array(
		z.object({
			level: z.string(),
			levelFr: z.string(),
			yearsExperience: z.string(),
			averageSalary: z.number(),
			range: z.object({
				min: z.number(),
				max: z.number(),
			}),
		}),
	),
	byRegion: z.array(
		z.object({
			region: z.string(),
			regionFr: z.string(),
			averageSalary: z.number(),
			costOfLivingIndex: z.number(),
		}),
	),
	trends: z.object({
		yearOverYearGrowth: z.number(),
		projectedGrowth2025: z.number(),
	}),
});

// Career programs data
export const careerPrograms: z.infer<typeof careerProgramSchema>[] = [
	// Healthcare programs
	{
		id: "sage-femme",
		name: "Midwife",
		nameFr: "Sage-Femme",
		category: "healthcare",
		duration: "3 years",
		durationFr: "3 ans",
		durationMonths: 36,
		cost: 45000,
		salaryRange: { min: 6000, max: 15000, currency: "MAD" },
		employmentRate: 92,
		requiredSkills: ["Communication", "Empathy", "Stress resistance", "Medical knowledge", "Teamwork"],
		requiredSkillsFr: [
			"Communication",
			"Empathie",
			"Resistance au stress",
			"Connaissances médicales",
			"Travail d'équipe",
		],
		description: "Healthcare professional specializing in pregnancy, childbirth, and postnatal care.",
		descriptionFr:
			"Professionnel de santé spécialisé dans le suivi de la grossesse, l'accouchement et les soins postnataux.",
		prospects: ["Public hospitals", "Private clinics", "Maternity centers", "Independent practice"],
		prospectsFr: ["Hôpitaux publics", "Cliniques privées", "Maternités", "Exercice libéral"],
		certification: "State Diploma of Midwife",
		certificationFr: "Diplôme d'État de Sage-Femme",
		demandLevel: "high",
		growthRate: 8.5,
		careerPathways: [
			{
				title: "Junior Midwife",
				titleFr: "Sage-Femme Debutante",
				description: "Entry-level position in hospital or clinic",
				descriptionFr: "Poste d'entrée en hôpital ou clinique",
				yearsExperience: "0-2",
			},
			{
				title: "Senior Midwife",
				titleFr: "Sage-Femme Senior",
				description: "Experienced practitioner with specialized skills",
				descriptionFr: "Praticienne expérimentée avec compétences spécialisées",
				yearsExperience: "3-5",
			},
			{
				title: "Head Midwife",
				titleFr: "Sage-Femme Chef",
				description: "Leadership role managing maternity unit",
				descriptionFr: "Rôle de leadership gérant une unité de maternite",
				yearsExperience: "5+",
			},
		],
		icon: "FirstAidKit",
	},
	{
		id: "infirmier-polyvalent",
		name: "General Nurse",
		nameFr: "Infirmier Polyvalent",
		category: "healthcare",
		duration: "3 years",
		durationFr: "3 ans",
		durationMonths: 36,
		cost: 42000,
		salaryRange: { min: 5500, max: 12000, currency: "MAD" },
		employmentRate: 95,
		requiredSkills: ["Nursing care", "Communication", "Stress management", "Teamwork", "Rigor"],
		requiredSkillsFr: ["Soins infirmiers", "Communication", "Gestion du stress", "Travail d'équipe", "Rigueur"],
		description:
			"Versatile healthcare professional providing comprehensive patient care across various medical settings.",
		descriptionFr:
			"Professionnel de santé polyvalent assurant des soins complets aux patients dans divers contextes médicaux.",
		prospects: ["Hospitals", "Clinics", "Health centers", "Home care", "Schools"],
		prospectsFr: ["Hôpitaux", "Cliniques", "Centres de santé", "Soins à domicile", "Établissements scolaires"],
		certification: "State Nursing Diploma",
		certificationFr: "Diplôme d'État d'Infirmier",
		demandLevel: "very_high",
		growthRate: 10.2,
		careerPathways: [
			{
				title: "Staff Nurse",
				titleFr: "Infirmier de Service",
				description: "General nursing duties in various departments",
				descriptionFr: "Fonctions infirmières générales dans différents services",
				yearsExperience: "0-2",
			},
			{
				title: "Specialized Nurse",
				titleFr: "Infirmier Spécialisé",
				description: "Focused on specific medical specialty",
				descriptionFr: "Spécialisé dans une branche médicale spécifique",
				yearsExperience: "3-5",
			},
			{
				title: "Head Nurse",
				titleFr: "Infirmier Chef",
				description: "Management of nursing team and unit",
				descriptionFr: "Gestion de l'équipe infirmière et de l'unité",
				yearsExperience: "5+",
			},
		],
		icon: "Heartbeat",
	},
	{
		id: "aide-soignant",
		name: "Healthcare Assistant",
		nameFr: "Aide Soignant",
		category: "healthcare",
		duration: "1 year",
		durationFr: "1 an",
		durationMonths: 12,
		cost: 18000,
		salaryRange: { min: 3500, max: 6000, currency: "MAD" },
		employmentRate: 88,
		requiredSkills: ["Empathy", "Patience", "Hygiene", "Communication", "Physical work"],
		requiredSkillsFr: ["Empathie", "Patience", "Hygiène", "Communication", "Travail physique"],
		description: "Support healthcare professionals in providing daily patient care and comfort.",
		descriptionFr: "Soutient les professionnels de santé dans les soins quotidiens et le confort des patients.",
		prospects: ["Hospitals", "Nursing homes", "Home care", "Rehabilitation centers"],
		prospectsFr: ["Hôpitaux", "Maisons de retraite", "Soins à domicile", "Centres de rééducation"],
		certification: "Healthcare Assistant Diploma",
		certificationFr: "Diplôme d'Aide-Soignant",
		demandLevel: "high",
		growthRate: 12.0,
		careerPathways: [
			{
				title: "Nursing Assistant",
				titleFr: "Aide Soignant",
				description: "Direct patient care under nurse supervision",
				descriptionFr: "Soins directs aux patients sous supervision infirmière",
				yearsExperience: "0-2",
			},
			{
				title: "Senior Nursing Assistant",
				titleFr: "Aide Soignant Senior",
				description: "Experienced assistant with specialized training",
				descriptionFr: "Assistant expérimenté avec formation spécialisée",
				yearsExperience: "3-5",
			},
		],
		icon: "HandHeart",
	},
	{
		id: "infirmier-auxiliaire",
		name: "Auxiliary Nurse",
		nameFr: "Infirmier Auxiliaire",
		category: "healthcare",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 28000,
		salaryRange: { min: 4500, max: 8000, currency: "MAD" },
		employmentRate: 90,
		requiredSkills: ["Basic care", "Observation", "Communication", "Hygiene", "Medical assistance"],
		requiredSkillsFr: ["Soins de base", "Observation", "Communication", "Hygiène", "Assistance médicale"],
		description: "Provide basic nursing care under the supervision of registered nurses and physicians.",
		descriptionFr: "Fournit des soins infirmiers de base sous la supervision des infirmiers diplômés et des médecins.",
		prospects: ["Hospitals", "Clinics", "Medical offices", "Long-term care facilities"],
		prospectsFr: ["Hôpitaux", "Cliniques", "Cabinets médicaux", "Établissements de soins de longue durée"],
		certification: "Auxiliary Nurse Diploma",
		certificationFr: "Diplôme d'Infirmier Auxiliaire",
		demandLevel: "medium",
		growthRate: 7.5,
		careerPathways: [
			{
				title: "Auxiliary Nurse",
				titleFr: "Infirmier Auxiliaire",
				description: "Basic nursing care in community settings",
				descriptionFr: "Soins infirmiers de base en milieu communautaire",
				yearsExperience: "0-2",
			},
			{
				title: "Community Health Nurse",
				titleFr: "Infirmier de Santé Communautaire",
				description: "Specialized in community outreach programs",
				descriptionFr: "Spécialisé dans les programmes de sensibilisation communautaire",
				yearsExperience: "3-5",
			},
		],
		icon: "Stethoscope",
	},
	// Industrial programs
	{
		id: "conducteur-engins",
		name: "Heavy Equipment Operator",
		nameFr: "Conducteur d'Engins",
		category: "industrial",
		duration: "6 months",
		durationFr: "6 mois",
		durationMonths: 6,
		cost: 15000,
		salaryRange: { min: 5000, max: 10000, currency: "MAD" },
		employmentRate: 85,
		requiredSkills: ["Equipment operation", "Safety", "Basic maintenance", "Coordination", "Vigilance"],
		requiredSkillsFr: ["Conduite d'engins", "Sécurité", "Maintenance de base", "Coordination", "Vigilance"],
		description: "Operate heavy machinery and equipment in construction, mining, and industrial settings.",
		descriptionFr:
			"Opère des machines lourdes et des équipements dans les secteurs de la construction, des mines et de l'industrie.",
		prospects: ["Construction companies", "Mining operations", "Public works", "Logistics"],
		prospectsFr: ["Entreprises de construction", "Exploitations minières", "Travaux publics", "Logistique"],
		certification: "CACES - Certificate of Ability to Operate Equipment Safely",
		certificationFr: "CACES - Certificat d'Aptitude à la Conduite d'Engins en Sécurité",
		demandLevel: "high",
		growthRate: 9.0,
		careerPathways: [
			{
				title: "Equipment Operator",
				titleFr: "Conducteur d'Engins",
				description: "Operating heavy machinery on sites",
				descriptionFr: "Conduite de machines lourdes sur les chantiers",
				yearsExperience: "0-2",
			},
			{
				title: "Senior Operator",
				titleFr: "Conducteur Senior",
				description: "Specialized in complex equipment",
				descriptionFr: "Spécialisé dans les équipements complexes",
				yearsExperience: "3-5",
			},
			{
				title: "Site Supervisor",
				titleFr: "Chef de Chantier",
				description: "Managing equipment teams",
				descriptionFr: "Gestion des équipes d'engins",
				yearsExperience: "5+",
			},
		],
		icon: "Truck",
	},
	{
		id: "mecanique-engins",
		name: "Heavy Equipment Mechanic",
		nameFr: "Mécanicien d'Engins",
		category: "industrial",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 32000,
		salaryRange: { min: 5500, max: 11000, currency: "MAD" },
		employmentRate: 88,
		requiredSkills: ["Mechanics", "Diagnostics", "Hydraulics", "Electrical", "Problem solving"],
		requiredSkillsFr: ["Mécanique", "Diagnostic", "Hydraulique", "Électricité", "Résolution de problèmes"],
		description: "Maintain, repair, and service heavy equipment and machinery.",
		descriptionFr: "Entretient, repare et assure la maintenance des engins et machines lourdes.",
		prospects: ["Equipment dealers", "Construction companies", "Mining", "Rental companies"],
		prospectsFr: ["Concessionnaires", "Entreprises de construction", "Mines", "Societes de location"],
		certification: "Heavy Equipment Mechanic Technician Diploma",
		certificationFr: "Diplôme de Technicien en Mécanique d'Engins",
		demandLevel: "high",
		growthRate: 8.0,
		careerPathways: [
			{
				title: "Junior Mechanic",
				titleFr: "Mécanicien Junior",
				description: "Basic maintenance and repairs",
				descriptionFr: "Maintenance et réparations de base",
				yearsExperience: "0-2",
			},
			{
				title: "Senior Mechanic",
				titleFr: "Mécanicien Senior",
				description: "Complex diagnostics and repairs",
				descriptionFr: "Diagnostics et réparations complexes",
				yearsExperience: "3-5",
			},
			{
				title: "Workshop Manager",
				titleFr: "Chef d'Atelier",
				description: "Managing maintenance operations",
				descriptionFr: "Gestion des opérations de maintenance",
				yearsExperience: "5+",
			},
		],
		icon: "Wrench",
	},
	{
		id: "electromecanique",
		name: "Electromechanics",
		nameFr: "Électromécanique",
		category: "industrial",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 35000,
		salaryRange: { min: 5500, max: 12000, currency: "MAD" },
		employmentRate: 90,
		requiredSkills: ["Electrical troubleshooting", "Motor maintenance", "PLC basics", "Hydraulics", "Pneumatics"],
		requiredSkillsFr: [
			"Dépannage électrique",
			"Maintenance des moteurs",
			"Bases automate",
			"Hydraulique",
			"Pneumatique",
		],
		description:
			"Comprehensive training in electrical and mechanical systems maintenance, covering motors, PLCs, hydraulics, pneumatics, and industrial automation.",
		descriptionFr:
			"Formation complète en maintenance des systèmes électriques et mécaniques, couvrant les moteurs, les automates programmables, l'hydraulique, la pneumatique et l'automatisation industrielle.",
		prospects: ["Manufacturing plants", "Industrial maintenance", "Power plants", "Automotive industry"],
		prospectsFr: ["Usines de fabrication", "Maintenance industrielle", "Centrales électriques", "Industrie automobile"],
		certification: "Electromechanical Technician Diploma",
		certificationFr: "Diplôme de Technicien Électromécanique",
		demandLevel: "high",
		growthRate: 11.0,
		careerPathways: [
			{
				title: "Electromechanical Technician",
				titleFr: "Technicien Électromécanique",
				description: "Entry-level maintenance and repair",
				descriptionFr: "Maintenance et réparations de niveau débutant",
				yearsExperience: "0-2",
			},
			{
				title: "Senior Technician",
				titleFr: "Technicien Senior",
				description: "Complex diagnostics and system optimization",
				descriptionFr: "Diagnostics complexes et optimisation des systèmes",
				yearsExperience: "3-5",
			},
			{
				title: "Maintenance Supervisor",
				titleFr: "Superviseur de Maintenance",
				description: "Managing maintenance teams and planning",
				descriptionFr: "Gestion des équipes de maintenance et planification",
				yearsExperience: "5+",
			},
		],
		icon: "Zap",
	},
	{
		id: "cariste-professionnel",
		name: "Forklift Operator",
		nameFr: "Cariste Professionnel",
		category: "industrial",
		duration: "3 months",
		durationFr: "3 mois",
		durationMonths: 3,
		cost: 8000,
		salaryRange: { min: 4000, max: 7000, currency: "MAD" },
		employmentRate: 90,
		requiredSkills: ["Forklift operation", "Safety", "Organization", "Material handling", "Vigilance"],
		requiredSkillsFr: ["Conduite de chariot", "Sécurité", "Organisation", "Manutention", "Vigilance"],
		description: "Operate forklifts and material handling equipment in warehouses and industrial facilities.",
		descriptionFr:
			"Opère des chariots élévateurs et équipements de manutention dans les entrepôts et installations industrielles.",
		prospects: ["Warehouses", "Factories", "Logistics centers", "Ports"],
		prospectsFr: ["Entrepôts", "Usines", "Centres logistiques", "Ports"],
		certification: "CACES R489 - Forklifts",
		certificationFr: "CACES R489 - Chariots Élévateurs",
		demandLevel: "high",
		growthRate: 11.0,
		careerPathways: [
			{
				title: "Forklift Operator",
				titleFr: "Cariste",
				description: "Basic warehouse handling operations",
				descriptionFr: "Operations de manutention de base en entrepôt",
				yearsExperience: "0-2",
			},
			{
				title: "Lead Operator",
				titleFr: "Cariste Chef d'Équipe",
				description: "Coordinating handling team",
				descriptionFr: "Coordination de l'équipe de manutention",
				yearsExperience: "3-5",
			},
			{
				title: "Warehouse Supervisor",
				titleFr: "Responsable d'Entrepot",
				description: "Managing warehouse operations",
				descriptionFr: "Gestion des opérations d'entrepôt",
				yearsExperience: "5+",
			},
		],
		icon: "Package",
	},
	{
		id: "soudure",
		name: "Welding",
		nameFr: "Soudure",
		category: "industrial",
		duration: "1 year",
		durationFr: "1 an",
		durationMonths: 12,
		cost: 20000,
		salaryRange: { min: 5000, max: 11000, currency: "MAD" },
		employmentRate: 86,
		requiredSkills: ["MIG welding", "TIG welding", "Arc welding", "Blueprint reading", "Quality control"],
		requiredSkillsFr: ["Soudure MIG", "Soudure TIG", "Soudure à l'arc", "Lecture de plans", "Contrôle qualite"],
		description:
			"Industrial welding certification training covering MIG, TIG, and arc welding techniques for various metals and industrial applications.",
		descriptionFr:
			"Formation certifiante en soudure industrielle couvrant les techniques MIG, TIG et soudure à l'arc pour divers métaux et applications industrielles.",
		prospects: ["Construction companies", "Shipbuilding", "Pipeline industry", "Automotive industry"],
		prospectsFr: [
			"Entreprises de construction",
			"Construction navale",
			"Industrie des pipelines",
			"Industrie automobile",
		],
		certification: "Industrial Welder Diploma",
		certificationFr: "Diplôme de Soudeur Industriel",
		demandLevel: "high",
		growthRate: 7.5,
		careerPathways: [
			{
				title: "Junior Welder",
				titleFr: "Soudeur Junior",
				description: "Basic welding tasks under supervision",
				descriptionFr: "Taches de soudure de base sous supervision",
				yearsExperience: "0-2",
			},
			{
				title: "Certified Welder",
				titleFr: "Soudeur Certifie",
				description: "Independent work on complex projects",
				descriptionFr: "Travail independant sur des projets complexes",
				yearsExperience: "2-5",
			},
			{
				title: "Welding Inspector",
				titleFr: "Inspecteur de Soudure",
				description: "Quality control and team management",
				descriptionFr: "Contrôle qualite et gestion d'équipe",
				yearsExperience: "5+",
			},
		],
		icon: "Flame",
	},
	// HSE programs
	{
		id: "hse-specialist",
		name: "HSE Specialist",
		nameFr: "Spécialiste HSE",
		category: "hse",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 35000,
		salaryRange: { min: 6000, max: 15000, currency: "MAD" },
		employmentRate: 93,
		requiredSkills: ["HSE regulations", "Risk assessment", "Training", "Communication", "Auditing"],
		requiredSkillsFr: ["Réglementation HSE", "Évaluation des risques", "Formation", "Communication", "Audit"],
		description: "Develop and implement health, safety, and environmental programs to ensure workplace compliance.",
		descriptionFr:
			"Développe et met en œuvre des programmes de santé, sécurité et environnement pour assurer la conformité au travail.",
		prospects: ["All industries", "Consulting", "Government", "Oil & Gas", "Manufacturing"],
		prospectsFr: ["Toutes industries", "Conseil", "Administration", "Petrole et Gaz", "Industrie"],
		certification: "HSE Technician Diploma / NEBOSH",
		certificationFr: "Diplôme de Technicien HSE / NEBOSH",
		demandLevel: "very_high",
		growthRate: 15.0,
		careerPathways: [
			{
				title: "HSE Coordinator",
				titleFr: "Coordinateur HSE",
				description: "Entry-level safety coordination role",
				descriptionFr: "Poste de coordination sécurité d'entrée",
				yearsExperience: "0-2",
			},
			{
				title: "HSE Manager",
				titleFr: "Responsable HSE",
				description: "Managing HSE department and policies",
				descriptionFr: "Gestion du département et des politiques HSE",
				yearsExperience: "3-5",
			},
			{
				title: "HSE Director",
				titleFr: "Directeur HSE",
				description: "Strategic leadership of HSE function",
				descriptionFr: "Leadership stratégique de la fonction HSE",
				yearsExperience: "7+",
			},
		],
		icon: "HardHat",
	},
	// Technology programs
	{
		id: "developpeur-web",
		name: "Web Developer",
		nameFr: "Développeur Web",
		category: "technology",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 40000,
		salaryRange: { min: 6000, max: 18000, currency: "MAD" },
		employmentRate: 85,
		requiredSkills: ["HTML/CSS/JavaScript", "React/Vue", "Node.js/PHP", "Databases", "Git"],
		requiredSkillsFr: ["HTML/CSS/JavaScript", "React/Vue", "Node.js/PHP", "Bases de données", "Git"],
		description:
			"Training in modern web development technologies including frontend, backend, databases, and deployment.",
		descriptionFr:
			"Formation aux technologies modernes du développement web incluant frontend, backend, bases de données et déploiement.",
		prospects: ["Tech companies", "Web agencies", "Startups", "Freelance", "E-commerce"],
		prospectsFr: ["Entreprises tech", "Agences web", "Startups", "Freelance", "E-commerce"],
		certification: "Web Developer Diploma",
		certificationFr: "Diplôme de Développeur Web",
		demandLevel: "very_high",
		growthRate: 20.0,
		careerPathways: [
			{
				title: "Junior Developer",
				titleFr: "Développeur Junior",
				description: "Entry-level development work",
				descriptionFr: "Travail de développement de niveau débutant",
				yearsExperience: "0-2",
			},
			{
				title: "Full Stack Developer",
				titleFr: "Développeur Full Stack",
				description: "Frontend and backend expertise",
				descriptionFr: "Expertise frontend et backend",
				yearsExperience: "2-5",
			},
			{
				title: "Tech Lead",
				titleFr: "Tech Lead",
				description: "Technical leadership and architecture",
				descriptionFr: "Leadership technique et architecture",
				yearsExperience: "5+",
			},
		],
		icon: "Code",
	},
	{
		id: "data-analyst",
		name: "Data Analyst",
		nameFr: "Analyste de Donnees",
		category: "technology",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 45000,
		salaryRange: { min: 8000, max: 20000, currency: "MAD" },
		employmentRate: 82,
		requiredSkills: ["Python/R", "SQL", "Data visualization", "Statistics", "Machine learning basics"],
		requiredSkillsFr: ["Python/R", "SQL", "Visualisation de données", "Statistiques", "Bases du machine learning"],
		description:
			"Training in data analysis, visualization, and business intelligence to support data-driven decisions.",
		descriptionFr:
			"Formation en analyse de données, visualisation et business intelligence pour supporter les décisions basées sur les données.",
		prospects: ["Banks", "Telecom", "E-commerce", "Consulting", "Insurance"],
		prospectsFr: ["Banques", "Telecom", "E-commerce", "Conseil", "Assurance"],
		certification: "Data Analyst Diploma",
		certificationFr: "Diplôme d'Analyste de Donnees",
		demandLevel: "very_high",
		growthRate: 25.0,
		careerPathways: [
			{
				title: "Junior Data Analyst",
				titleFr: "Analyste de Donnees Junior",
				description: "Entry-level data analysis",
				descriptionFr: "Analyse de données de niveau débutant",
				yearsExperience: "0-2",
			},
			{
				title: "Senior Data Analyst",
				titleFr: "Analyste de Donnees Senior",
				description: "Complex analysis and modeling",
				descriptionFr: "Analyse complexe et modélisation",
				yearsExperience: "2-5",
			},
			{
				title: "Data Science Lead",
				titleFr: "Lead Data Science",
				description: "Leading data teams and strategy",
				descriptionFr: "Leadership des équipes data et stratégie",
				yearsExperience: "5+",
			},
		],
		icon: "BarChart",
	},
	// Management programs
	{
		id: "commerce-marketing-digital",
		name: "Commerce and Digital Marketing",
		nameFr: "Commerce et Marketing Digital",
		category: "management",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 32000,
		salaryRange: { min: 4500, max: 14000, currency: "MAD" },
		employmentRate: 84,
		requiredSkills: ["Sales techniques", "Social media", "SEO/SEA", "CRM", "Data analysis"],
		requiredSkillsFr: ["Techniques de vente", "Réseaux sociaux", "SEO/SEA", "CRM", "Analyse de données"],
		description:
			"Train in commercial techniques and digital marketing including social media, online advertising, and e-commerce.",
		descriptionFr:
			"Formation aux techniques commerciales et au marketing digital incluant les réseaux sociaux, la publicité en ligne et le e-commerce.",
		prospects: ["Communication agencies", "E-commerce companies", "Retail", "SMEs", "Startups"],
		prospectsFr: ["Agences de communication", "Entreprises e-commerce", "Distribution", "PME", "Startups"],
		certification: "Commercial and Digital Marketing Technician Diploma",
		certificationFr: "Diplôme de Technicien Commercial et Marketing Digital",
		demandLevel: "high",
		growthRate: 16.0,
		careerPathways: [
			{
				title: "Sales Representative / Digital Assistant",
				titleFr: "Commercial / Assistant Digital",
				description: "Prospecting, sales and social media management",
				descriptionFr: "Prospection, vente et gestion des réseaux sociaux",
				yearsExperience: "0-2",
			},
			{
				title: "Digital Marketing Officer",
				titleFr: "Charge de Marketing Digital",
				description: "Managing campaigns and online performance",
				descriptionFr: "Gestion des campagnes et de la performance en ligne",
				yearsExperience: "2-5",
			},
			{
				title: "Marketing Manager",
				titleFr: "Responsable Marketing",
				description: "Leading the marketing strategy and team",
				descriptionFr: "Pilotage de la stratégie et de l'équipe marketing",
				yearsExperience: "5+",
			},
		],
		icon: "Megaphone",
	},
	{
		id: "finance-comptabilite",
		name: "Finance and Accounting",
		nameFr: "Finance et Comptabilité",
		category: "management",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 30000,
		salaryRange: { min: 4500, max: 13000, currency: "MAD" },
		employmentRate: 88,
		requiredSkills: ["Accounting", "Taxation", "Payroll", "Sage software", "Financial reporting"],
		requiredSkillsFr: ["Comptabilité", "Fiscalité", "Paie", "Logiciel Sage", "États de synthese"],
		description: "Train in accounting, Moroccan taxation, payroll, and financial statement preparation.",
		descriptionFr: "Formation en comptabilité, fiscalité marocaine, paie et établissement des etats de synthese.",
		prospects: ["Accounting firms", "Banks", "Company finance departments", "Fiduciaries", "Audit firms"],
		prospectsFr: [
			"Cabinets comptables",
			"Banques",
			"Services financiers d'entreprises",
			"Fiduciaires",
			"Cabinets d'audit",
		],
		certification: "Finance and Accounting Technician Diploma",
		certificationFr: "Diplôme de Technicien en Finance et Comptabilité",
		demandLevel: "high",
		growthRate: 9.0,
		careerPathways: [
			{
				title: "Accounting Assistant",
				titleFr: "Aide-Comptable",
				description: "Bookkeeping and bank reconciliations",
				descriptionFr: "Saisie comptable et rapprochements bancaires",
				yearsExperience: "0-2",
			},
			{
				title: "Accountant",
				titleFr: "Comptable",
				description: "Full accounting, tax declarations and reporting",
				descriptionFr: "Comptabilité complète, déclarations fiscales et reporting",
				yearsExperience: "2-5",
			},
			{
				title: "Chief Accountant",
				titleFr: "Chef Comptable",
				description: "Managing the accounting department",
				descriptionFr: "Gestion du service comptable",
				yearsExperience: "5+",
			},
		],
		icon: "Calculator",
	},
	{
		id: "management-projets-industriels",
		name: "Industrial Project Management",
		nameFr: "Management de Projets Industriels",
		category: "management",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 35000,
		salaryRange: { min: 6000, max: 16000, currency: "MAD" },
		employmentRate: 86,
		requiredSkills: ["Planning", "Cost control", "Team coordination", "Risk management", "Reporting"],
		requiredSkillsFr: [
			"Planification",
			"Suivi des coûts",
			"Coordination d'équipes",
			"Gestion des risques",
			"Reporting",
		],
		description:
			"Train in industrial project management including planning, cost and deadline control, and team coordination.",
		descriptionFr:
			"Formation au management de projets industriels incluant la planification, le suivi des coûts et délais et la coordination des équipes.",
		prospects: [
			"Industrial companies",
			"Engineering offices",
			"Construction companies",
			"OCP Group",
			"Consulting firms",
		],
		prospectsFr: ["Entreprises industrielles", "Bureaux d'études", "Societes BTP", "OCP Group", "Cabinets de conseil"],
		certification: "Industrial Project Management Technician Diploma",
		certificationFr: "Diplôme de Technicien en Management de Projets Industriels",
		demandLevel: "high",
		growthRate: 12.0,
		careerPathways: [
			{
				title: "Project Assistant",
				titleFr: "Assistant Projet",
				description: "Planning support and project follow-up",
				descriptionFr: "Appui à la planification et suivi de projet",
				yearsExperience: "0-2",
			},
			{
				title: "Project Coordinator",
				titleFr: "Coordinateur de Projet",
				description: "Coordinating teams, costs and deadlines",
				descriptionFr: "Coordination des équipes, coûts et délais",
				yearsExperience: "2-5",
			},
			{
				title: "Project Manager",
				titleFr: "Chef de Projet",
				description: "Leading industrial projects end to end",
				descriptionFr: "Pilotage de projets industriels de bout en bout",
				yearsExperience: "5+",
			},
		],
		icon: "ClipboardText",
	},
	{
		id: "ressources-humaines-droit",
		name: "Human Resources and Labor Law",
		nameFr: "Ressources Humaines et Droit Social",
		category: "management",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 30000,
		salaryRange: { min: 4500, max: 13000, currency: "MAD" },
		employmentRate: 85,
		requiredSkills: ["Recruitment", "Payroll & CNSS", "Labor law", "HR administration", "Training"],
		requiredSkillsFr: ["Recrutement", "Paie et CNSS", "Droit du travail", "Administration RH", "Formation"],
		description:
			"Train in human resources management and Moroccan labor law including recruitment, payroll, and personnel administration.",
		descriptionFr:
			"Formation à la gestion des ressources humaines et au droit social marocain incluant le recrutement, la paie et l'administration du personnel.",
		prospects: ["Company HR departments", "Recruitment agencies", "HR consulting firms", "SMEs", "Industrial groups"],
		prospectsFr: [
			"Services RH d'entreprises",
			"Cabinets de recrutement",
			"Cabinets de conseil RH",
			"PME",
			"Groupes industriels",
		],
		certification: "Human Resources Technician Diploma",
		certificationFr: "Diplôme de Technicien en Ressources Humaines et Droit Social",
		demandLevel: "high",
		growthRate: 10.0,
		careerPathways: [
			{
				title: "HR Assistant",
				titleFr: "Assistant RH",
				description: "Personnel administration and payroll support",
				descriptionFr: "Administration du personnel et appui à la paie",
				yearsExperience: "0-2",
			},
			{
				title: "HR Officer",
				titleFr: "Charge des Ressources Humaines",
				description: "Recruitment, payroll and HR management",
				descriptionFr: "Recrutement, paie et gestion RH",
				yearsExperience: "2-5",
			},
			{
				title: "HR Manager",
				titleFr: "Responsable RH",
				description: "Leading the HR function and labor relations",
				descriptionFr: "Pilotage de la fonction RH et du dialogue social",
				yearsExperience: "5+",
			},
		],
		icon: "Users",
	},
	{
		id: "supply-chain-logistique",
		name: "Supply Chain and Logistics",
		nameFr: "Supply Chain et Logistique",
		category: "management",
		duration: "2 years",
		durationFr: "2 ans",
		durationMonths: 24,
		cost: 32000,
		salaryRange: { min: 5000, max: 14000, currency: "MAD" },
		employmentRate: 89,
		requiredSkills: ["Inventory management", "Warehouse management", "Transport", "ERP/WMS", "Cost optimization"],
		requiredSkillsFr: ["Gestion des stocks", "Gestion d'entrepôt", "Transport", "ERP/WMS", "Optimisation des coûts"],
		description: "Train in supply chain and logistics including procurement, inventory, warehousing, and transport.",
		descriptionFr:
			"Formation à la supply chain et la logistique incluant les approvisionnements, les stocks, l'entreposage et le transport.",
		prospects: ["Logistics platforms", "Tanger Med", "Transport companies", "Import-export firms", "Large retail"],
		prospectsFr: [
			"Plateformes logistiques",
			"Tanger Med",
			"Societes de transport",
			"Entreprises import-export",
			"Grande distribution",
		],
		certification: "Supply Chain and Logistics Technician Diploma",
		certificationFr: "Diplôme de Technicien en Supply Chain et Logistique",
		demandLevel: "very_high",
		growthRate: 14.0,
		careerPathways: [
			{
				title: "Logistics Assistant",
				titleFr: "Assistant Logistique",
				description: "Inventory and warehouse operations",
				descriptionFr: "Operations de stock et d'entrepôt",
				yearsExperience: "0-2",
			},
			{
				title: "Logistics Officer",
				titleFr: "Charge de Logistique",
				description: "Managing flows, transport and suppliers",
				descriptionFr: "Gestion des flux, du transport et des fournisseurs",
				yearsExperience: "2-5",
			},
			{
				title: "Supply Chain Manager",
				titleFr: "Responsable Supply Chain",
				description: "Leading the supply chain function",
				descriptionFr: "Pilotage de la fonction supply chain",
				yearsExperience: "5+",
			},
		],
		icon: "Package",
	},
];

// Assessment questions in French
export const assessmentQuestions: z.infer<typeof assessmentQuestionSchema>[] = [
	{
		id: "q1",
		question: "What type of work environment do you prefer?",
		questionFr: "Quel type d'environnement de travail préférez-vous?",
		category: "environment",
		options: [
			{
				id: "q1a",
				text: "Hospital or clinic with patients",
				textFr: "Hôpital ou clinique avec des patients",
				careerWeights: { healthcare: 3, industrial: 0, hse: 1, technology: 0 },
			},
			{
				id: "q1b",
				text: "Factory or industrial site",
				textFr: "Usine ou site industriel",
				careerWeights: { healthcare: 0, industrial: 3, hse: 2, technology: 0 },
			},
			{
				id: "q1c",
				text: "Office with focus on safety and compliance",
				textFr: "Bureau avec un accent sur la sécurité et la conformité",
				careerWeights: { healthcare: 1, industrial: 1, hse: 3, technology: 1 },
			},
			{
				id: "q1d",
				text: "Modern office with computers",
				textFr: "Bureau moderne avec ordinateurs",
				careerWeights: { healthcare: 0, industrial: 0, hse: 1, technology: 3 },
			},
		],
	},
	{
		id: "q2",
		question: "How do you prefer to work?",
		questionFr: "Comment préférez-vous travailler?",
		category: "work_style",
		options: [
			{
				id: "q2a",
				text: "Directly helping people in need",
				textFr: "En aidant directement les personnes dans le besoin",
				careerWeights: { healthcare: 3, industrial: 0, hse: 1, technology: 0 },
			},
			{
				id: "q2b",
				text: "Working with machines and tools",
				textFr: "En travaillant avec des machines et des outils",
				careerWeights: { healthcare: 0, industrial: 3, hse: 1, technology: 1 },
			},
			{
				id: "q2c",
				text: "Analyzing risks and ensuring compliance",
				textFr: "En analysant les risques et assurant la conformité",
				careerWeights: { healthcare: 1, industrial: 1, hse: 3, technology: 1 },
			},
			{
				id: "q2d",
				text: "Creating digital solutions and applications",
				textFr: "En créant des solutions numériques et applications",
				careerWeights: { healthcare: 0, industrial: 0, hse: 0, technology: 3 },
			},
		],
	},
	{
		id: "q3",
		question: "What interests you the most?",
		questionFr: "Qu'est-ce qui vous intéresse le plus?",
		category: "interests",
		options: [
			{
				id: "q3a",
				text: "Human anatomy and medicine",
				textFr: "L'anatomie humaine et la médecine",
				careerWeights: { healthcare: 3, industrial: 0, hse: 0, technology: 0 },
			},
			{
				id: "q3b",
				text: "How machines and systems work",
				textFr: "Le fonctionnement des machines et systèmes",
				careerWeights: { healthcare: 0, industrial: 3, hse: 1, technology: 2 },
			},
			{
				id: "q3c",
				text: "Preventing accidents and protecting people",
				textFr: "La prévention des accidents et la protection des personnes",
				careerWeights: { healthcare: 1, industrial: 1, hse: 3, technology: 0 },
			},
			{
				id: "q3d",
				text: "Programming and new technologies",
				textFr: "La programmation et les nouvelles technologies",
				careerWeights: { healthcare: 0, industrial: 1, hse: 0, technology: 3 },
			},
		],
	},
	{
		id: "q4",
		question: "How do you handle stressful situations?",
		questionFr: "Comment gérez-vous les situations stressantes?",
		category: "stress",
		options: [
			{
				id: "q4a",
				text: "I stay calm and focus on helping others",
				textFr: "Je reste calme et me concentre sur l'aide aux autres",
				careerWeights: { healthcare: 3, industrial: 1, hse: 2, technology: 0 },
			},
			{
				id: "q4b",
				text: "I analyze the problem methodically",
				textFr: "J'analyse le problème méthodiquement",
				careerWeights: { healthcare: 1, industrial: 3, hse: 2, technology: 2 },
			},
			{
				id: "q4c",
				text: "I follow established protocols",
				textFr: "Je suis les protocoles établis",
				careerWeights: { healthcare: 2, industrial: 2, hse: 3, technology: 1 },
			},
			{
				id: "q4d",
				text: "I look for innovative solutions",
				textFr: "Je cherche des solutions innovantes",
				careerWeights: { healthcare: 0, industrial: 1, hse: 1, technology: 3 },
			},
		],
	},
	{
		id: "q5",
		question: "What is your main career goal?",
		questionFr: "Quel est votre principal objectif de carrière?",
		category: "goals",
		options: [
			{
				id: "q5a",
				text: "Making a difference in people's health",
				textFr: "Faire une différence dans la santé des gens",
				careerWeights: { healthcare: 3, industrial: 0, hse: 1, technology: 0 },
			},
			{
				id: "q5b",
				text: "Mastering technical skills",
				textFr: "Maîtriser des compétences techniques",
				careerWeights: { healthcare: 0, industrial: 3, hse: 1, technology: 2 },
			},
			{
				id: "q5c",
				text: "Creating safer workplaces",
				textFr: "Creer des lieux de travail plus sûrs",
				careerWeights: { healthcare: 1, industrial: 1, hse: 3, technology: 0 },
			},
			{
				id: "q5d",
				text: "Building the future with technology",
				textFr: "Construire l'avenir avec la technologie",
				careerWeights: { healthcare: 0, industrial: 1, hse: 0, technology: 3 },
			},
		],
	},
	{
		id: "q6",
		question: "What physical activity level do you prefer at work?",
		questionFr: "Quel niveau d'activité physique préférez-vous au travail?",
		category: "environment",
		options: [
			{
				id: "q6a",
				text: "Active, moving and standing frequently",
				textFr: "Actif, bouger et être debout fréquemment",
				careerWeights: { healthcare: 3, industrial: 2, hse: 2, technology: 0 },
			},
			{
				id: "q6b",
				text: "Mix of physical and desk work",
				textFr: "Mélange de travail physique et de bureau",
				careerWeights: { healthcare: 2, industrial: 3, hse: 3, technology: 1 },
			},
			{
				id: "q6c",
				text: "Primarily desk-based with some field visits",
				textFr: "Principalement au bureau avec quelques visites terrain",
				careerWeights: { healthcare: 1, industrial: 1, hse: 2, technology: 2 },
			},
			{
				id: "q6d",
				text: "Mostly sedentary, working at a computer",
				textFr: "Principalement sédentaire, travaillant sur ordinateur",
				careerWeights: { healthcare: 0, industrial: 0, hse: 1, technology: 3 },
			},
		],
	},
	{
		id: "q7",
		question: "How do you prefer to learn new things?",
		questionFr: "Comment préférez-vous apprendre de nouvelles choses?",
		category: "work_style",
		options: [
			{
				id: "q7a",
				text: "Through hands-on practice with patients",
				textFr: "Par la pratique avec des patients",
				careerWeights: { healthcare: 3, industrial: 0, hse: 1, technology: 0 },
			},
			{
				id: "q7b",
				text: "By working with equipment and tools",
				textFr: "En travaillant avec des équipements et outils",
				careerWeights: { healthcare: 0, industrial: 3, hse: 1, technology: 1 },
			},
			{
				id: "q7c",
				text: "Through regulations and case studies",
				textFr: "A travers les règlements et études de cas",
				careerWeights: { healthcare: 1, industrial: 1, hse: 3, technology: 1 },
			},
			{
				id: "q7d",
				text: "By experimenting with code and software",
				textFr: "En expérimentant avec du code et des logiciels",
				careerWeights: { healthcare: 0, industrial: 0, hse: 0, technology: 3 },
			},
		],
	},
	{
		id: "q8",
		question: "What type of team do you prefer?",
		questionFr: "Quel type d'équipe préférez-vous?",
		category: "work_style",
		options: [
			{
				id: "q8a",
				text: "Medical team (doctors, nurses)",
				textFr: "Équipe médicale (médecins, infirmiers)",
				careerWeights: { healthcare: 3, industrial: 0, hse: 1, technology: 0 },
			},
			{
				id: "q8b",
				text: "Technical team (engineers, technicians)",
				textFr: "Équipe technique (ingénieurs, techniciens)",
				careerWeights: { healthcare: 0, industrial: 3, hse: 2, technology: 2 },
			},
			{
				id: "q8c",
				text: "Cross-functional team focused on safety",
				textFr: "Équipe transversale axée sur la sécurité",
				careerWeights: { healthcare: 1, industrial: 1, hse: 3, technology: 1 },
			},
			{
				id: "q8d",
				text: "Development team (developers, designers)",
				textFr: "Équipe de développement (développeurs, designers)",
				careerWeights: { healthcare: 0, industrial: 0, hse: 0, technology: 3 },
			},
		],
	},
	{
		id: "q9",
		question: "What motivates you most at work?",
		questionFr: "Qu'est-ce qui vous motive le plus au travail?",
		category: "goals",
		options: [
			{
				id: "q9a",
				text: "Seeing patients recover",
				textFr: "Voir les patients guérir",
				careerWeights: { healthcare: 3, industrial: 0, hse: 0, technology: 0 },
			},
			{
				id: "q9b",
				text: "Solving complex technical problems",
				textFr: "Résoudre des problèmes techniques complexes",
				careerWeights: { healthcare: 0, industrial: 3, hse: 1, technology: 2 },
			},
			{
				id: "q9c",
				text: "Preventing accidents and incidents",
				textFr: "Prévenir les accidents et incidents",
				careerWeights: { healthcare: 1, industrial: 1, hse: 3, technology: 0 },
			},
			{
				id: "q9d",
				text: "Creating something new and innovative",
				textFr: "Creer quelque chose de nouveau et innovant",
				careerWeights: { healthcare: 0, industrial: 1, hse: 0, technology: 3 },
			},
		],
	},
	{
		id: "q10",
		question: "How do you view continuous learning?",
		questionFr: "Comment voyez-vous la formation continue?",
		category: "goals",
		options: [
			{
				id: "q10a",
				text: "Essential for staying updated on medical advances",
				textFr: "Essentielle pour rester à jour sur les avancées médicales",
				careerWeights: { healthcare: 3, industrial: 1, hse: 1, technology: 1 },
			},
			{
				id: "q10b",
				text: "Important for mastering new equipment",
				textFr: "Importante pour maîtriser les nouveaux équipements",
				careerWeights: { healthcare: 0, industrial: 3, hse: 1, technology: 2 },
			},
			{
				id: "q10c",
				text: "Critical for understanding evolving regulations",
				textFr: "Critique pour comprendre les règlements en évolution",
				careerWeights: { healthcare: 1, industrial: 1, hse: 3, technology: 1 },
			},
			{
				id: "q10d",
				text: "Exciting opportunity to learn new languages and frameworks",
				textFr: "Opportunité excitante d'apprendre de nouveaux langages et frameworks",
				careerWeights: { healthcare: 0, industrial: 0, hse: 0, technology: 3 },
			},
		],
	},
];

// Market insights data by field
export const marketInsightsData: Record<string, z.infer<typeof marketInsightSchema>> = {
	healthcare: {
		field: "healthcare",
		employmentRate: 92,
		averageSalary: 8500,
		salaryRange: { min: 3500, max: 15000, currency: "MAD" },
		demandLevel: "very_high",
		growthProjection: { percentage: 15, period: "2024-2025" },
		topSkills: [
			"Patient care",
			"Clinical procedures",
			"Emergency response",
			"Medical documentation",
			"Team collaboration",
		],
		topSkillsFr: [
			"Soins aux patients",
			"Procédures cliniques",
			"Réponse aux urgences",
			"Documentation médicale",
			"Collaboration en équipe",
		],
		jobOpenings: 5200,
		trends: [
			{
				trend: "Digital health adoption increasing",
				trendFr: "Adoption croissante de la santé numérique",
				impact: "positive",
			},
			{
				trend: "Growing demand for specialized nurses",
				trendFr: "Demande croissante pour les infirmiers spécialisés",
				impact: "positive",
			},
			{
				trend: "Rural areas facing shortages",
				trendFr: "Pénuries dans les zones rurales - opportunités",
				impact: "positive",
			},
		],
	},
	industrial: {
		field: "industrial",
		employmentRate: 88,
		averageSalary: 7500,
		salaryRange: { min: 4000, max: 12000, currency: "MAD" },
		demandLevel: "high",
		growthProjection: { percentage: 12, period: "2024-2025" },
		topSkills: [
			"Equipment maintenance",
			"Troubleshooting",
			"Safety protocols",
			"Technical documentation",
			"PLC programming",
		],
		topSkillsFr: [
			"Maintenance des équipements",
			"Dépannage",
			"Protocoles de sécurité",
			"Documentation technique",
			"Programmation automate",
		],
		jobOpenings: 3800,
		trends: [
			{
				trend: "Industry 4.0 transformation",
				trendFr: "Transformation Industrie 4.0",
				impact: "positive",
			},
			{
				trend: "Automation increasing demand for skilled technicians",
				trendFr: "L'automatisation augmente la demande de techniciens qualifiés",
				impact: "positive",
			},
			{
				trend: "Green manufacturing initiatives",
				trendFr: "Initiatives de fabrication verte",
				impact: "positive",
			},
		],
	},
	hse: {
		field: "hse",
		employmentRate: 93,
		averageSalary: 10000,
		salaryRange: { min: 6000, max: 18000, currency: "MAD" },
		demandLevel: "very_high",
		growthProjection: { percentage: 18, period: "2024-2025" },
		topSkills: [
			"Risk assessment",
			"Safety auditing",
			"Regulatory compliance",
			"Training delivery",
			"Incident investigation",
		],
		topSkillsFr: [
			"Évaluation des risques",
			"Audit de sécurité",
			"Conformité réglementaire",
			"Animation de formations",
			"Enquete sur les incidents",
		],
		jobOpenings: 2100,
		trends: [
			{
				trend: "Stricter environmental regulations",
				trendFr: "Réglementation environnementale plus stricte",
				impact: "positive",
			},
			{
				trend: "ISO 45001 adoption growing",
				trendFr: "Adoption croissante de l'ISO 45001",
				impact: "positive",
			},
			{
				trend: "Focus on mental health at work",
				trendFr: "Accent sur la santé mentale au travail",
				impact: "positive",
			},
		],
	},
	technology: {
		field: "technology",
		employmentRate: 85,
		averageSalary: 11000,
		salaryRange: { min: 5000, max: 25000, currency: "MAD" },
		demandLevel: "very_high",
		growthProjection: { percentage: 25, period: "2024-2025" },
		topSkills: ["Programming", "Cloud computing", "Data analysis", "Cybersecurity", "Agile methodologies"],
		topSkillsFr: ["Programmation", "Cloud computing", "Analyse de données", "Cybersécurité", "Méthodologies agiles"],
		jobOpenings: 4500,
		trends: [
			{
				trend: "AI and machine learning boom",
				trendFr: "Boom de l'IA et du machine learning",
				impact: "positive",
			},
			{
				trend: "Remote work opportunities expanding",
				trendFr: "Opportunités de télétravail en expansion",
				impact: "positive",
			},
			{
				trend: "Cybersecurity demand surging",
				trendFr: "Demande en cybersécurité en hausse",
				impact: "positive",
			},
		],
	},
	management: {
		field: "management",
		employmentRate: 86,
		averageSalary: 8000,
		salaryRange: { min: 4500, max: 16000, currency: "MAD" },
		demandLevel: "high",
		growthProjection: { percentage: 13, period: "2024-2025" },
		topSkills: [
			"Digital marketing",
			"Accounting and taxation",
			"Project management",
			"Supply chain",
			"Human resources",
		],
		topSkillsFr: [
			"Marketing digital",
			"Comptabilité et fiscalité",
			"Gestion de projet",
			"Supply chain",
			"Ressources humaines",
		],
		jobOpenings: 3600,
		trends: [
			{
				trend: "E-commerce growth driving digital skills demand",
				trendFr: "La croissance du e-commerce stimule la demande de compétences digitales",
				impact: "positive",
			},
			{
				trend: "Logistics hub expansion (Tanger Med)",
				trendFr: "Expansion des hubs logistiques (Tanger Med)",
				impact: "positive",
			},
			{
				trend: "Industrial sector needs structured management profiles",
				trendFr: "L'industrie a besoin de profils de gestion structures",
				impact: "positive",
			},
		],
	},
};

// Top employers in Morocco by field
export const topEmployersData: z.infer<typeof employerSchema>[] = [
	// Healthcare employers
	{
		id: "chu-rabat",
		name: "CHU Ibn Sina - Rabat",
		sector: "Public Healthcare",
		sectorFr: "Santé Publique",
		location: "Rabat",
		locationFr: "Rabat",
		employeeCount: "5000+",
		description: "Morocco's largest university hospital center, providing tertiary care and medical education.",
		descriptionFr:
			"Le plus grand centre hospitalier universitaire du Maroc, offrant des soins tertiaires et une formation médicale.",
		hiringFields: ["healthcare"],
		benefits: ["Job security", "Training opportunities", "Career progression", "Social benefits"],
		benefitsFr: ["Sécurité de l'emploi", "Opportunités de formation", "Evolution de carrière", "Avantages sociaux"],
		website: "https://www.chuisrabat.ma",
		averageSalary: { min: 5500, max: 12000, currency: "MAD" },
	},
	{
		id: "chu-casablanca",
		name: "CHU Ibn Rochd - Casablanca",
		sector: "Public Healthcare",
		sectorFr: "Santé Publique",
		location: "Casablanca",
		locationFr: "Casablanca",
		employeeCount: "4000+",
		description: "Major university hospital in Casablanca serving the largest metropolitan area in Morocco.",
		descriptionFr: "Hôpital universitaire majeur à Casablanca desservant la plus grande zone métropolitaine du Maroc.",
		hiringFields: ["healthcare"],
		benefits: ["Competitive salary", "Professional development", "Modern facilities", "Research opportunities"],
		benefitsFr: [
			"Salaire compétitif",
			"Développement professionnel",
			"Installations modernes",
			"Opportunités de recherche",
		],
		website: "https://www.chuibnrochd.ma",
		averageSalary: { min: 5500, max: 13000, currency: "MAD" },
	},
	{
		id: "clinique-cheikh-zaid",
		name: "Hôpital Cheikh Zaid",
		sector: "Private Healthcare",
		sectorFr: "Santé Privée",
		location: "Rabat",
		locationFr: "Rabat",
		employeeCount: "1500+",
		description: "Premier private hospital offering specialized medical services and modern healthcare.",
		descriptionFr: "Hôpital privé de premier plan offrant des services médicaux spécialisés et des soins modernes.",
		hiringFields: ["healthcare"],
		benefits: ["Higher salaries", "Modern equipment", "International standards", "Continuous training"],
		benefitsFr: ["Salaires plus élevés", "Equipements modernes", "Normes internationales", "Formation continue"],
		website: "https://www.hcz.ma",
		averageSalary: { min: 7000, max: 15000, currency: "MAD" },
	},
	// Industrial employers
	{
		id: "ocp-group",
		name: "OCP Group",
		sector: "Mining & Chemicals",
		sectorFr: "Mines & Chimie",
		location: "Multiple locations",
		locationFr: "Plusieurs sites",
		employeeCount: "20000+",
		description:
			"World leader in phosphate and phosphate-based products, Morocco's largest employer in industrial sector.",
		descriptionFr:
			"Leader mondial du phosphate et des produits à base de phosphate, le plus grand employeur industriel du Maroc.",
		hiringFields: ["industrial", "hse"],
		benefits: [
			"Excellent salaries",
			"Housing assistance",
			"Medical coverage",
			"Training programs",
			"Career advancement",
		],
		benefitsFr: [
			"Excellents salaires",
			"Aide au logement",
			"Couverture médicale",
			"Programmes de formation",
			"Avancement de carrière",
		],
		website: "https://www.ocpgroup.ma",
		averageSalary: { min: 8000, max: 18000, currency: "MAD" },
	},
	{
		id: "renault-maroc",
		name: "Renault Maroc (SOMACA)",
		sector: "Automotive",
		sectorFr: "Automobile",
		location: "Casablanca, Tangier",
		locationFr: "Casablanca, Tanger",
		employeeCount: "10000+",
		description: "Major automotive manufacturer with production facilities in Morocco.",
		descriptionFr: "Constructeur automobile majeur avec des installations de production au Maroc.",
		hiringFields: ["industrial", "hse"],
		benefits: ["Competitive pay", "International exposure", "Technical training", "Transport provided"],
		benefitsFr: ["Salaire compétitif", "Exposition internationale", "Formation technique", "Transport assure"],
		website: "https://www.renault.ma",
		averageSalary: { min: 6000, max: 14000, currency: "MAD" },
	},
	{
		id: "managem",
		name: "Managem Group",
		sector: "Mining",
		sectorFr: "Mines",
		location: "Multiple locations",
		locationFr: "Plusieurs sites",
		employeeCount: "8000+",
		description: "Leading mining company in Morocco specializing in precious metals and base metals.",
		descriptionFr: "Société minière leader au Maroc spécialisée dans les métaux précieux et les métaux de base.",
		hiringFields: ["industrial", "hse"],
		benefits: ["High salaries", "Site bonuses", "Health coverage", "Career growth"],
		benefitsFr: ["Hauts salaires", "Primes de site", "Couverture santé", "Evolution de carrière"],
		website: "https://www.managemgroup.com",
		averageSalary: { min: 7000, max: 16000, currency: "MAD" },
	},
	// HSE employers
	{
		id: "bureau-veritas",
		name: "Bureau Veritas Maroc",
		sector: "Consulting & Certification",
		sectorFr: "Conseil & Certification",
		location: "Casablanca",
		locationFr: "Casablanca",
		employeeCount: "500+",
		description: "Global leader in testing, inspection and certification services.",
		descriptionFr: "Leader mondial des services de test, d'inspection et de certification.",
		hiringFields: ["hse"],
		benefits: ["International company", "Training abroad", "Diverse projects", "Career mobility"],
		benefitsFr: ["Entreprise internationale", "Formations à l'étranger", "Projets diversifiés", "Mobilité de carrière"],
		website: "https://www.bureauveritas.ma",
		averageSalary: { min: 8000, max: 15000, currency: "MAD" },
	},
	{
		id: "lafargeholcim",
		name: "LafargeHolcim Maroc",
		sector: "Construction Materials",
		sectorFr: "Matériaux de Construction",
		location: "Multiple locations",
		locationFr: "Plusieurs sites",
		employeeCount: "3000+",
		description: "Leading supplier of cement and construction materials in Morocco.",
		descriptionFr: "Principal fournisseur de ciment et de matériaux de construction au Maroc.",
		hiringFields: ["industrial", "hse"],
		benefits: ["Stable employment", "Good benefits", "Safety culture", "Training programs"],
		benefitsFr: ["Emploi stable", "Bons avantages", "Culture sécurité", "Programmes de formation"],
		website: "https://www.lafargeholcim.ma",
		averageSalary: { min: 6500, max: 14000, currency: "MAD" },
	},
	// Technology employers
	{
		id: "capgemini",
		name: "Capgemini Maroc",
		sector: "IT Services",
		sectorFr: "Services IT",
		location: "Casablanca, Rabat",
		locationFr: "Casablanca, Rabat",
		employeeCount: "3000+",
		description: "Global IT services and consulting company with major operations in Morocco.",
		descriptionFr: "Société mondiale de services et conseil IT avec des opérations majeures au Maroc.",
		hiringFields: ["technology"],
		benefits: ["Competitive salary", "International projects", "Training programs", "Remote work options"],
		benefitsFr: ["Salaire compétitif", "Projets internationaux", "Programmes de formation", "Options de télétravail"],
		website: "https://www.capgemini.com/ma-fr/",
		averageSalary: { min: 8000, max: 20000, currency: "MAD" },
	},
	{
		id: "atos",
		name: "Atos Maroc",
		sector: "IT Services",
		sectorFr: "Services IT",
		location: "Casablanca",
		locationFr: "Casablanca",
		employeeCount: "2000+",
		description: "International IT services company providing digital transformation solutions.",
		descriptionFr: "Entreprise internationale de services IT offrant des solutions de transformation numérique.",
		hiringFields: ["technology"],
		benefits: ["Good salary", "Career growth", "Technical training", "Work-life balance"],
		benefitsFr: ["Bon salaire", "Evolution de carrière", "Formation technique", "Equilibre travail-vie"],
		website: "https://atos.net/fr-ma/maroc",
		averageSalary: { min: 7000, max: 18000, currency: "MAD" },
	},
	// Management employers
	{
		id: "attijariwafa-bank",
		name: "Attijariwafa Bank",
		sector: "Banking & Finance",
		sectorFr: "Banque & Finance",
		location: "Casablanca",
		locationFr: "Casablanca",
		employeeCount: "20000+",
		description: "Leading banking group in Morocco and Africa, recruiting finance, accounting and commercial profiles.",
		descriptionFr:
			"Premier groupe bancaire au Maroc et en Afrique, recrutant des profils finance, comptabilité et commerciaux.",
		hiringFields: ["management"],
		benefits: ["Job security", "Career progression", "Training programs", "Social benefits"],
		benefitsFr: ["Sécurité de l'emploi", "Evolution de carrière", "Programmes de formation", "Avantages sociaux"],
		website: "https://www.attijariwafabank.com",
		averageSalary: { min: 6000, max: 16000, currency: "MAD" },
	},
	{
		id: "marjane-holding",
		name: "Marjane Holding",
		sector: "Retail & Distribution",
		sectorFr: "Distribution & Commerce",
		location: "Multiple locations",
		locationFr: "Plusieurs sites",
		employeeCount: "12000+",
		description:
			"Largest retail group in Morocco, recruiting commercial, marketing, supply chain and logistics profiles.",
		descriptionFr:
			"Le plus grand groupe de distribution au Maroc, recrutant des profils commerciaux, marketing, supply chain et logistique.",
		hiringFields: ["management"],
		benefits: ["Career opportunities", "Internal mobility", "Training", "Performance bonuses"],
		benefitsFr: ["Opportunités de carrière", "Mobilité interne", "Formation", "Primes de performance"],
		website: "https://www.marjane.ma",
		averageSalary: { min: 4500, max: 13000, currency: "MAD" },
	},
	{
		id: "tanger-med",
		name: "Tanger Med",
		sector: "Logistics & Ports",
		sectorFr: "Logistique & Ports",
		location: "Tangier",
		locationFr: "Tanger",
		employeeCount: "5000+",
		description:
			"Leading port and logistics hub in Africa, recruiting supply chain, logistics and project management profiles.",
		descriptionFr:
			"Premier hub portuaire et logistique en Afrique, recrutant des profils supply chain, logistique et gestion de projet.",
		hiringFields: ["management", "industrial"],
		benefits: ["Competitive salary", "International environment", "Career growth", "Training"],
		benefitsFr: ["Salaire compétitif", "Environnement international", "Evolution de carrière", "Formation"],
		website: "https://www.tangermed.ma",
		averageSalary: { min: 5500, max: 15000, currency: "MAD" },
	},
];

// Salary statistics by program
export const salaryStatisticsData: Record<string, z.infer<typeof salaryStatisticsSchema>> = {
	"sage-femme": {
		programId: "sage-femme",
		averageSalary: 9000,
		minSalary: 6000,
		maxSalary: 15000,
		currency: "MAD",
		experienceLevels: [
			{
				level: "Entry Level",
				levelFr: "Débutant",
				yearsExperience: "0-2",
				averageSalary: 6500,
				range: { min: 6000, max: 7500 },
			},
			{
				level: "Mid Level",
				levelFr: "Intermédiaire",
				yearsExperience: "3-5",
				averageSalary: 9000,
				range: { min: 7500, max: 11000 },
			},
			{
				level: "Senior",
				levelFr: "Senior",
				yearsExperience: "5+",
				averageSalary: 13000,
				range: { min: 11000, max: 15000 },
			},
		],
		byRegion: [
			{ region: "Casablanca", regionFr: "Casablanca", averageSalary: 10000, costOfLivingIndex: 100 },
			{ region: "Rabat", regionFr: "Rabat", averageSalary: 9500, costOfLivingIndex: 95 },
			{ region: "Marrakech", regionFr: "Marrakech", averageSalary: 8000, costOfLivingIndex: 85 },
			{ region: "Tangier", regionFr: "Tanger", averageSalary: 8500, costOfLivingIndex: 88 },
		],
		trends: { yearOverYearGrowth: 5, projectedGrowth2025: 7 },
	},
	"infirmier-polyvalent": {
		programId: "infirmier-polyvalent",
		averageSalary: 8000,
		minSalary: 5500,
		maxSalary: 12000,
		currency: "MAD",
		experienceLevels: [
			{
				level: "Entry Level",
				levelFr: "Débutant",
				yearsExperience: "0-2",
				averageSalary: 5800,
				range: { min: 5500, max: 6500 },
			},
			{
				level: "Mid Level",
				levelFr: "Intermédiaire",
				yearsExperience: "3-5",
				averageSalary: 8000,
				range: { min: 6500, max: 9500 },
			},
			{
				level: "Senior",
				levelFr: "Senior",
				yearsExperience: "5+",
				averageSalary: 11000,
				range: { min: 9500, max: 12000 },
			},
		],
		byRegion: [
			{ region: "Casablanca", regionFr: "Casablanca", averageSalary: 8500, costOfLivingIndex: 100 },
			{ region: "Rabat", regionFr: "Rabat", averageSalary: 8200, costOfLivingIndex: 95 },
			{ region: "Marrakech", regionFr: "Marrakech", averageSalary: 7000, costOfLivingIndex: 85 },
			{ region: "Fes", regionFr: "Fes", averageSalary: 6800, costOfLivingIndex: 80 },
		],
		trends: { yearOverYearGrowth: 4, projectedGrowth2025: 6 },
	},
	"hse-specialist": {
		programId: "hse-specialist",
		averageSalary: 10000,
		minSalary: 6000,
		maxSalary: 15000,
		currency: "MAD",
		experienceLevels: [
			{
				level: "Entry Level",
				levelFr: "Débutant",
				yearsExperience: "0-2",
				averageSalary: 7000,
				range: { min: 6000, max: 8000 },
			},
			{
				level: "Mid Level",
				levelFr: "Intermédiaire",
				yearsExperience: "3-5",
				averageSalary: 10500,
				range: { min: 8500, max: 12500 },
			},
			{
				level: "Senior",
				levelFr: "Senior",
				yearsExperience: "5+",
				averageSalary: 14000,
				range: { min: 12000, max: 18000 },
			},
		],
		byRegion: [
			{ region: "Casablanca", regionFr: "Casablanca", averageSalary: 11000, costOfLivingIndex: 100 },
			{ region: "Khouribga", regionFr: "Khouribga", averageSalary: 12000, costOfLivingIndex: 75 },
			{ region: "Tangier", regionFr: "Tanger", averageSalary: 10000, costOfLivingIndex: 88 },
			{ region: "Jorf Lasfar", regionFr: "Jorf Lasfar", averageSalary: 11500, costOfLivingIndex: 70 },
		],
		trends: { yearOverYearGrowth: 8, projectedGrowth2025: 12 },
	},
	electromecanique: {
		programId: "electromecanique",
		averageSalary: 8500,
		minSalary: 5500,
		maxSalary: 12000,
		currency: "MAD",
		experienceLevels: [
			{
				level: "Entry Level",
				levelFr: "Débutant",
				yearsExperience: "0-2",
				averageSalary: 6000,
				range: { min: 5500, max: 7000 },
			},
			{
				level: "Mid Level",
				levelFr: "Intermédiaire",
				yearsExperience: "3-5",
				averageSalary: 8500,
				range: { min: 7000, max: 10000 },
			},
			{
				level: "Senior",
				levelFr: "Senior",
				yearsExperience: "5+",
				averageSalary: 11000,
				range: { min: 10000, max: 12000 },
			},
		],
		byRegion: [
			{ region: "Casablanca", regionFr: "Casablanca", averageSalary: 9000, costOfLivingIndex: 100 },
			{ region: "Tangier", regionFr: "Tanger", averageSalary: 8500, costOfLivingIndex: 88 },
			{ region: "Kenitra", regionFr: "Kenitra", averageSalary: 8000, costOfLivingIndex: 78 },
			{ region: "Agadir", regionFr: "Agadir", averageSalary: 7500, costOfLivingIndex: 82 },
		],
		trends: { yearOverYearGrowth: 6, projectedGrowth2025: 9 },
	},
	"developpeur-web": {
		programId: "developpeur-web",
		averageSalary: 11000,
		minSalary: 6000,
		maxSalary: 18000,
		currency: "MAD",
		experienceLevels: [
			{
				level: "Entry Level",
				levelFr: "Débutant",
				yearsExperience: "0-2",
				averageSalary: 7000,
				range: { min: 6000, max: 9000 },
			},
			{
				level: "Mid Level",
				levelFr: "Intermédiaire",
				yearsExperience: "2-5",
				averageSalary: 12000,
				range: { min: 9000, max: 15000 },
			},
			{
				level: "Senior",
				levelFr: "Senior",
				yearsExperience: "5+",
				averageSalary: 17000,
				range: { min: 15000, max: 25000 },
			},
		],
		byRegion: [
			{ region: "Casablanca", regionFr: "Casablanca", averageSalary: 12000, costOfLivingIndex: 100 },
			{ region: "Rabat", regionFr: "Rabat", averageSalary: 11000, costOfLivingIndex: 95 },
			{ region: "Tangier", regionFr: "Tanger", averageSalary: 9500, costOfLivingIndex: 88 },
			{ region: "Remote", regionFr: "Télétravail", averageSalary: 14000, costOfLivingIndex: 85 },
		],
		trends: { yearOverYearGrowth: 15, projectedGrowth2025: 20 },
	},
};

// Career category descriptions for results
export const careerDescriptions: Record<
	string,
	{ description: string; descriptionFr: string; suggestedPrograms: string[] }
> = {
	healthcare: {
		description:
			"Healthcare careers focus on patient care, médical procédures, and improving people's health and well-being.",
		descriptionFr:
			"Les carrières dans la santé se concentrent sur les soins aux patients, les procédures médicales et l'amelioration de la santé et du bien-être des personnes.",
		suggestedPrograms: ["sage-femme", "infirmier-polyvalent", "aide-soignant"],
	},
	industrial: {
		description:
			"Industrial careers involve working with machines, equipment maintenance, manufacturing, and technical problem-solving.",
		descriptionFr:
			"Les carrières industrielles impliquent le travail avec des machines, la maintenance des équipements, la fabrication et la résolution de problèmes techniques.",
		suggestedPrograms: ["electromecanique", "mecanique-engins", "conducteur-engins"],
	},
	hse: {
		description:
			"HSE careers focus on ensuring workplace safety, environmental compliance, and protecting workers from hazards.",
		descriptionFr:
			"Les carrières HSE se concentrent sur la sécurité au travail, la conformité environnementale et la protection des travailleurs contre les dangers.",
		suggestedPrograms: ["hse-specialist"],
	},
	technology: {
		description:
			"Technology careers involve software development, IT solutions, digital innovation, and working with cutting-edge technologies.",
		descriptionFr:
			"Les carrières technologiques impliquent le développement de logiciels, les solutions IT, l'innovation numérique et le travail avec des technologies de pointe.",
		suggestedPrograms: ["developpeur-web", "data-analyst"],
	},
	management: {
		description:
			"Management careers focus on business administration, commerce, finance, human resources, and supply chain coordination.",
		descriptionFr:
			"Les carrières en gestion se concentrent sur l'administration des entreprises, le commerce, la finance, les ressources humaines et la coordination de la supply chain.",
		suggestedPrograms: ["commerce-marketing-digital", "finance-comptabilite", "supply-chain-logistique"],
	},
};
