// Static interview tips data
export function getInterviewTips(
	field?: "healthcare" | "industrial" | "hse" | "technology" | "management" | "general",
	category?: "preparation" | "during" | "after" | "common_questions" | "body_language" | "field_specific",
	language: "fr" | "en" = "fr",
) {
	const tips = [
		// Preparation tips
		{
			id: "prep-1",
			title: "Research the Company",
			titleFr: "Recherchez l'entreprise",
			content: "Learn about the company's mission, values, and recent news before the interview.",
			contentFr: "Renseignez-vous sur la mission, les valeurs et l'actualite de l'entreprise avant l'entretien.",
			category: "preparation" as const,
			tags: ["preparation", "research"],
		},
		{
			id: "prep-2",
			title: "Prepare Your Documents",
			titleFr: "Preparez vos documents",
			content: "Bring multiple copies of your CV, diplomas, and any certificates.",
			contentFr: "Apportez plusieurs copies de votre CV, diplomes, attestations de stage et certificats.",
			category: "preparation" as const,
			tags: ["preparation", "documents"],
		},
		{
			id: "prep-3",
			title: "Practice Common Questions",
			titleFr: "Entrainez-vous aux questions courantes",
			content: "Practice answering common interview questions using the STAR method.",
			contentFr:
				"Entrainez-vous a repondre aux questions courantes en utilisant la methode STAR (Situation, Tache, Action, Resultat).",
			category: "preparation" as const,
			tags: ["preparation", "practice"],
		},
		{
			id: "prep-4",
			title: "Prepare Your Internship Stories",
			titleFr: "Preparez vos recits de stage",
			content: "Think about specific situations from your internships that demonstrate your skills.",
			contentFr:
				"Reflechissez a des situations specifiques de vos stages qui demontrent vos competences et savoir-faire.",
			category: "preparation" as const,
			tags: ["preparation", "internship"],
		},
		{
			id: "prep-5",
			title: "Review Your Technical Skills",
			titleFr: "Revisez vos competences techniques",
			content: "Review the key technical concepts relevant to the position you're applying for.",
			contentFr: "Revisez les concepts techniques cles en lien avec le poste que vous visez.",
			category: "preparation" as const,
			tags: ["preparation", "technical"],
		},
		{
			id: "prep-6",
			title: "Dress Professionally",
			titleFr: "Habillez-vous professionnellement",
			content: "Choose clean, professional attire appropriate for the work environment.",
			contentFr: "Choisissez une tenue propre et professionnelle adaptee au milieu de travail.",
			category: "preparation" as const,
			tags: ["preparation", "appearance"],
		},
		{
			id: "prep-7",
			title: "Analyze the Job Offer",
			titleFr: "Analysez l'offre ligne par ligne",
			content: "Identify required skills, main tasks, and keywords to reuse during the interview.",
			contentFr:
				"Reperez les competences demandees, les missions principales et les mots cles a reprendre en entretien.",
			category: "preparation" as const,
			tags: ["preparation", "job_offer"],
		},
		{
			id: "prep-8",
			title: "Prepare Your 60-Second Pitch",
			titleFr: "Preparez votre pitch de 60 secondes",
			content: "Summarize your training, best experience, main strength, and professional goal.",
			contentFr:
				"Resumez votre formation, votre meilleure experience, votre force principale et votre objectif professionnel.",
			category: "preparation" as const,
			tags: ["preparation", "pitch"],
		},
		{
			id: "prep-9",
			title: "List Your Proof Points",
			titleFr: "Listez vos preuves",
			content: "Match each important skill with proof from an internship, project, module, result, or field situation.",
			contentFr:
				"Associez chaque competence importante a une preuve: stage, projet, module, resultat ou situation terrain.",
			category: "preparation" as const,
			tags: ["preparation", "proof"],
		},
		{
			id: "prep-10",
			title: "Prepare Questions for the Recruiter",
			titleFr: "Preparez vos questions au recruteur",
			content: "Prepare three questions about tasks, team, onboarding, schedule, or expectations.",
			contentFr:
				"Ayez trois questions sur les missions, l'equipe, l'integration, les horaires ou les attentes du poste.",
			category: "preparation" as const,
			tags: ["preparation", "questions"],
		},
		{
			id: "prep-11",
			title: "Run a Mock Interview",
			titleFr: "Faites une simulation",
			content: "Practice out loud with a friend or AI to improve rhythm, clarity, and examples.",
			contentFr: "Repetez a voix haute avec un ami ou l'IA pour travailler le rythme, la clarte et les exemples.",
			category: "preparation" as const,
			tags: ["preparation", "practice"],
		},
		{
			id: "prep-12",
			title: "Plan Your Route",
			titleFr: "Planifiez le trajet",
			content: "Check the address, travel time, parking, contact, and a safety margin.",
			contentFr: "Verifiez l'adresse, le temps de transport, le parking, le contact et une marge de securite.",
			category: "preparation" as const,
			tags: ["preparation", "logistics"],
		},
		{
			id: "prep-13",
			title: "Clean Up Your Online Presence",
			titleFr: "Nettoyez votre presence en ligne",
			content: "Check public profiles and your professional photo in case the recruiter searches your name.",
			contentFr: "Verifiez vos profils publics et votre photo professionnelle si le recruteur cherche votre nom.",
			category: "preparation" as const,
			tags: ["preparation", "online_profile"],
		},
		{
			id: "prep-14",
			title: "Clarify Your Expectations",
			titleFr: "Preparez vos attentes",
			content: "Clarify your availability, expected salary, transport constraints, and important conditions.",
			contentFr: "Clarifiez vos disponibilites, salaire attendu, contraintes de transport et conditions importantes.",
			category: "preparation" as const,
			tags: ["preparation", "expectations"],
		},
		{
			id: "prep-15",
			title: "Prepare Difficult Answers",
			titleFr: "Anticipez les questions difficiles",
			content: "Prepare calm answers about gaps, failures, delays, or limited experience.",
			contentFr: "Preparez des reponses calmes sur les lacunes, les echecs, les retards ou le manque d'experience.",
			category: "preparation" as const,
			tags: ["preparation", "difficult_questions"],
		},
		{
			id: "prep-16",
			title: "Adapt Your Resume to the Role",
			titleFr: "Adaptez votre CV au poste",
			content: "Highlight the experiences, skills, and keywords that best match the offer.",
			contentFr: "Mettez en avant les experiences, competences et mots cles qui correspondent le mieux a l'offre.",
			category: "preparation" as const,
			tags: ["preparation", "resume"],
		},
		{
			id: "prep-17",
			title: "Prepare a Notes Page",
			titleFr: "Preparez un carnet de notes",
			content: "Write down the recruiter's name, important points, your questions, and information to confirm.",
			contentFr: "Notez le nom du recruteur, les points importants, vos questions et les informations a confirmer.",
			category: "preparation" as const,
			tags: ["preparation", "notes"],
		},
		{
			id: "prep-18",
			title: "Rest and Arrive Ready",
			titleFr: "Dormez et arrivez pret",
			content: "Prepare your things the night before, avoid improvising, and keep the morning routine simple.",
			contentFr: "Preparez vos affaires la veille, evitez l'improvisation et gardez une routine simple le matin.",
			category: "preparation" as const,
			tags: ["preparation", "readiness"],
		},
		// During interview tips
		{
			id: "during-1",
			title: "Arrive Early",
			titleFr: "Arrivez en avance",
			content: "Arrive 10-15 minutes early to show punctuality and professionalism.",
			contentFr: "Arrivez 10-15 minutes en avance pour montrer votre ponctualite et professionnalisme.",
			category: "during" as const,
			tags: ["during", "punctuality"],
		},
		{
			id: "during-2",
			title: "Listen Carefully",
			titleFr: "Ecoutez attentivement",
			content: "Listen to the full question before answering. Ask for clarification if needed.",
			contentFr: "Ecoutez la question en entier avant de repondre. Demandez des precisions si necessaire.",
			category: "during" as const,
			tags: ["during", "communication"],
		},
		{
			id: "during-3",
			title: "Use Concrete Examples",
			titleFr: "Utilisez des exemples concrets",
			content: "Support your answers with specific examples from your internships or studies.",
			contentFr: "Appuyez vos reponses avec des exemples precis de vos stages ou etudes a l'IMTA.",
			category: "during" as const,
			tags: ["during", "examples"],
		},
		{
			id: "during-4",
			title: "Show Enthusiasm",
			titleFr: "Montrez votre enthousiasme",
			content: "Express genuine interest in the position and the company.",
			contentFr: "Exprimez un interet sincere pour le poste et l'entreprise. Montrez votre motivation.",
			category: "during" as const,
			tags: ["during", "attitude"],
		},
		{
			id: "during-5",
			title: "Ask Questions",
			titleFr: "Posez des questions",
			content: "Prepare thoughtful questions about the role, team, or company.",
			contentFr: "Preparez des questions pertinentes sur le poste, l'equipe ou l'entreprise.",
			category: "during" as const,
			tags: ["during", "questions"],
		},
		{
			id: "during-6",
			title: "Stay Calm Under Pressure",
			titleFr: "Restez calme sous pression",
			content: "Take a breath before answering difficult questions. It's okay to think.",
			contentFr: "Respirez avant de repondre aux questions difficiles. Il est normal de prendre le temps de reflechir.",
			category: "during" as const,
			tags: ["during", "stress"],
		},
		// Body language tips
		{
			id: "body-1",
			title: "Maintain Eye Contact",
			titleFr: "Maintenez le contact visuel",
			content: "Look at the interviewer when speaking to show confidence and engagement.",
			contentFr: "Regardez le recruteur quand vous parlez pour montrer confiance et engagement.",
			category: "body_language" as const,
			tags: ["body_language", "confidence"],
		},
		{
			id: "body-2",
			title: "Sit Up Straight",
			titleFr: "Tenez-vous droit",
			content: "Good posture shows professionalism and attentiveness.",
			contentFr: "Une bonne posture montre le professionnalisme et l'attention.",
			category: "body_language" as const,
			tags: ["body_language", "posture"],
		},
		{
			id: "body-3",
			title: "Smile Naturally",
			titleFr: "Souriez naturellement",
			content: "A genuine smile helps build rapport and shows you're approachable.",
			contentFr: "Un sourire sincere aide a creer un lien et montre que vous etes accessible.",
			category: "body_language" as const,
			tags: ["body_language", "rapport"],
		},
		{
			id: "body-4",
			title: "Firm Handshake",
			titleFr: "Controlez vos gestes",
			content: "A confident handshake makes a good first impression.",
			contentFr: "Gardez les mains calmes et evitez de jouer avec un stylo, un telephone ou vos documents.",
			category: "body_language" as const,
			tags: ["body_language", "greeting"],
		},
		{
			id: "body-5",
			title: "Speak Clearly",
			titleFr: "Parlez clairement",
			content: "Use a calm rhythm, short sentences, and a voice that is easy to hear.",
			contentFr: "Utilisez un rythme calme, des phrases courtes et une voix suffisamment audible.",
			category: "body_language" as const,
			tags: ["body_language", "voice"],
		},
		{
			id: "body-6",
			title: "Respect Personal Space",
			titleFr: "Respectez l'espace du recruteur",
			content: "Keep a professional distance and wait to be invited before sitting down.",
			contentFr: "Adoptez une distance professionnelle et attendez l'invitation avant de vous asseoir.",
			category: "body_language" as const,
			tags: ["body_language", "presence"],
		},
		// After interview tips
		{
			id: "after-1",
			title: "Send a Thank You",
			titleFr: "Envoyez un remerciement",
			content: "Send a brief thank-you email within 24 hours of the interview.",
			contentFr: "Envoyez un bref email de remerciement dans les 24 heures suivant l'entretien.",
			category: "after" as const,
			tags: ["after", "follow-up"],
		},
		{
			id: "after-2",
			title: "Reflect on the Interview",
			titleFr: "Analysez l'entretien",
			content: "Note what went well and what you could improve for next time.",
			contentFr: "Notez ce qui s'est bien passe et ce que vous pourriez ameliorer pour la prochaine fois.",
			category: "after" as const,
			tags: ["after", "reflection"],
		},
		{
			id: "after-3",
			title: "Be Patient",
			titleFr: "Soyez patient",
			content: "Wait for the response within the timeframe mentioned. Follow up politely if needed.",
			contentFr: "Attendez la reponse dans le delai mentionne. Relancez poliment si necessaire.",
			category: "after" as const,
			tags: ["after", "patience"],
		},
		{
			id: "after-4",
			title: "Keep Documents Ready",
			titleFr: "Gardez les documents prets",
			content: "Keep requested documents ready in case the recruiter asks for them after the interview.",
			contentFr: "Preparez les pieces demandees rapidement si le recruteur revient vers vous.",
			category: "after" as const,
			tags: ["after", "documents"],
		},
		{
			id: "after-5",
			title: "Evaluate the Offer",
			titleFr: "Comparez l'offre avec vos objectifs",
			content: "Review duties, schedule, conditions, learning opportunities, and growth before accepting.",
			contentFr: "Verifiez les missions, horaires, conditions, apprentissages et possibilites d'evolution.",
			category: "after" as const,
			tags: ["after", "offer"],
		},
		{
			id: "after-6",
			title: "Keep Applying",
			titleFr: "Continuez a postuler",
			content: "Do not stop your search until you have received a clear confirmation.",
			contentFr: "Ne bloquez pas vos recherches tant que vous n'avez pas recu une confirmation claire.",
			category: "after" as const,
			tags: ["after", "job_search"],
		},
		// Common questions tips
		{
			id: "common-1",
			title: "Tell Me About Yourself",
			titleFr: "Parlez-moi de vous",
			content: "Prepare a two-minute introduction: training, internship, key skill, and goal.",
			contentFr: "Preparez une presentation de deux minutes: formation, stage, competence forte et objectif.",
			category: "common_questions" as const,
			tags: ["common_questions", "introduction"],
		},
		{
			id: "common-2",
			title: "Why This Role?",
			titleFr: "Pourquoi ce poste ?",
			content: "Connect your skills, training, and motivation to the company's needs.",
			contentFr: "Reliez vos competences, votre formation et votre motivation aux besoins de l'entreprise.",
			category: "common_questions" as const,
			tags: ["common_questions", "motivation"],
		},
		{
			id: "common-3",
			title: "What Are Your Strengths?",
			titleFr: "Quels sont vos points forts ?",
			content: "Choose two strengths useful for the role and prove them with examples.",
			contentFr: "Choisissez deux forces utiles pour le poste et prouvez-les avec des exemples.",
			category: "common_questions" as const,
			tags: ["common_questions", "strengths"],
		},
		{
			id: "common-4",
			title: "What Would You Improve?",
			titleFr: "Quel point voulez-vous ameliorer ?",
			content: "Name a real improvement area and show the actions you are taking.",
			contentFr: "Citez une vraie piste de progres et montrez les actions que vous faites pour avancer.",
			category: "common_questions" as const,
			tags: ["common_questions", "growth"],
		},
		{
			id: "common-5",
			title: "Why Should We Hire You?",
			titleFr: "Pourquoi devrions-nous vous choisir ?",
			content: "Summarize your value: training, practical experience, reliability, motivation, and adaptability.",
			contentFr: "Resumez votre valeur: formation, experience pratique, serieux, motivation et adaptation.",
			category: "common_questions" as const,
			tags: ["common_questions", "value"],
		},
		{
			id: "common-6",
			title: "Where Do You See Yourself?",
			titleFr: "Ou vous voyez-vous dans quelques annees ?",
			content: "Give an ambitious but realistic answer connected to the target profession.",
			contentFr: "Donnez une reponse ambitieuse mais realiste, en lien avec le metier vise.",
			category: "common_questions" as const,
			tags: ["common_questions", "career"],
		},
		// Healthcare field-specific tips
		{
			id: "healthcare-1",
			title: "Emphasize Patient Care",
			titleFr: "Mettez l'accent sur les soins aux patients",
			content: "Show your commitment to patient well-being and safety in your answers.",
			contentFr: "Montrez votre engagement pour le bien-etre et la securite des patients.",
			category: "field_specific" as const,
			field: "healthcare" as const,
			tags: ["healthcare", "patient_care"],
		},
		{
			id: "healthcare-2",
			title: "Discuss Empathy and Communication",
			titleFr: "Parlez d'empathie et de communication",
			content: "Healthcare requires strong interpersonal skills - give examples of your empathy.",
			contentFr:
				"Le domaine de la sante exige de fortes competences relationnelles - donnez des exemples de votre empathie.",
			category: "field_specific" as const,
			field: "healthcare" as const,
			tags: ["healthcare", "empathy"],
		},
		{
			id: "healthcare-3",
			title: "Know Hygiene Protocols",
			titleFr: "Connaissez les protocoles d'hygiene",
			content: "Be ready to discuss infection control and hygiene procedures.",
			contentFr: "Soyez pret(e) a parler du controle des infections et des procedures d'hygiene.",
			category: "field_specific" as const,
			field: "healthcare" as const,
			tags: ["healthcare", "hygiene"],
		},
		{
			id: "healthcare-4",
			title: "Mention Teamwork",
			titleFr: "Mentionnez le travail d'equipe",
			content: "Healthcare is collaborative - share examples of working with doctors, nurses, and staff.",
			contentFr:
				"La sante est un travail d'equipe - partagez des exemples de collaboration avec medecins, infirmiers et autres.",
			category: "field_specific" as const,
			field: "healthcare" as const,
			tags: ["healthcare", "teamwork"],
		},
		// Industrial field-specific tips
		{
			id: "industrial-1",
			title: "Highlight Safety Awareness",
			titleFr: "Soulignez votre conscience de la securite",
			content: "Demonstrate your understanding of workplace safety and machine operation protocols.",
			contentFr:
				"Demontrez votre comprehension de la securite au travail et des protocoles d'utilisation des machines.",
			category: "field_specific" as const,
			field: "industrial" as const,
			tags: ["industrial", "safety"],
		},
		{
			id: "industrial-2",
			title: "Show Technical Knowledge",
			titleFr: "Montrez vos connaissances techniques",
			content: "Be prepared to discuss specific tools, machines, or maintenance procedures.",
			contentFr: "Soyez pret(e) a discuter des outils, machines ou procedures de maintenance specifiques.",
			category: "field_specific" as const,
			field: "industrial" as const,
			tags: ["industrial", "technical"],
		},
		{
			id: "industrial-3",
			title: "Discuss Problem-Solving",
			titleFr: "Parlez de resolution de problemes",
			content: "Share examples of diagnosing and fixing technical issues.",
			contentFr: "Partagez des exemples de diagnostic et de resolution de problemes techniques.",
			category: "field_specific" as const,
			field: "industrial" as const,
			tags: ["industrial", "problem_solving"],
		},
		{
			id: "industrial-4",
			title: "Mention Preventive Maintenance",
			titleFr: "Mentionnez la maintenance preventive",
			content: "Show you understand the importance of regular maintenance to prevent breakdowns.",
			contentFr: "Montrez que vous comprenez l'importance de la maintenance preventive pour eviter les pannes.",
			category: "field_specific" as const,
			field: "industrial" as const,
			tags: ["industrial", "maintenance"],
		},
		// HSE field-specific tips
		{
			id: "hse-1",
			title: "Know the Regulations",
			titleFr: "Connaissez la reglementation",
			content: "Be familiar with relevant HSE regulations and standards (ISO, local laws).",
			contentFr: "Familiarisez-vous avec la reglementation HSE pertinente et les normes (ISO 45001, Code du travail).",
			category: "field_specific" as const,
			field: "hse" as const,
			tags: ["hse", "regulations"],
		},
		{
			id: "hse-2",
			title: "Discuss Risk Assessment",
			titleFr: "Parlez d'evaluation des risques",
			content: "Be ready to explain how you would identify and evaluate workplace hazards.",
			contentFr: "Soyez pret(e) a expliquer comment vous identifieriez et evalueriez les dangers au travail.",
			category: "field_specific" as const,
			field: "hse" as const,
			tags: ["hse", "risk"],
		},
		{
			id: "hse-3",
			title: "Mention Training and Awareness",
			titleFr: "Mentionnez la formation et sensibilisation",
			content: "Show you understand the importance of safety training and communication.",
			contentFr: "Montrez que vous comprenez l'importance de la formation securite et de la sensibilisation.",
			category: "field_specific" as const,
			field: "hse" as const,
			tags: ["hse", "training"],
		},
		{
			id: "hse-4",
			title: "Discuss Emergency Procedures",
			titleFr: "Parlez des procedures d'urgence",
			content: "Be prepared to discuss emergency response plans and evacuation procedures.",
			contentFr: "Soyez pret(e) a parler des plans d'intervention d'urgence et des procedures d'evacuation.",
			category: "field_specific" as const,
			field: "hse" as const,
			tags: ["hse", "emergency"],
		},
	];

	let filtered = tips;

	if (field && field !== "general") {
		filtered = filtered.filter((t) => !t.field || t.field === field);
	}

	if (category) {
		filtered = filtered.filter((t) => t.category === category);
	}

	return filtered.map((t) => ({
		...t,
		title: language === "fr" ? t.titleFr : t.title,
		content: language === "fr" ? t.contentFr : t.content,
	}));
}

// Static common questions data
export function getCommonQuestions(
	field: "healthcare" | "industrial" | "hse" | "technology" | "management" | "general",
	type?: "behavioral" | "technical" | "situational" | "motivational" | "general",
	language: "fr" | "en" = "fr",
) {
	const questions = [
		// General questions
		{
			id: "gen-1",
			question: "Tell me about yourself.",
			questionFr: "Parlez-moi de vous.",
			type: "general" as const,
			field: "general" as const,
			sampleAnswer: "I am a [degree] graduate from [school] with experience in [area]. I chose this field because...",
			sampleAnswerFr:
				"Je suis diplome(e) en [diplome] de l'IMTA avec une experience en [domaine]. J'ai choisi ce domaine car...",
			tips: ["Keep it under 2 minutes", "Focus on relevant experience", "End with why you want this job"],
			tipsFr: [
				"Restez sous 2 minutes",
				"Concentrez-vous sur l'experience pertinente (stages)",
				"Terminez par pourquoi vous voulez ce poste",
			],
		},
		{
			id: "gen-2",
			question: "What are your strengths and weaknesses?",
			questionFr: "Quels sont vos points forts et points faibles?",
			type: "general" as const,
			field: "general" as const,
			sampleAnswerFr:
				"Parmi mes points forts, je citerais ma rigueur et ma capacite a travailler en equipe. En ce qui concerne mes points a ameliorer, j'ai tendance a vouloir tout perfectionner, mais j'apprends a mieux gerer mon temps...",
			tips: ["Choose relevant strengths", "For weaknesses, show self-awareness and improvement", "Give examples"],
			tipsFr: [
				"Choisissez des forces pertinentes au poste",
				"Pour les faiblesses, montrez la conscience de soi et l'amelioration",
				"Donnez des exemples concrets de vos stages",
			],
		},
		{
			id: "gen-3",
			question: "Why do you want to work here?",
			questionFr: "Pourquoi voulez-vous travailler ici?",
			type: "motivational" as const,
			field: "general" as const,
			sampleAnswerFr:
				"J'ai choisi votre entreprise car elle est reconnue pour [qualite specifique]. De plus, les valeurs de l'entreprise correspondent a mes aspirations professionnelles...",
			tips: ["Show you researched the company", "Connect your goals to their mission", "Be specific"],
			tipsFr: [
				"Montrez que vous avez fait des recherches sur l'entreprise",
				"Connectez vos objectifs a leur mission",
				"Soyez specifique - mentionnez des projets ou valeurs de l'entreprise",
			],
		},
		{
			id: "gen-4",
			question: "Where do you see yourself in 5 years?",
			questionFr: "Ou vous voyez-vous dans 5 ans?",
			type: "motivational" as const,
			field: "general" as const,
			sampleAnswerFr:
				"Dans 5 ans, je souhaite avoir developpe mon expertise dans ce domaine et avoir evolue vers plus de responsabilites. Je vise a contribuer significativement a l'entreprise...",
			tips: ["Show ambition but be realistic", "Align with company opportunities", "Show commitment"],
			tipsFr: [
				"Montrez de l'ambition mais restez realiste",
				"Alignez-vous avec les opportunites de l'entreprise",
				"Montrez votre engagement",
			],
		},
		{
			id: "gen-5",
			question: "Describe a challenging situation and how you handled it.",
			questionFr: "Decrivez une situation difficile et comment vous l'avez geree.",
			type: "behavioral" as const,
			field: "general" as const,
			sampleAnswerFr:
				"Pendant mon stage, j'ai fait face a [situation]. J'ai d'abord analyse le probleme, puis j'ai [action]. Le resultat a ete [resultat positif]...",
			tips: ["Use STAR method", "Choose a professional example", "Focus on positive outcome"],
			tipsFr: [
				"Utilisez la methode STAR (Situation, Tache, Action, Resultat)",
				"Choisissez un exemple de stage",
				"Mettez l'accent sur le resultat positif et ce que vous avez appris",
			],
		},
		{
			id: "gen-6",
			question: "Why should we hire you?",
			questionFr: "Pourquoi devrions-nous vous embaucher?",
			type: "motivational" as const,
			field: "general" as const,
			sampleAnswerFr:
				"Je suis convaincu(e) de pouvoir apporter une valeur ajoutee a votre equipe grace a ma formation a l'IMTA et mes experiences de stage. Ma motivation et ma capacite d'adaptation me permettront de m'integrer rapidement...",
			tips: ["Summarize your key qualifications", "Show enthusiasm", "Connect your skills to the job requirements"],
			tipsFr: [
				"Resumez vos qualifications cles",
				"Montrez votre enthousiasme",
				"Reliez vos competences aux besoins du poste",
			],
		},
		// Healthcare questions
		{
			id: "health-1",
			question: "Why did you choose nursing/healthcare?",
			questionFr: "Pourquoi avez-vous choisi le domaine de la sante?",
			type: "motivational" as const,
			field: "healthcare" as const,
			sampleAnswerFr:
				"J'ai toujours ete attire(e) par l'aide aux autres. Pendant mon stage, j'ai realise l'impact positif qu'on peut avoir sur la vie des patients. Prendre soin des autres est pour moi une vocation...",
			tips: ["Show genuine passion", "Include personal story if relevant", "Mention what inspires you"],
			tipsFr: [
				"Montrez une passion sincere",
				"Incluez une histoire personnelle si pertinent",
				"Mentionnez ce qui vous inspire dans ce metier",
			],
		},
		{
			id: "health-2",
			question: "How do you handle difficult patients?",
			questionFr: "Comment gerez-vous les patients difficiles?",
			type: "behavioral" as const,
			field: "healthcare" as const,
			sampleAnswerFr:
				"Je reste calme et professionnel(le). J'essaie de comprendre la source de leur frustration - la douleur, l'inquietude, la peur - et de communiquer avec empathie. Je leur explique clairement les soins et les ecoute...",
			tips: ["Show empathy", "Emphasize communication", "Give a specific example"],
			tipsFr: [
				"Montrez de l'empathie",
				"Mettez l'accent sur la communication et l'ecoute",
				"Donnez un exemple de stage",
			],
		},
		{
			id: "health-3",
			question: "Explain the steps for taking vital signs.",
			questionFr: "Expliquez les etapes de la prise des constantes vitales.",
			type: "technical" as const,
			field: "healthcare" as const,
			sampleAnswerFr:
				"D'abord, je me lave les mains et prepare le materiel. Je verifie l'identite du patient. Je prends d'abord la temperature, puis la tension arterielle (normale: 120/80 mmHg), le pouls (60-100 bpm) et la frequence respiratoire (12-20/min). Je note tout dans le dossier patient...",
			tips: ["Be methodical", "Mention hygiene first", "Include normal values if you can"],
			tipsFr: ["Soyez methodique", "Mentionnez l'hygiene en premier", "Incluez les valeurs normales"],
		},
		{
			id: "health-4",
			question: "How do you handle stressful situations in healthcare?",
			questionFr: "Comment gerez-vous les situations stressantes dans le domaine de la sante?",
			type: "situational" as const,
			field: "healthcare" as const,
			sampleAnswerFr:
				"Dans les situations stressantes, je me concentre sur les priorites et reste methodique. Je respire profondement et me rappelle ma formation. Je communique clairement avec l'equipe et n'hesite pas a demander de l'aide si necessaire...",
			tips: ["Show emotional control", "Mention teamwork", "Give specific example"],
			tipsFr: ["Montrez le controle emotionnel", "Mentionnez le travail d'equipe", "Donnez un exemple concret"],
		},
		{
			id: "health-5",
			question: "How do you ensure patient confidentiality?",
			questionFr: "Comment assurez-vous la confidentialite des patients?",
			type: "technical" as const,
			field: "healthcare" as const,
			sampleAnswerFr:
				"Je respecte strictement le secret medical. Je ne discute des cas qu'avec le personnel soignant concerne. Je protege les dossiers et ne laisse jamais d'informations visibles. J'utilise les mots de passe de maniere securisee...",
			tips: ["Mention legal obligations", "Give practical examples", "Show understanding of ethics"],
			tipsFr: [
				"Mentionnez les obligations legales",
				"Donnez des exemples pratiques",
				"Montrez la comprehension de l'ethique",
			],
		},
		{
			id: "health-6",
			question: "Describe how you would handle a patient fall.",
			questionFr: "Decrivez comment vous gerereriez une chute de patient.",
			type: "situational" as const,
			field: "healthcare" as const,
			sampleAnswerFr:
				"D'abord, je securise la zone et appelle a l'aide si necessaire. J'evalue l'etat du patient sans le deplacer immediatement. Je previens l'equipe medicale, note les circonstances de la chute et remplis le rapport d'incident...",
			tips: ["Prioritize safety", "Follow protocols", "Mention documentation"],
			tipsFr: ["Priorisez la securite", "Suivez les protocoles", "Mentionnez la documentation"],
		},
		// Industrial questions
		{
			id: "ind-1",
			question: "How do you approach troubleshooting a machine failure?",
			questionFr: "Comment abordez-vous le diagnostic d'une panne machine?",
			type: "technical" as const,
			field: "industrial" as const,
			sampleAnswerFr:
				"Je commence par la securite - couper l'alimentation si necessaire. Ensuite, j'identifie les symptomes (bruits, indicateurs), consulte la documentation technique, et procede par elimination systematique. Je verifie les elements les plus simples d'abord...",
			tips: ["Start with safety", "Show systematic approach", "Mention documentation"],
			tipsFr: [
				"Commencez par la securite",
				"Montrez une approche systematique",
				"Mentionnez la documentation technique",
			],
		},
		{
			id: "ind-2",
			question: "Describe a time you improved a process.",
			questionFr: "Decrivez une fois ou vous avez ameliore un processus.",
			type: "behavioral" as const,
			field: "industrial" as const,
			sampleAnswerFr:
				"Pendant mon stage, j'ai remarque que [probleme]. J'ai propose [solution] a mon maitre de stage. Apres mise en place, cela a permis de [resultat - gain de temps, reduction des pannes, etc.]...",
			tips: ["Use STAR method", "Quantify results if possible", "Show initiative"],
			tipsFr: [
				"Utilisez la methode STAR",
				"Quantifiez les resultats si possible",
				"Montrez votre initiative et esprit d'amelioration",
			],
		},
		{
			id: "ind-3",
			question: "What safety measures do you take before working on a machine?",
			questionFr: "Quelles mesures de securite prenez-vous avant d'intervenir sur une machine?",
			type: "technical" as const,
			field: "industrial" as const,
			sampleAnswerFr:
				"Je verifie d'abord que la machine est hors tension et consignee. Je porte les EPI appropries (gants, lunettes, chaussures de securite). Je balise la zone de travail et informe mes collegues de l'intervention...",
			tips: ["Mention lockout/tagout", "List PPE", "Show thoroughness"],
			tipsFr: ["Mentionnez la consignation", "Listez les EPI", "Montrez votre rigueur"],
		},
		{
			id: "ind-4",
			question: "How do you stay updated on new technologies?",
			questionFr: "Comment restez-vous a jour sur les nouvelles technologies?",
			type: "behavioral" as const,
			field: "industrial" as const,
			sampleAnswerFr:
				"Je suis regulierement des formations et je m'interesse aux nouvelles technologies via des revues specialisees. Je participe egalement aux discussions avec mes collegues et maitres de stage pour apprendre de leur experience...",
			tips: ["Show curiosity", "Mention continuous learning", "Be specific"],
			tipsFr: ["Montrez votre curiosite", "Mentionnez la formation continue", "Soyez specifique"],
		},
		{
			id: "ind-5",
			question: "How do you prioritize maintenance tasks?",
			questionFr: "Comment priorisez-vous les taches de maintenance?",
			type: "situational" as const,
			field: "industrial" as const,
			sampleAnswerFr:
				"Je priorise d'abord selon l'impact sur la production et la securite. Les pannes critiques passent en premier, puis les maintenances preventives planifiees. Je communique avec la production pour coordonner les interventions...",
			tips: ["Show understanding of priorities", "Mention communication", "Be practical"],
			tipsFr: ["Montrez la comprehension des priorites", "Mentionnez la communication", "Soyez pratique"],
		},
		{
			id: "ind-6",
			question: "Describe your experience with preventive maintenance.",
			questionFr: "Decrivez votre experience en maintenance preventive.",
			type: "technical" as const,
			field: "industrial" as const,
			sampleAnswerFr:
				"Pendant mon stage, j'ai participe a la maintenance preventive des equipements. Cela incluait les inspections regulieres, les changements d'huile, le controle des courroies et la verification des niveaux. J'utilisais les fiches de suivi pour documenter chaque intervention...",
			tips: ["Give specific examples", "Mention documentation", "Show understanding of importance"],
			tipsFr: [
				"Donnez des exemples specifiques",
				"Mentionnez la documentation",
				"Montrez l'importance de la prevention",
			],
		},
		// HSE questions
		{
			id: "hse-1",
			question: "How would you conduct a risk assessment?",
			questionFr: "Comment effectueriez-vous une evaluation des risques?",
			type: "technical" as const,
			field: "hse" as const,
			sampleAnswerFr:
				"Je commence par identifier les dangers sur le poste de travail. J'evalue qui pourrait etre affecte et comment. J'analyse la probabilite et la gravite pour calculer le niveau de risque. Je propose ensuite des mesures de prevention et de protection, puis je documente le tout et planifie le suivi...",
			tips: ["Show methodology", "Mention documentation", "Include follow-up"],
			tipsFr: ["Montrez la methodologie", "Mentionnez la documentation", "Incluez le suivi et la reevaluation"],
		},
		{
			id: "hse-2",
			question: "What would you do if you witnessed a safety violation?",
			questionFr: "Que feriez-vous si vous etiez temoin d'une violation de securite?",
			type: "situational" as const,
			field: "hse" as const,
			sampleAnswerFr:
				"D'abord, j'interviendrais pour prevenir tout danger immediat si possible. Je rappellerais poliment mais fermement les regles de securite a la personne concernee. Je documenterais l'incident et le signalerais a mon superieur selon la procedure etablie...",
			tips: ["Prioritize immediate safety", "Follow procedures", "Show balance between firmness and diplomacy"],
			tipsFr: [
				"Priorisez la securite immediate",
				"Suivez les procedures",
				"Montrez l'equilibre entre fermete et diplomatie",
			],
		},
		{
			id: "hse-3",
			question: "How would you organize a safety training session?",
			questionFr: "Comment organiseriez-vous une formation securite?",
			type: "situational" as const,
			field: "hse" as const,
			sampleAnswerFr:
				"Je commencerais par identifier les besoins specifiques et le public cible. Je preparerais un contenu adapte avec des exemples concrets et des exercices pratiques. Pendant la formation, j'utiliserais des supports visuels et encouragerais la participation. Je terminerais par une evaluation et un quiz...",
			tips: ["Show organization skills", "Mention practical exercises", "Include evaluation"],
			tipsFr: [
				"Montrez vos competences organisationnelles",
				"Mentionnez les exercices pratiques",
				"Incluez l'evaluation",
			],
		},
		{
			id: "hse-4",
			question: "What are the key elements of an emergency evacuation plan?",
			questionFr: "Quels sont les elements cles d'un plan d'evacuation d'urgence?",
			type: "technical" as const,
			field: "hse" as const,
			sampleAnswerFr:
				"Un plan d'evacuation comprend: les voies d'evacuation clairement marquees, les points de rassemblement, les roles et responsabilites (guide-file, serre-file), les procedures d'alerte, la liste du personnel, et le plan pour les personnes a mobilite reduite. Il doit etre regulierement teste et mis a jour...",
			tips: ["List key components", "Mention testing", "Show thoroughness"],
			tipsFr: ["Listez les composants cles", "Mentionnez les exercices d'evacuation", "Montrez votre rigueur"],
		},
		{
			id: "hse-5",
			question: "How do you handle resistance to safety rules?",
			questionFr: "Comment gerez-vous la resistance aux regles de securite?",
			type: "behavioral" as const,
			field: "hse" as const,
			sampleAnswerFr:
				"J'essaie d'abord de comprendre les raisons de la resistance - est-ce un probleme de comprehension ou de praticite? J'explique les risques concrets et les consequences potentielles. Je cherche des solutions pratiques avec la personne et implique la hierarchie si necessaire...",
			tips: ["Show empathy", "Explain risks", "Find practical solutions"],
			tipsFr: ["Montrez de l'empathie", "Expliquez les risques", "Trouvez des solutions pratiques"],
		},
		{
			id: "hse-6",
			question: "What PPE is required for different work environments?",
			questionFr: "Quels EPI sont necessaires pour differents environnements de travail?",
			type: "technical" as const,
			field: "hse" as const,
			sampleAnswerFr:
				"Les EPI varient selon les risques: casque pour les chantiers, lunettes pour le travail avec des produits chimiques ou des machines, gants adaptes au risque (chimique, mecanique, thermique), chaussures de securite, protection auditive dans les environnements bruyants, masques selon l'exposition...",
			tips: ["Show knowledge of different PPE", "Match PPE to risks", "Mention proper use"],
			tipsFr: [
				"Montrez la connaissance des differents EPI",
				"Associez EPI aux risques",
				"Mentionnez l'utilisation correcte",
			],
		},
	];

	let filtered = questions;

	if (field !== "general") {
		filtered = filtered.filter((q) => q.field === field || q.field === "general");
	}

	if (type) {
		filtered = filtered.filter((q) => q.type === type);
	}

	return filtered.map((q) => ({
		...q,
		question: language === "fr" ? q.questionFr : q.question,
		sampleAnswer: language === "fr" ? q.sampleAnswerFr : q.sampleAnswer,
		tips: language === "fr" ? q.tipsFr : q.tips,
	}));
}
