import type { Icon } from "@phosphor-icons/react";
import {
	BankIcon,
	BriefcaseIcon,
	FirstAidKitIcon,
	GearIcon,
	HardHatIcon,
	HeartbeatIcon,
	HouseIcon,
	PillIcon,
	StethoscopeIcon,
	UserIcon,
	WrenchIcon,
} from "@phosphor-icons/react";

import type { FieldConfigEntry, ProgramField, TrainingProgram } from "./programs-types";

// Icon mapping
export const iconMap: Record<string, Icon> = {
	FirstAidKit: FirstAidKitIcon,
	Heartbeat: HeartbeatIcon,
	Stethoscope: StethoscopeIcon,
	Pill: PillIcon,
	Gear: GearIcon,
	Wrench: WrenchIcon,
	HardHat: HardHatIcon,
	User: UserIcon,
	Briefcase: BriefcaseIcon,
	Bank: BankIcon,
	House: HouseIcon,
};

// Field configuration
export const fieldConfig: Record<ProgramField, FieldConfigEntry> = {
	healthcare: {
		label: "Healthcare",
		icon: FirstAidKitIcon,
		color: "text-red-600 dark:text-red-400",
		gradient: "from-red-500/20 via-rose-500/10 to-transparent",
		bgColor: "bg-red-100 dark:bg-red-900/30",
	},
	industrial: {
		label: "Industrial",
		icon: GearIcon,
		color: "text-blue-600 dark:text-blue-400",
		gradient: "from-blue-500/20 via-indigo-500/10 to-transparent",
		bgColor: "bg-blue-100 dark:bg-blue-900/30",
	},
	hse: {
		label: "HSE",
		icon: HardHatIcon,
		color: "text-amber-600 dark:text-amber-400",
		gradient: "from-amber-500/20 via-orange-500/10 to-transparent",
		bgColor: "bg-amber-100 dark:bg-amber-900/30",
	},
	business: {
		label: "Business",
		icon: BriefcaseIcon,
		color: "text-green-600 dark:text-green-400",
		gradient: "from-green-500/20 via-emerald-500/10 to-transparent",
		bgColor: "bg-green-100 dark:bg-green-900/30",
	},
};

export const demandLevelConfig: Record<string, { label: string; color: string }> = {
	very_high: { label: "Very High", color: "bg-green-500 text-white" },
	high: { label: "High", color: "bg-blue-500 text-white" },
	medium: { label: "Medium", color: "bg-amber-500 text-white" },
	low: { label: "Low", color: "bg-gray-500 text-white" },
};

// Complete IMTA Training Programs Catalog
export const trainingPrograms: TrainingProgram[] = [
	// Healthcare Programs
	{
		id: "sage-femme",
		name: "Midwife",
		field: "healthcare",
		duration: "3 years",
		durationMonths: 36,
		description:
			"Comprehensive training in obstetrics and gynecology. Pregnancy support, delivery, and postnatal care.",
		prerequisites: ["Science baccalaureate", "Minimum age 18", "Certified physical fitness", "Passed entrance exam"],
		careerOutcomes: ["Hospital midwife", "Independent midwife", "Maternity coordinator", "Midwifery school instructor"],
		certification: "State Diploma in Midwifery",
		salaryMin: 6000,
		salaryMax: 15000,
		salaryCurrency: "MAD",
		icon: "Heartbeat",
		employmentRate: 95,
		demandLevel: "very_high",
	},
	{
		id: "infirmier-polyvalent",
		name: "General Nurse",
		field: "healthcare",
		duration: "3 years",
		durationMonths: 36,
		description: "Versatile nursing training. Comprehensive patient care across various hospital departments.",
		prerequisites: [
			"Baccalaureate or equivalent",
			"Age between 18 and 30",
			"Good physical condition",
			"Admission by exam",
		],
		careerOutcomes: ["Hospital nurse", "Operating room nurse", "ICU nurse", "Healthcare manager"],
		certification: "State Nursing Diploma",
		salaryMin: 5000,
		salaryMax: 12000,
		salaryCurrency: "MAD",
		icon: "FirstAidKit",
		employmentRate: 92,
		demandLevel: "very_high",
	},
	{
		id: "aide-soignant",
		name: "Nursing Assistant",
		field: "healthcare",
		duration: "18 months",
		durationMonths: 18,
		description: "Training in basic care and patient support. Hygiene, comfort, and assistance with daily activities.",
		prerequisites: ["Minimum 9th grade education", "Minimum age 17", "Physical fitness", "Motivation for caregiving"],
		careerOutcomes: [
			"Hospital nursing assistant",
			"Private clinic nursing assistant",
			"Home care aide",
			"Advancement to nurse",
		],
		certification: "State Nursing Assistant Diploma",
		salaryMin: 3500,
		salaryMax: 7000,
		salaryCurrency: "MAD",
		icon: "Stethoscope",
		employmentRate: 88,
		demandLevel: "high",
	},
	{
		id: "auxiliaire-pharmacie",
		name: "Pharmacy Assistant",
		field: "healthcare",
		duration: "2 years",
		durationMonths: 24,
		description:
			"Training in medication dispensing and pharmaceutical counseling. Stock management and patient reception.",
		prerequisites: [
			"Science baccalaureate preferred",
			"Good interpersonal skills",
			"Rigor and precision",
			"Basic chemistry knowledge",
		],
		careerOutcomes: [
			"Retail pharmacy assistant",
			"Hospital pharmacy technician",
			"Pharmaceutical stock manager",
			"Medical representative",
		],
		certification: "Pharmacy Assistant Diploma",
		salaryMin: 4000,
		salaryMax: 8000,
		salaryCurrency: "MAD",
		icon: "Pill",
		employmentRate: 85,
		demandLevel: "high",
	},
	// Industrial Programs
	{
		id: "technicien-maintenance",
		name: "Industrial Maintenance Technician",
		field: "industrial",
		duration: "2 years",
		durationMonths: 24,
		description:
			"Comprehensive training in preventive and corrective maintenance of industrial equipment. Fault diagnosis and repairs.",
		prerequisites: [
			"Technical or science baccalaureate",
			"Knowledge of mechanics/electricity",
			"Teamwork ability",
			"Availability for shift work",
		],
		careerOutcomes: [
			"Maintenance technician",
			"Maintenance manager",
			"Field service technician",
			"Production supervisor",
		],
		certification: "Specialized Maintenance Technician Diploma",
		salaryMin: 5000,
		salaryMax: 12000,
		salaryCurrency: "MAD",
		icon: "Wrench",
		employmentRate: 89,
		demandLevel: "very_high",
	},
	{
		id: "conducteur-engins",
		name: "Construction Equipment Operator",
		field: "industrial",
		duration: "12 months",
		durationMonths: 12,
		description:
			"Training in operating and handling construction equipment. Excavators, loaders, cranes, and bulldozers.",
		prerequisites: [
			"Driver's license preferred",
			"Minimum age 21",
			"Good physical condition",
			"Normal visual and auditory acuity",
		],
		careerOutcomes: [
			"Construction equipment operator",
			"Mining equipment operator",
			"Site team leader",
			"Equipment operation instructor",
		],
		certification: "CACES and Equipment Operator Certificate",
		salaryMin: 4500,
		salaryMax: 10000,
		salaryCurrency: "MAD",
		icon: "Gear",
		employmentRate: 87,
		demandLevel: "high",
	},
	{
		id: "soudeur",
		name: "Welder",
		field: "industrial",
		duration: "18 months",
		durationMonths: 18,
		description:
			"Training in welding techniques (TIG, MIG, ARC). Blueprint reading, preparation, and assembly of metal parts.",
		prerequisites: ["Minimum vocational certificate", "Good manual dexterity", "Normal vision", "Physical endurance"],
		careerOutcomes: [
			"Qualified welder",
			"High-pressure welder",
			"Welding shop supervisor",
			"Welding quality inspector",
		],
		certification: "Welding Qualification Certificate",
		salaryMin: 4000,
		salaryMax: 9000,
		salaryCurrency: "MAD",
		icon: "Gear",
		employmentRate: 84,
		demandLevel: "high",
	},
	{
		id: "electricien-industriel",
		name: "Industrial Electrician",
		field: "industrial",
		duration: "2 years",
		durationMonths: 24,
		description:
			"Training in industrial electricity. Installation, maintenance, and troubleshooting of electrical systems and automation.",
		prerequisites: [
			"Technical baccalaureate or equivalent",
			"Basic electrical knowledge",
			"Rigor and precision",
			"Compliance with safety standards",
		],
		careerOutcomes: [
			"Industrial electrician",
			"Automation technician",
			"Electrical manager",
			"Electrical design engineer",
		],
		certification: "Industrial Electrical Technician Diploma",
		salaryMin: 5000,
		salaryMax: 11000,
		salaryCurrency: "MAD",
		icon: "Gear",
		employmentRate: 86,
		demandLevel: "very_high",
	},
	// HSE Programs
	{
		id: "technicien-hse",
		name: "HSE Technician",
		field: "hse",
		duration: "2 years",
		durationMonths: 24,
		description:
			"Training in Health, Safety, and Environment. Risk assessment, prevention plans, and regulatory compliance.",
		prerequisites: ["Science or technical baccalaureate", "Safety awareness", "Writing skills", "Interpersonal skills"],
		careerOutcomes: ["HSE Technician", "Safety coordinator", "Prevention officer", "HSE Manager"],
		certification: "Specialized HSE Technician Diploma",
		salaryMin: 5500,
		salaryMax: 13000,
		salaryCurrency: "MAD",
		icon: "HardHat",
		employmentRate: 90,
		demandLevel: "very_high",
	},
	{
		id: "responsable-qualite",
		name: "Quality Manager",
		field: "hse",
		duration: "2 years",
		durationMonths: 24,
		description:
			"Training in quality management. Implementation and monitoring of quality systems, audits, and continuous improvement.",
		prerequisites: ["Baccalaureate or higher", "Analytical mindset", "Knowledge of ISO standards", "Leadership"],
		careerOutcomes: ["Quality manager", "Quality auditor", "Quality consultant", "Quality director"],
		certification: "Quality Management Diploma",
		salaryMin: 6000,
		salaryMax: 15000,
		salaryCurrency: "MAD",
		icon: "HardHat",
		employmentRate: 88,
		demandLevel: "high",
	},
	{
		id: "coordinateur-securite",
		name: "Safety Coordinator",
		field: "hse",
		duration: "18 months",
		durationMonths: 18,
		description:
			"Training in coordinating safety measures on construction sites and industrial facilities. Safety plans and risk management.",
		prerequisites: [
			"Construction or industrial experience",
			"Knowledge of regulations",
			"Natural authority",
			"Attention to detail",
		],
		careerOutcomes: ["SPS Coordinator", "Site safety manager", "Safety trainer", "Prevention expert"],
		certification: "SPS Safety Coordinator Certificate",
		salaryMin: 5000,
		salaryMax: 12000,
		salaryCurrency: "MAD",
		icon: "HardHat",
		employmentRate: 85,
		demandLevel: "high",
	},
	// Business Programs
	{
		id: "comptable-entreprise",
		name: "Corporate Accountant",
		field: "business",
		duration: "2 years",
		durationMonths: 24,
		description:
			"Comprehensive training in general and analytical accounting. Financial management, taxation, and accounting software.",
		prerequisites: [
			"Economics or science baccalaureate",
			"Rigor and organization",
			"Mathematical proficiency",
			"Basic computer knowledge",
		],
		careerOutcomes: ["Corporate accountant", "Accounting assistant", "Payroll manager", "Chief accountant"],
		certification: "Corporate Accountant Diploma",
		salaryMin: 4500,
		salaryMax: 12000,
		salaryCurrency: "MAD",
		icon: "Bank",
		employmentRate: 82,
		demandLevel: "high",
	},
	{
		id: "assistant-rh",
		name: "HR Assistant",
		field: "business",
		duration: "2 years",
		durationMonths: 24,
		description:
			"Training in human resources management. Recruitment, personnel administration, training, and career management.",
		prerequisites: [
			"Baccalaureate or equivalent",
			"Interpersonal skills",
			"Professional discretion",
			"Proficiency in office software",
		],
		careerOutcomes: ["HR Assistant", "Recruitment officer", "Payroll manager", "HR Manager"],
		certification: "Human Resources Assistant Diploma",
		salaryMin: 4000,
		salaryMax: 10000,
		salaryCurrency: "MAD",
		icon: "User",
		employmentRate: 80,
		demandLevel: "medium",
	},
	{
		id: "secretaire-direction",
		name: "Executive Secretary",
		field: "business",
		duration: "18 months",
		durationMonths: 18,
		description:
			"High-level secretarial training. Organization, communication, calendar management, and executive support.",
		prerequisites: [
			"Baccalaureate or equivalent",
			"Excellent written and oral communication",
			"Language proficiency",
			"Professional appearance",
		],
		careerOutcomes: ["Executive secretary", "Executive assistant", "Office manager", "Executive assistant"],
		certification: "Executive Secretary Diploma",
		salaryMin: 4000,
		salaryMax: 9000,
		salaryCurrency: "MAD",
		icon: "Briefcase",
		employmentRate: 78,
		demandLevel: "medium",
	},
];
