import type { SuccessStory } from "./success-stories-types";

// Sample success stories data
export const successStories: SuccessStory[] = [
	{
		id: "1",
		name: "Fatima Zahra El Amrani",
		currentPosition: "Coordinating Midwife",
		company: "CHU Ibn Sina, Rabat",
		programId: "sage-femme",
		programName: "Midwifery",
		category: "healthcare",
		graduationYear: 2020,
		shortQuote: "The IMTA training gave me the skills and confidence to excel in my midwifery career.",
		fullStory:
			"My journey began in 2018 when I decided to pursue my dream of becoming a midwife. The training at IMTA was a transformative experience. The hands-on courses, hospital internships, and instructor support allowed me to develop solid expertise. After graduating in 2020, I started as a midwife at CHU Ibn Sina. Thanks to my hard work and the skills I acquired, I was promoted to coordinator after only 3 years. Today, I supervise a team of 12 midwives and participate in training new recruits. What makes me most proud is being able to support expectant mothers during such a special moment in their lives.",
		advice: [
			"Never underestimate the importance of practical internships",
			"Build a professional network from the start of your training",
			"Stay curious and continue learning throughout your career",
			"Communication with patients is just as important as technical skills",
		],
		keyLessons: [
			"Perseverance always pays off",
			"Empathy is a skill that can be learned",
			"Teamwork is essential in healthcare",
			"Every experience, even difficult ones, is a learning opportunity",
		],
		helpfulSkills: ["Patient communication", "Stress management", "Teamwork", "Obstetric care", "Leadership"],
		careerTimeline: [
			{
				year: "2018",
				title: "Started training",
				description: "Enrolled in the IMTA Midwifery program",
				type: "education",
			},
			{
				year: "2019",
				title: "Hospital internship",
				description: "6-month practical internship at the Casablanca Hospital Center",
				type: "education",
			},
			{
				year: "2020",
				title: "Graduation",
				description: "Graduated with honors in Midwifery",
				type: "achievement",
			},
			{
				year: "2020",
				title: "First job",
				description: "Hired at CHU Ibn Sina as a midwife",
				type: "job",
			},
			{
				year: "2023",
				title: "Promotion",
				description: "Promoted to Coordinating Midwife",
				type: "promotion",
			},
		],
		avatarInitials: "FZ",
		location: "Rabat",
		featured: true,
	},
	{
		id: "2",
		name: "Mohammed Benali",
		currentPosition: "HSE Site Supervisor",
		company: "OCP Group",
		programId: "hse-specialist",
		programName: "HSE Specialist",
		category: "hse",
		graduationYear: 2019,
		shortQuote:
			"Going from a simple technician to HSE site supervisor in 4 years - the IMTA training was the catalyst for my success.",
		fullStory:
			"Before my training at IMTA, I worked as a factory worker with no advancement prospects. I decided to train in HSE to change my life. The training opened my eyes to the importance of workplace safety and gave me the tools to make a difference. My first position was as an HSE technician in a construction company. I quickly gained my supervisors' trust through my rigor and knowledge. Today, at OCP, I am responsible for safety on major projects. I also train new employees on safety standards. It's incredible to see how far I've come.",
		advice: [
			"Certification is essential, but field experience is even more important",
			"Document everything - it's the foundation of the HSE profession",
			"Learn to communicate with all hierarchical levels",
			"Stay up to date on constantly evolving regulations",
		],
		keyLessons: [
			"Safety is never a cost, it's an investment",
			"A good HSE professional must be a teacher above all",
			"Prevention is always better than correction",
			"Following procedures saves lives",
		],
		helpfulSkills: ["Risk analysis", "Safety audit", "Training", "Crisis management", "Regulations"],
		careerTimeline: [
			{
				year: "2017",
				title: "Career change",
				description: "Decision to train in HSE after 5 years as a factory worker",
				type: "education",
			},
			{
				year: "2018",
				title: "IMTA training",
				description: "HSE Specialist program with international certification",
				type: "education",
			},
			{
				year: "2019",
				title: "First HSE position",
				description: "HSE Technician at a construction company",
				type: "job",
			},
			{
				year: "2021",
				title: "Career advancement",
				description: "Hired at OCP as Junior HSE Manager",
				type: "job",
			},
			{
				year: "2023",
				title: "Current promotion",
				description: "HSE Site Supervisor overseeing 200+ employees",
				type: "promotion",
			},
		],
		avatarInitials: "MB",
		location: "Khouribga",
	},
	{
		id: "3",
		name: "Aicha Bouazza",
		currentPosition: "Head Nurse",
		company: "Clinique Internationale de Marrakech",
		programId: "infirmier-polyvalent",
		programName: "General Nurse",
		category: "healthcare",
		graduationYear: 2018,
		shortQuote: "In 5 years, I went from intern to head of department. IMTA gave me the wings to fly.",
		fullStory:
			"I always wanted to help others. The general nursing training at IMTA allowed me to fulfill this dream. What struck me most was the quality of supervision and the diversity of internships. I was able to explore several specialties before finding my path in pediatrics. After graduating, I started at a private clinic in Marrakech. My commitment and versatility were quickly recognized. Today, I manage a team of 20 caregivers and continue to train. I just obtained a specialization in pediatric intensive care.",
		advice: [
			"Be proactive during your internships - ask questions",
			"Versatility is your greatest asset",
			"Don't be afraid to ask for responsibilities",
			"Take care of yourself to better care for others",
		],
		keyLessons: [
			"Excellence is built day by day",
			"A smile can change a patient's day",
			"Continuing education is indispensable",
			"Leadership is learned in the field",
		],
		helpfulSkills: ["General nursing", "Team management", "Communication", "Pediatric care", "Emergency care"],
		careerTimeline: [
			{
				year: "2016",
				title: "IMTA enrollment",
				description: "Started the General Nurse program",
				type: "education",
			},
			{
				year: "2017",
				title: "Pediatrics internship",
				description: "Discovered my calling in the pediatric department",
				type: "education",
			},
			{
				year: "2018",
				title: "Graduation and employment",
				description: "Graduated and immediately hired at the clinic",
				type: "job",
			},
			{
				year: "2020",
				title: "Senior nurse",
				description: "Promoted to senior nurse in pediatrics",
				type: "promotion",
			},
			{
				year: "2023",
				title: "Head of department",
				description: "Appointed as Head Nurse",
				type: "promotion",
			},
		],
		avatarInitials: "AB",
		location: "Marrakech",
	},
	{
		id: "4",
		name: "Youssef Haddad",
		currentPosition: "Logistics Manager",
		company: "Renault Maroc",
		programId: "conducteur-engins",
		programName: "Heavy Equipment Operator",
		category: "industrial",
		graduationYear: 2017,
		shortQuote: "From forklift operator to logistics manager - the training was the first step of a long journey.",
		fullStory:
			"When I finished my heavy equipment operator training at IMTA, I never thought I'd go this far. I started as a simple forklift operator in a warehouse. But the training had taught me much more than driving - it taught me logistics, safety, and organization. I demonstrated my skills and climbed the ranks. Today, I am logistics manager at Renault Maroc, managing a team of 50 people and millions of dirhams worth of goods. I will never forget where I came from.",
		advice: [
			"Master the basics before aiming higher",
			"Show initiative even in small tasks",
			"Learn everything you can about supply chain",
			"Additional certifications open doors",
		],
		keyLessons: [
			"Every position is a learning opportunity",
			"Safety and efficiency go hand in hand",
			"Respect for others is the foundation of leadership",
			"Ambition without work leads nowhere",
		],
		helpfulSkills: ["Equipment operation", "Logistics", "Inventory management", "Management", "SAP/WMS"],
		careerTimeline: [
			{
				year: "2015",
				title: "IMTA training",
				description: "Heavy Equipment Operator program with CACES certification",
				type: "education",
			},
			{
				year: "2016",
				title: "First job",
				description: "Forklift operator at a distribution center",
				type: "job",
			},
			{
				year: "2018",
				title: "Renault Maroc",
				description: "Hired as senior forklift operator at Renault",
				type: "job",
			},
			{
				year: "2020",
				title: "Team leader",
				description: "Promoted to logistics team leader",
				type: "promotion",
			},
			{
				year: "2022",
				title: "Logistics Manager",
				description: "Promoted to current position",
				type: "promotion",
			},
		],
		avatarInitials: "YH",
		location: "Tanger",
	},
	{
		id: "5",
		name: "Khadija Ouazzani",
		currentPosition: "Lead Healthcare Assistant",
		company: "Maison de Retraite Les Oliviers",
		programId: "aide-soignant",
		programName: "Healthcare Assistant",
		category: "healthcare",
		graduationYear: 2021,
		shortQuote:
			"Caring for our elders is my mission. The training taught me that it is a noble and rewarding profession.",
		fullStory:
			"At 35, after being a stay-at-home mother for 10 years, I decided to launch a career in healthcare. The healthcare assistant training at IMTA welcomed me with kindness. I was afraid of not being up to the task, but the instructors supported me. Internships at nursing homes revealed my calling: accompanying elderly people with dignity and respect. Today, I am my team's lead and train new healthcare assistants. It's a second career that I am immensely proud of.",
		advice: [
			"It's never too late for a career change",
			"Your life experience is an asset, not a handicap",
			"Patience is the number one quality in this profession",
			"Every resident has a story that deserves to be heard",
		],
		keyLessons: [
			"Career change is possible at any age",
			"Life experience enriches caregiving",
			"Kindness is cultivated daily",
			"Working with the elderly is profoundly human",
		],
		helpfulSkills: ["Basic care", "Patient support", "Communication", "Patience", "Teamwork"],
		careerTimeline: [
			{
				year: "2020",
				title: "Career change decision",
				description: "Enrolled in the Healthcare Assistant program after a 10-year break",
				type: "education",
			},
			{
				year: "2020",
				title: "Training and internships",
				description: "Discovered working in nursing homes",
				type: "education",
			},
			{
				year: "2021",
				title: "First job",
				description: "Hired at Les Oliviers as a healthcare assistant",
				type: "job",
			},
			{
				year: "2023",
				title: "Team lead",
				description: "Promoted to lead and trainer",
				type: "promotion",
			},
		],
		avatarInitials: "KO",
		location: "Fes",
	},
	{
		id: "6",
		name: "Omar Benjelloun",
		currentPosition: "Senior Mechanical Technician",
		company: "Alstom Maroc",
		programId: "mecanique-engins",
		programName: "Heavy Equipment Mechanics",
		category: "industrial",
		graduationYear: 2019,
		shortQuote: "Repairing the biggest machines in the country - that's what the IMTA training enabled me to do.",
		fullStory:
			"Mechanics has been my passion since childhood. But without a diploma, finding a good job was difficult. The heavy equipment mechanics training at IMTA changed my life. I learned on modern equipment, with instructors from the industry. My internship at a construction equipment dealership opened the doors to Alstom, where I work on train and tramway maintenance. It's technical and rewarding work. Every day, I contribute to the mobility of millions of Moroccans.",
		advice: [
			"Passion isn't enough, you need certified skills",
			"Internships are disguised job interviews",
			"Specialize in a high-demand field",
			"Never stop learning new technologies",
		],
		keyLessons: [
			"Precision is everything in mechanics",
			"A good diagnosis is better than a bad repair",
			"Safety first, always",
			"A job well done is its own reward",
		],
		helpfulSkills: ["Heavy mechanics", "Hydraulics", "Diagnostics", "Preventive maintenance", "Embedded electronics"],
		careerTimeline: [
			{
				year: "2017",
				title: "IMTA training",
				description: "Heavy Equipment Mechanics program",
				type: "education",
			},
			{
				year: "2018",
				title: "Successful internship",
				description: "Internship at a Caterpillar dealership",
				type: "education",
			},
			{
				year: "2019",
				title: "First job",
				description: "Mechanical technician at a construction company",
				type: "job",
			},
			{
				year: "2021",
				title: "Alstom Maroc",
				description: "Hired for railway maintenance",
				type: "job",
			},
			{
				year: "2023",
				title: "Senior Technician",
				description: "Promoted with team responsibility",
				type: "promotion",
			},
		],
		avatarInitials: "OB",
		location: "Casablanca",
	},
	{
		id: "7",
		name: "Salma Idrissi",
		currentPosition: "HSE Manager",
		company: "LafargeHolcim Maroc",
		programId: "hse-specialist",
		programName: "HSE Specialist",
		category: "hse",
		graduationYear: 2020,
		shortQuote:
			"Workplace safety has no gender. As a woman in industry, I prove every day that competence comes first.",
		fullStory:
			"Being a woman in the field of industrial safety is not always easy. But my training at IMTA armed me with solid skills and unwavering confidence. I started as a junior HSE auditor, visiting male-dominated worksites. My rigor and expertise quickly earned everyone's respect. Today, at LafargeHolcim, I am responsible for safety across multiple sites. I also mentor young women who want to follow this path. There are more and more of us!",
		advice: [
			"Don't let anyone define you by your gender",
			"Technical competence is your best weapon",
			"Build your support network",
			"Be the change you want to see in the industry",
		],
		keyLessons: [
			"Diversity strengthens safety",
			"Authority comes from expertise, not title",
			"Every obstacle overcome strengthens your legitimacy",
			"Helping others succeed multiplies your impact",
		],
		helpfulSkills: ["HSE audit", "Regulations", "Management", "Communication", "Leadership"],
		careerTimeline: [
			{
				year: "2018",
				title: "IMTA training",
				description: "HSE Specialist program - first woman in the class",
				type: "education",
			},
			{
				year: "2019",
				title: "ISO certification",
				description: "ISO 45001 auditor certification",
				type: "achievement",
			},
			{
				year: "2020",
				title: "First position",
				description: "HSE auditor at a consulting firm",
				type: "job",
			},
			{
				year: "2022",
				title: "LafargeHolcim",
				description: "Hired as HSE coordinator",
				type: "job",
			},
			{
				year: "2024",
				title: "HSE Manager",
				description: "Promoted to multi-site manager",
				type: "promotion",
			},
		],
		avatarInitials: "SI",
		location: "Meknes",
	},
	{
		id: "8",
		name: "Hassan Tazi",
		currentPosition: "Technical Instructor",
		company: "IMTA - Training Institute",
		programId: "tourneur-industriel",
		programName: "Industrial Lathe Operator",
		category: "industrial",
		graduationYear: 2015,
		shortQuote: "After benefiting from IMTA training, I came back to pass it on. The circle is complete.",
		fullStory:
			"My story with IMTA began almost 10 years ago. I was a young man without a diploma, passionate about machines but with no clear future. The industrial lathe operator training gave me a trade and direction. After several years in the automotive industry, I had the opportunity to return to IMTA as an instructor. Today, I train the new generation of technicians. Seeing my former students succeed in industry is my greatest pride. It's my way of giving back what the institute gave me.",
		advice: [
			"Precision in machining is measured in micrometers, not approximations",
			"Respect the machines and they will respect you",
			"Share your knowledge - that's how it multiplies",
			"Your first job is just the beginning of the journey",
		],
		keyLessons: [
			"Teaching is the most rewarding profession",
			"Field experience is irreplaceable",
			"Patience is the mother of all skills",
			"Each generation brings something new",
		],
		helpfulSkills: ["CNC machining", "Blueprint reading", "Metrology", "Training", "Pedagogy"],
		careerTimeline: [
			{
				year: "2013",
				title: "IMTA training",
				description: "Industrial Lathe Operator program with CNC specialization",
				type: "education",
			},
			{
				year: "2015",
				title: "Automotive industry",
				description: "Machining technician at an equipment manufacturer",
				type: "job",
			},
			{
				year: "2018",
				title: "Workshop supervisor",
				description: "Promoted to machining workshop supervisor",
				type: "promotion",
			},
			{
				year: "2020",
				title: "Train-the-trainer",
				description: "Technical pedagogy certification",
				type: "achievement",
			},
			{
				year: "2021",
				title: "Return to IMTA",
				description: "Hired as a permanent technical instructor",
				type: "job",
			},
		],
		avatarInitials: "HT",
		location: "Casablanca",
		featured: true,
	},
	{
		id: "9",
		name: "Amina Elkhalfi",
		currentPosition: "General Nurse",
		company: "CHU Hassan II, Fes",
		programId: "infirmier-polyvalent",
		programName: "General Nurse",
		category: "healthcare",
		graduationYear: 2023,
		shortQuote:
			"Coming from a rural background is not an obstacle - it's a strength. IMTA training proved that perseverance opens all doors.",
		fullStory:
			"Growing up in a small village near Taza, far from big cities and opportunities, could have been a barrier to my ambition. But my family always encouraged me to pursue my dreams. I discovered the IMTA General Nurse program during an open day and knew it was my path. During my training, I used the platform's resume builder to polish my application and stand out from other graduates. I created a professional resume that highlighted my internships and practical skills. Just two months after graduating, I was hired at CHU Hassan II in Fes. I actively contacted HR departments at several hospitals, attended recruitment events, and accepted volunteer assignments during my training to build my network. Today, I am proud to care for patients from all backgrounds and to show young people from my region that nothing is impossible.",
		advice: [
			"Don't let your origins define your limits",
			"Polish your resume - it's your first professional impression",
			"Contact hospital HR departments directly",
			"Volunteering during training is an investment in your future",
		],
		keyLessons: [
			"Perseverance compensates for all initial disadvantages",
			"Professional networking starts from the first day of training",
			"A well-crafted resume can make the difference between two equal candidates",
			"Every internship is an opportunity to leave a good impression",
		],
		helpfulSkills: [
			"Patient care",
			"Emergency response",
			"Team communication",
			"Medical records management",
			"General nursing",
		],
		careerTimeline: [
			{
				year: "2021",
				title: "IMTA enrollment",
				description: "Started the General Nurse program after a year of preparation",
				type: "education",
			},
			{
				year: "2022",
				title: "CHU Hassan II internship",
				description: "4-month practical internship in internal medicine and emergency departments",
				type: "education",
			},
			{
				year: "2022",
				title: "Hospital volunteering",
				description: "Volunteer work to strengthen skills and professional network",
				type: "achievement",
			},
			{
				year: "2023",
				title: "Graduation",
				description: "Obtained the General Nurse diploma",
				type: "achievement",
			},
			{
				year: "2023",
				title: "Hired at CHU Hassan II",
				description: "Employed as a general nurse two months after graduation",
				type: "job",
			},
		],
		avatarInitials: "AE",
		location: "Fes",
		featured: false,
	},
	{
		id: "10",
		name: "Omar Bensouda",
		currentPosition: "Senior Equipment Mechanic",
		company: "OCP Group",
		programId: "mecanique-engins",
		programName: "Heavy Equipment Mechanics",
		category: "industrial",
		graduationYear: 2022,
		shortQuote:
			"From internship to permanent hire at OCP - technical competence and passion for the trade make all the difference.",
		fullStory:
			"Heavy mechanics has always fascinated me. Seeing multi-ton machines come back to life in my hands is an incomparable satisfaction. When I joined the IMTA Heavy Equipment Mechanics program, I already had some basic knowledge, but the training gave me a rigorous structure and industry-recognized certified skills. During my internship at OCP Group in Khouribga, I gave everything to impress the managers. I repaired complex breakdowns on excavators and dump trucks that my senior colleagues hadn't been able to resolve quickly. The platform's career roadmap tool helped me plan my certifications: advanced hydraulics, welding, then manufacturer certifications. Six months after my internship ended, OCP offered me a permanent contract. In three years, my salary has nearly doubled. I keep a detailed maintenance journal for each machine - it's a habit I picked up at IMTA and it has earned me a lot of respect in the field.",
		advice: [
			"Practical experience is worth ten times more than diplomas alone",
			"Plan your certifications from the start - each one opens a new door",
			"Keep a personal maintenance journal, it's your best tool for growth",
			"A successful internship is often the shortest path to a permanent contract",
		],
		keyLessons: [
			"Technical mastery inspires trust and respect",
			"Certifications are long-term investments",
			"Rigorous documentation distinguishes a good technician from an excellent one",
			"Impressing during an internship requires preparation, not luck",
		],
		helpfulSkills: [
			"Heavy equipment maintenance",
			"Hydraulic systems",
			"Welding",
			"Electronic diagnostics",
			"Technical report writing",
		],
		careerTimeline: [
			{
				year: "2020",
				title: "IMTA training",
				description: "Enrolled in Heavy Equipment Mechanics with hydraulics specialization",
				type: "education",
			},
			{
				year: "2021",
				title: "OCP Group internship",
				description: "6-month internship at the Khouribga mining site",
				type: "education",
			},
			{
				year: "2021",
				title: "Hydraulics certification",
				description: "Obtained advanced hydraulic systems certification",
				type: "achievement",
			},
			{
				year: "2022",
				title: "Graduation and employment",
				description: "Graduated and hired permanently at OCP Group",
				type: "job",
			},
			{
				year: "2024",
				title: "Senior mechanic promotion",
				description: "Promoted with responsibility for a team of 4 technicians",
				type: "promotion",
			},
		],
		avatarInitials: "OB",
		location: "Khouribga",
		featured: false,
	},
	{
		id: "11",
		name: "Khadija Mouline",
		currentPosition: "Specialized Healthcare Assistant",
		company: "Clinique Internationale, Casablanca",
		programId: "aide-soignant",
		programName: "Healthcare Assistant",
		category: "healthcare",
		graduationYear: 2024,
		shortQuote:
			"At 32, I left everything to care for others. The IMTA career quiz revealed a talent I didn't know I had.",
		fullStory:
			"For seven years, I worked in retail at a Casablanca shopping mall. I had a stable job but felt empty. I wanted my work to have deep meaning. One evening, I took the professional aptitude assessment on the IMTA platform. The result surprised me: healthcare aptitude profile, high empathy, developed sense of service. I had never considered it. After a night of reflection, I applied for the Healthcare Assistant program. The one-year program was intensive but perfectly suited for someone changing careers. The instructors understood our situation - several of us already had professional lives. My years in customer service taught me to handle difficult people with calm and a smile, a valuable skill with patients. Six months after graduating, I work at the Clinique Internationale de Casablanca. I continue my training with specialization modules in elderly care. It truly is never too late.",
		advice: [
			"Listen to career guidance tools - they sometimes reveal what you don't dare admit to yourself",
			"Your past experience, even in a different field, is an asset in healthcare",
			"Career change takes courage but brings invaluable satisfaction",
			"Continuing education is the key to progress even in short programs",
		],
		keyLessons: [
			"Professional aptitude can be found where you least expect it",
			"Empathy is the most important skill in healthcare, and it can be learned",
			"Changing careers at any age is not only possible but often enriching",
			"Patient care requires as many human skills as technical ones",
		],
		helpfulSkills: [
			"Hygiene and basic care",
			"Vital signs monitoring",
			"Elderly care",
			"Stress and emergency management",
			"Compassionate communication",
		],
		careerTimeline: [
			{
				year: "2023",
				title: "Career change",
				description: "Decision to leave retail after the IMTA career assessment quiz",
				type: "education",
			},
			{
				year: "2023",
				title: "Healthcare Assistant training",
				description: "Intensive one-year program with hospital and clinic internships",
				type: "education",
			},
			{
				year: "2024",
				title: "Graduation",
				description: "Obtained the Healthcare Assistant diploma with honors",
				type: "achievement",
			},
			{
				year: "2024",
				title: "First position",
				description: "Hired at the Clinique Internationale de Casablanca",
				type: "job",
			},
		],
		avatarInitials: "KM",
		location: "Casablanca",
		featured: false,
	},
	{
		id: "12",
		name: "Yassine Tazi",
		currentPosition: "Full Stack Developer",
		company: "Startup Tech, Casablanca",
		programId: "developpeur-web",
		programName: "Web Developer",
		category: "technology",
		graduationYear: 2023,
		shortQuote:
			"IMTA transformed my self-taught passion into certified expertise. My first client came within weeks thanks to my portfolio.",
		fullStory:
			"I had been teaching myself to code since the age of 17, watching online tutorials and building small personal projects. But without certification or structure, it was difficult to convince employers or clients. The IMTA Web Developer program was the missing link. The training gave me the methodological rigor and best practices that I would have taken years to discover on my own. I built my portfolio on the IMTA platform during training, and by the end of my program, I had 5 complete projects to showcase. My first freelance client came 3 weeks after graduation, having seen my projects online. Today, I hold a full stack developer position at a Casablanca startup and take on freelance projects that give me significant financial independence. I also contribute to Moroccan open source projects and lead networking sessions at Casablanca tech meetups. The Moroccan tech ecosystem is booming and I'm taking my place in it.",
		advice: [
			"Build your portfolio from day one of training, don't wait until the end",
			"Open source is the best business card for a junior developer",
			"Attend local tech meetups - networking is as important as code",
			"Combining employment and freelance work greatly accelerates your growth",
		],
		keyLessons: [
			"Being self-taught is an asset, but certification gives it credibility",
			"A visible portfolio is worth more than ten standard applications",
			"The startup ecosystem offers unmatched learning opportunities",
			"Contributing to the tech community positions you as an expert quickly",
		],
		helpfulSkills: ["React", "Node.js", "PostgreSQL", "Mobile development", "Git and collaboration"],
		careerTimeline: [
			{
				year: "2021",
				title: "IMTA training",
				description: "Web Developer program with React, Node.js, and database modules",
				type: "education",
			},
			{
				year: "2022",
				title: "Open source contribution",
				description: "First pull requests accepted on Moroccan open source projects",
				type: "achievement",
			},
			{
				year: "2023",
				title: "Graduation and first client",
				description: "Graduated and first freelance client acquired through online portfolio",
				type: "job",
			},
			{
				year: "2023",
				title: "Startup position",
				description: "Hired as a full stack developer at a tech startup in Casablanca",
				type: "job",
			},
			{
				year: "2024",
				title: "Confirmed developer",
				description: "Promoted to senior developer with responsibility for two juniors",
				type: "promotion",
			},
		],
		avatarInitials: "YT",
		location: "Casablanca",
		featured: false,
	},
];
