/**
 * Business card theme definitions.
 * Each theme provides consistent styling for the card header, body, and text.
 */
export const businessCardThemes = {
	minimal: {
		name: "Minimal",
		wrapper: "bg-white dark:bg-slate-900",
		header: "bg-slate-100 dark:bg-slate-800",
		headerText: "text-slate-900 dark:text-white",
		headerSubtext: "text-slate-600 dark:text-slate-300",
		body: "bg-white dark:bg-slate-900",
		bodyText: "text-slate-700 dark:text-slate-200",
		bodySubtext: "text-slate-500 dark:text-slate-400",
		border: "border-slate-200 dark:border-slate-700",
		iconBg: "bg-slate-100 dark:bg-slate-800",
		iconColor: "text-slate-600 dark:text-slate-400",
		buttonBg: "bg-slate-900 dark:bg-white",
		buttonText: "text-white dark:text-slate-900",
	},
	professional: {
		name: "Professional",
		wrapper: "bg-white dark:bg-slate-900",
		header: "bg-gradient-to-r from-blue-600 to-blue-700",
		headerText: "text-white",
		headerSubtext: "text-blue-100",
		body: "bg-white dark:bg-slate-900",
		bodyText: "text-slate-700 dark:text-slate-200",
		bodySubtext: "text-slate-500 dark:text-slate-400",
		border: "border-slate-200 dark:border-slate-700",
		iconBg: "bg-blue-50 dark:bg-blue-900/30",
		iconColor: "text-blue-600 dark:text-blue-400",
		buttonBg: "bg-blue-600 hover:bg-blue-700",
		buttonText: "text-white",
	},
	modern: {
		name: "Modern",
		wrapper: "bg-slate-900",
		header: "bg-gradient-to-br from-purple-600 to-pink-500",
		headerText: "text-white",
		headerSubtext: "text-purple-100",
		body: "bg-slate-900",
		bodyText: "text-slate-200",
		bodySubtext: "text-slate-400",
		border: "border-slate-700",
		iconBg: "bg-slate-800",
		iconColor: "text-purple-400",
		buttonBg: "bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-700 hover:to-pink-600",
		buttonText: "text-white",
	},
	creative: {
		name: "Creative",
		wrapper: "bg-gradient-to-br from-amber-50 to-orange-100 dark:from-slate-900 dark:to-slate-800",
		header: "bg-gradient-to-r from-orange-500 to-red-500",
		headerText: "text-white",
		headerSubtext: "text-orange-100",
		body: "bg-white/80 dark:bg-slate-900/80 backdrop-blur-sm",
		bodyText: "text-slate-700 dark:text-slate-200",
		bodySubtext: "text-slate-500 dark:text-slate-400",
		border: "border-orange-200 dark:border-orange-900/50",
		iconBg: "bg-orange-50 dark:bg-orange-900/30",
		iconColor: "text-orange-600 dark:text-orange-400",
		buttonBg: "bg-gradient-to-r from-orange-500 to-red-500 hover:from-orange-600 hover:to-red-600",
		buttonText: "text-white",
	},
	moroccan: {
		name: "Moroccan",
		wrapper: "bg-[#fdf9f3] dark:bg-[#0a0a0a] border-2 border-[#c19a6b]/20",
		header: "bg-[#1a3a3a] border-b-4 border-[#c19a6b]",
		headerText: "text-[#fdf9f3] font-display",
		headerSubtext: "text-[#c19a6b]",
		body: "bg-[#fdf9f3] dark:bg-[#0a0a0a]",
		bodyText: "text-[#1a3a3a] dark:text-[#fdf9f3]",
		bodySubtext: "text-[#c19a6b]",
		border: "border-[#c19a6b]/20",
		iconBg: "bg-[#1a3a3a]/5 dark:bg-[#c19a6b]/10",
		iconColor: "text-[#1a3a3a] dark:text-[#c19a6b]",
		buttonBg: "bg-[#1a3a3a] hover:bg-[#2a4a4a]",
		buttonText: "text-[#fdf9f3]",
	},
	elegant: {
		name: "Elegant",
		wrapper:
			"bg-gradient-to-br from-slate-50 to-stone-100 dark:from-zinc-900 dark:to-slate-900 border border-stone-200/50 dark:border-zinc-700/50",
		header: "bg-gradient-to-br from-stone-800 to-zinc-900",
		headerText: "text-stone-50 tracking-wide",
		headerSubtext: "text-stone-300 tracking-wider text-xs uppercase",
		body: "bg-transparent",
		bodyText: "text-stone-700 dark:text-stone-200",
		bodySubtext: "text-stone-500 dark:text-stone-400",
		border: "border-stone-200/50 dark:border-zinc-700/50",
		iconBg: "bg-stone-100 dark:bg-zinc-800",
		iconColor: "text-stone-600 dark:text-stone-300",
		buttonBg: "bg-stone-800 hover:bg-stone-900 dark:bg-stone-200 dark:hover:bg-stone-100",
		buttonText: "text-stone-50 dark:text-stone-900",
	},
	glassmorphism: {
		name: "Glass",
		wrapper: "bg-white/30 dark:bg-black/30 backdrop-blur-xl border border-white/20 dark:border-white/10",
		header: "bg-gradient-to-r from-indigo-500/80 to-purple-600/80 backdrop-blur-sm",
		headerText: "text-white drop-shadow-sm",
		headerSubtext: "text-indigo-100",
		body: "bg-white/50 dark:bg-black/50 backdrop-blur-md",
		bodyText: "text-slate-800 dark:text-slate-100",
		bodySubtext: "text-slate-600 dark:text-slate-400",
		border: "border-white/20 dark:border-white/10",
		iconBg: "bg-white/60 dark:bg-white/10 backdrop-blur-sm",
		iconColor: "text-indigo-600 dark:text-indigo-300",
		buttonBg: "bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700",
		buttonText: "text-white",
	},
	neon: {
		name: "Neon",
		wrapper: "bg-gray-950 border-2 border-cyan-500/30",
		header: "bg-gray-900 border-b-2 border-cyan-400/50",
		headerText: "text-cyan-400 drop-shadow-[0_0_10px_rgba(34,211,238,0.5)]",
		headerSubtext: "text-fuchsia-400 drop-shadow-[0_0_8px_rgba(232,121,249,0.4)]",
		body: "bg-gray-950",
		bodyText: "text-gray-200",
		bodySubtext: "text-gray-500",
		border: "border-cyan-500/20",
		iconBg: "bg-cyan-500/10",
		iconColor: "text-cyan-400",
		buttonBg:
			"bg-gradient-to-r from-cyan-500 to-fuchsia-500 hover:from-cyan-400 hover:to-fuchsia-400 shadow-[0_0_20px_rgba(34,211,238,0.3)]",
		buttonText: "text-white font-semibold",
	},
} as const;

export type BusinessCardTheme = keyof typeof businessCardThemes;
export type BusinessCardThemeConfig = (typeof businessCardThemes)[BusinessCardTheme];
