import type {
	CompanyCultureProfile,
	CultureQuestion,
	RedFlag,
	ValuesQuestion,
	WorkStyleQuestion,
} from "./culture-match-types";

// =============================================================================
// WORK STYLE ASSESSMENT CONFIGURATION
// =============================================================================

export const WORK_STYLE_QUESTIONS: WorkStyleQuestion[] = [
	{
		id: "ws1",
		question: "How do you prefer to organize your workday?",
		category: "structure",
		options: [
			{
				id: "ws1-a",
				text: "Structured schedule with fixed hours",
				scores: { workLifeBalance: 3, innovation: -1, growth: 0 },
			},
			{
				id: "ws1-b",
				text: "Total flexibility, I manage my own time",
				scores: { workLifeBalance: 1, innovation: 3, growth: 2 },
			},
			{
				id: "ws1-c",
				text: "A mix of both depending on the project",
				scores: { workLifeBalance: 2, innovation: 2, collaboration: 1 },
			},
			{
				id: "ws1-d",
				text: "Clear objectives but freedom in methods",
				scores: { growth: 3, innovation: 2, transparency: 1 },
			},
		],
	},
	{
		id: "ws2",
		question: "Which office environment suits you best?",
		category: "environment",
		options: [
			{
				id: "ws2-a",
				text: "Dynamic and collaborative open space",
				scores: { collaboration: 3, innovation: 2, workLifeBalance: -1 },
			},
			{
				id: "ws2-b",
				text: "Quiet and private individual office",
				scores: { workLifeBalance: 2, collaboration: -1, growth: 1 },
			},
			{
				id: "ws2-c",
				text: "Fully remote from home",
				scores: { workLifeBalance: 3, collaboration: -1, diversity: 2 },
			},
			{
				id: "ws2-d",
				text: "Hybrid with collaborative spaces and quiet zones",
				scores: { collaboration: 2, workLifeBalance: 2, innovation: 1 },
			},
		],
	},
	{
		id: "ws3",
		question: "How do you prefer to receive feedback?",
		category: "communication",
		options: [
			{
				id: "ws3-a",
				text: "Frequent and informal feedback",
				scores: { transparency: 3, growth: 2, collaboration: 2 },
			},
			{
				id: "ws3-b",
				text: "Formal periodic evaluations",
				scores: { transparency: 1, growth: 1, workLifeBalance: 2 },
			},
			{
				id: "ws3-c",
				text: "360-degree feedback from colleagues",
				scores: { collaboration: 3, transparency: 2, diversity: 1 },
			},
			{
				id: "ws3-d",
				text: "Self-assessment with personalized coaching",
				scores: { growth: 3, innovation: 1, transparency: 1 },
			},
		],
	},
	{
		id: "ws4",
		question: "How do you approach team projects?",
		category: "collaboration",
		options: [
			{
				id: "ws4-a",
				text: "Natural leader, I enjoy coordinating",
				scores: { growth: 3, collaboration: 2, innovation: 1 },
			},
			{
				id: "ws4-b",
				text: "Expert individual contributor",
				scores: { innovation: 2, growth: 2, collaboration: 0 },
			},
			{
				id: "ws4-c",
				text: "Facilitator, I foster collaboration",
				scores: { collaboration: 3, diversity: 2, transparency: 2 },
			},
			{
				id: "ws4-d",
				text: "Flexible role based on team needs",
				scores: { collaboration: 2, growth: 2, diversity: 1 },
			},
		],
	},
	{
		id: "ws5",
		question: "What is your approach to change?",
		category: "growth",
		options: [
			{
				id: "ws5-a",
				text: "I love change and innovation",
				scores: { innovation: 3, growth: 3, workLifeBalance: -1 },
			},
			{
				id: "ws5-b",
				text: "I prefer stability and established processes",
				scores: { workLifeBalance: 3, innovation: -1, transparency: 1 },
			},
			{
				id: "ws5-c",
				text: "Change is good if well managed",
				scores: { transparency: 2, growth: 1, collaboration: 1 },
			},
			{
				id: "ws5-d",
				text: "I often initiate change myself",
				scores: { innovation: 3, growth: 2, diversity: 1 },
			},
		],
	},
];

export const VALUES_QUESTIONS: ValuesQuestion[] = [
	{
		id: "v1",
		statement: "Work-life balance is essential to me",
		category: "lifestyle",
		dimension: "workLifeBalance",
	},
	{
		id: "v2",
		statement: "I want to work on innovative and cutting-edge projects",
		category: "work",
		dimension: "innovation",
	},
	{
		id: "v3",
		statement: "Teamwork is more important than individual achievements",
		category: "work",
		dimension: "collaboration",
	},
	{
		id: "v4",
		statement: "I seek continuous learning and growth opportunities",
		category: "career",
		dimension: "growth",
	},
	{
		id: "v5",
		statement: "Diversity and inclusion are priorities for me",
		category: "values",
		dimension: "diversity",
	},
	{
		id: "v6",
		statement: "I value transparency in company communication",
		category: "values",
		dimension: "transparency",
	},
	{
		id: "v7",
		statement: "A high salary is more important than other benefits",
		category: "compensation",
		dimension: "workLifeBalance",
	},
	{
		id: "v8",
		statement: "I prefer a flat and accessible hierarchy",
		category: "structure",
		dimension: "transparency",
	},
	{
		id: "v9",
		statement: "I want to contribute to a meaningful mission",
		category: "purpose",
		dimension: "diversity",
	},
	{
		id: "v10",
		statement: "Public recognition of my work matters to me",
		category: "recognition",
		dimension: "collaboration",
	},
];

// Reference company archetypes for culture comparison algorithm — not real companies
export const COMPANY_PROFILES: CompanyCultureProfile[] = [
	{
		id: "tech-startup",
		name: "InnoTech Maroc",
		industry: "Technology",
		location: "Casablanca",
		size: "50-200 employees",
		description: "Fast-growing technology startup specializing in fintech solutions for Africa.",
		cultureScores: {
			workLifeBalance: 60,
			innovation: 95,
			collaboration: 85,
			growth: 90,
			diversity: 75,
			transparency: 80,
		},
		values: ["Innovation", "Agility", "Social impact", "Autonomy"],
		perks: ["Flexible remote work", "Stock options", "Unlimited training", "No dress code"],
		workStyle: "Agile with 2-week sprints",
		remotePolicy: "Hybrid 3 days office / 2 days remote",
	},
	{
		id: "multinational",
		name: "Atlas Industries",
		industry: "Industrial / Manufacturing",
		location: "Tanger",
		size: "1000+ employees",
		description: "Moroccan industrial leader with international presence in automotive and aerospace.",
		cultureScores: {
			workLifeBalance: 75,
			innovation: 65,
			collaboration: 70,
			growth: 80,
			diversity: 85,
			transparency: 60,
		},
		values: ["Excellence", "Safety", "Respect", "Performance"],
		perks: ["Comprehensive insurance", "Retirement plan", "Subsidized cafeteria", "Transport"],
		workStyle: "Structured with defined processes",
		remotePolicy: "On-site with occasional flexibility",
	},
	{
		id: "healthcare",
		name: "Clinique Al Amal",
		industry: "Healthcare",
		location: "Rabat",
		size: "200-500 employees",
		description: "Private healthcare facility recognized for its expertise and patient-centric approach.",
		cultureScores: {
			workLifeBalance: 55,
			innovation: 70,
			collaboration: 90,
			growth: 75,
			diversity: 80,
			transparency: 70,
		},
		values: ["Compassion", "Medical excellence", "Ethics", "Teamwork"],
		perks: ["Continuing medical education", "Organized on-call shifts", "Family health insurance", "Parking"],
		workStyle: "Rotation and on-call with stable teams",
		remotePolicy: "On-site required (healthcare)",
	},
	{
		id: "consulting",
		name: "Strategos Conseil",
		industry: "Consulting",
		location: "Casablanca",
		size: "50-200 employees",
		description: "Strategy and transformation consulting firm supporting major Moroccan enterprises.",
		cultureScores: {
			workLifeBalance: 40,
			innovation: 80,
			collaboration: 75,
			growth: 95,
			diversity: 70,
			transparency: 65,
		},
		values: ["Excellence", "Client first", "Personal development", "Integrity"],
		perks: ["Performance bonus", "Client travel", "Sponsored MBA", "Latest laptop"],
		workStyle: "Intensive projects with rest periods",
		remotePolicy: "Depends on client engagements",
	},
	{
		id: "energy",
		name: "Solaris Energy",
		industry: "Renewable energy",
		location: "Ouarzazate",
		size: "200-500 employees",
		description: "Moroccan pioneer in solar energy, operator of photovoltaic power plants.",
		cultureScores: {
			workLifeBalance: 70,
			innovation: 85,
			collaboration: 75,
			growth: 70,
			diversity: 90,
			transparency: 85,
		},
		values: ["Sustainability", "Green innovation", "Community", "Safety"],
		perks: ["On-site housing", "Solar bonus", "Additional leave", "HSE training"],
		workStyle: "Operations with rotation and planned maintenance",
		remotePolicy: "Mixed depending on position",
	},
];

export const RED_FLAGS: RedFlag[] = [
	{
		id: "rf1",
		category: "Recruitment",
		flag: "Very long recruitment process (> 2 months) without communication",
		severity: "high",
		explanation: "May indicate internal disorganization or lack of respect for candidates.",
		checked: false,
	},
	{
		id: "rf2",
		category: "Recruitment",
		flag: "Inappropriate personal questions during the interview",
		severity: "high",
		explanation: "Potential violation of labor law and indicator of toxic culture.",
		checked: false,
	},
	{
		id: "rf3",
		category: "Management",
		flag: "High turnover mentioned or visible on LinkedIn",
		severity: "high",
		explanation: "Sign of management problems or difficult working conditions.",
		checked: false,
	},
	{
		id: "rf4",
		category: "Management",
		flag: "Manager who speaks negatively about current employees",
		severity: "high",
		explanation: "Blame culture and lack of professionalism.",
		checked: false,
	},
	{
		id: "rf5",
		category: "Compensation",
		flag: "Vague salary or 'depending on profile' without a range",
		severity: "medium",
		explanation: "Lack of transparency, may hide low salaries.",
		checked: false,
	},
	{
		id: "rf6",
		category: "Compensation",
		flag: "Promises of rapid promotion without clear criteria",
		severity: "medium",
		explanation: "Tactic to attract with false hopes.",
		checked: false,
	},
	{
		id: "rf7",
		category: "Culture",
		flag: "'We are a family' used excessively",
		severity: "medium",
		explanation: "May mask expectations of constant availability and blurred boundaries.",
		checked: false,
	},
	{
		id: "rf8",
		category: "Culture",
		flag: "No clear remote work policy post-COVID",
		severity: "low",
		explanation: "May indicate organizational rigidity.",
		checked: false,
	},
	{
		id: "rf9",
		category: "Conditions",
		flag: "Overtime considered 'normal' or 'expected'",
		severity: "high",
		explanation: "Burnout culture and disregard for work-life balance.",
		checked: false,
	},
	{
		id: "rf10",
		category: "Conditions",
		flag: "Abnormally long probation period (> 6 months)",
		severity: "medium",
		explanation: "May indicate reluctance to commit or instability.",
		checked: false,
	},
	{
		id: "rf11",
		category: "Transparency",
		flag: "Refusal to show the workspace or introduce the team",
		severity: "medium",
		explanation: "May hide a problematic work environment.",
		checked: false,
	},
	{
		id: "rf12",
		category: "Transparency",
		flag: "Very negative and recent reviews on Glassdoor/Indeed",
		severity: "high",
		explanation: "Direct feedback from former employees that should not be ignored.",
		checked: false,
	},
];

export const CULTURE_QUESTIONS: CultureQuestion[] = [
	{
		id: "cq1",
		category: "Management",
		question: "How would you describe the management style here?",
		whyAsk: "Understand whether management is authoritarian, collaborative, or laissez-faire.",
		greenFlags: ["Coaching and mentoring", "Open communication", "Regular feedback"],
		redFlags: ["Micromanagement", "Top-down decisions only", "Inaccessible manager"],
	},
	{
		id: "cq2",
		category: "Growth",
		question: "What are the advancement opportunities for this position?",
		whyAsk: "Evaluate growth possibilities and investment in employees.",
		greenFlags: ["Clear career plan", "Sponsored training", "Internal mobility"],
		redFlags: ["No defined plan", "Rare promotions", "Frequent stagnation"],
	},
	{
		id: "cq3",
		category: "Team",
		question: "How does the team celebrate successes and handle failures?",
		whyAsk: "Understand the culture of recognition and learning.",
		greenFlags: ["Public recognition", "Constructive post-mortem", "Learning culture"],
		redFlags: ["No celebration", "Individual blame", "Fear of failure"],
	},
	{
		id: "cq4",
		category: "Balance",
		question: "What does a typical day look like and what are the working hours?",
		whyAsk: "Evaluate work-life balance.",
		greenFlags: ["Flexible hours", "Respect for boundaries", "Leave encouraged"],
		redFlags: ["Long hours normalized", "Weekend emails", "Difficult vacations"],
	},
	{
		id: "cq5",
		category: "Values",
		question: "How are the company's values reflected in daily work?",
		whyAsk: "Verify whether stated values are truly lived.",
		greenFlags: ["Concrete examples", "Aligned decisions", "Employee ambassadors"],
		redFlags: ["Vague answers", "Contradictions", "Marketing values only"],
	},
	{
		id: "cq6",
		category: "Diversity",
		question: "What initiatives exist for diversity and inclusion?",
		whyAsk: "Evaluate genuine commitment to diversity.",
		greenFlags: ["Concrete programs", "Diverse leadership", "Resource groups"],
		redFlags: ["No initiatives", "Homogeneous team", "Defensive response"],
	},
	{
		id: "cq7",
		category: "Communication",
		question: "How does information flow within the company?",
		whyAsk: "Understand the level of organizational transparency.",
		greenFlags: ["Regular town halls", "Accessible documentation", "Explained decisions"],
		redFlags: ["Siloed information", "Frequent rumors", "Management surprises"],
	},
	{
		id: "cq8",
		category: "Innovation",
		question: "How does the company encourage innovation and new ideas?",
		whyAsk: "Evaluate openness to change and experimentation.",
		greenFlags: ["Dedicated innovation time", "Experimentation budget", "Employee ideas valued"],
		redFlags: ["'We've always done it this way'", "Resistance to change", "Rigid hierarchy"],
	},
];
