import type { Icon } from "@phosphor-icons/react";
import { BriefcaseIcon, FirstAidKitIcon, GearIcon, GlobeIcon, HardHatIcon, SparkleIcon } from "@phosphor-icons/react";
import type {
	CompanyBenefit,
	CompanyCultureInsight,
	CompanyEmployeeReview,
	CompanyIndustry,
	CompanyInterviewQuestion,
	CompanyInterviewTip,
	CompanyKeyPerson,
	CompanyNewsItem,
	CompanySalaryRange,
	CompanyValue,
} from "@/integrations/drizzle/schema";
import { generateId } from "@/utils/string";

// Industry config
export const industryConfig: Record<CompanyIndustry, { label: string; icon: Icon; color: string }> = {
	healthcare: {
		label: "Santé",
		icon: FirstAidKitIcon,
		color: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
	},
	industrial: {
		label: "Industrie",
		icon: GearIcon,
		color: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
	},
	manufacturing: {
		label: "Fabrication",
		icon: GearIcon,
		color: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-400",
	},
	mining: {
		label: "Mines et chimie",
		icon: HardHatIcon,
		color: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
	},
	automotive: {
		label: "Automobile",
		icon: GearIcon,
		color: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400",
	},
	services: {
		label: "Services",
		icon: BriefcaseIcon,
		color: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
	},
	energy: {
		label: "Énergie",
		icon: SparkleIcon,
		color: "bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400",
	},
	tech: {
		label: "Technologie",
		icon: GlobeIcon,
		color: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-400",
	},
};

// Seed data for new users — inserted into DB via ORPC on first visit
export const DEFAULT_COMPANIES_DATA = [
	{
		name: "OCP Group",
		industry: "mining" as CompanyIndustry,
		description:
			"Global leader in the phosphate industry and its derivatives. OCP is the world's largest phosphate exporter and significantly contributes to global food security.",
		mission: "Feed the world responsibly and sustainably",
		vision: "Become the global leader in sustainable nutrition",
		location: "Casablanca, Khouribga, Safi, Jorf Lasfar",
		headquarters: "Casablanca",
		employeeCount: "21,000+",
		founded: 1920,
		website: "https://www.ocpgroup.ma",
		linkedIn: "https://linkedin.com/company/ocp-group",
		revenue: "9.4 billion USD",
		stockSymbol: "OCP.CSE",
		cultureInsights: [
			{
				category: "Work-Life Balance",
				score: 72,
				description: "Decent work-life balance with flexible hours for certain positions",
			},
			{
				category: "Diversity & Inclusion",
				score: 85,
				description: "Strong commitment to diversity with dedicated programs",
			},
			{
				category: "Career Opportunities",
				score: 88,
				description: "Excellent advancement possibilities and internal mobility",
			},
			{
				category: "Management",
				score: 75,
				description: "Hierarchical management but evolving toward more collaboration",
			},
			{
				category: "Innovation",
				score: 82,
				description: "Innovation culture with significant research programs",
			},
		] as CompanyCultureInsight[],
		cultureValues: [
			{ value: "Excellence", description: "Strive for excellence in all our actions and decisions" },
			{ value: "Innovation", description: "Encourage creativity and new ideas" },
			{ value: "Sustainability", description: "Act responsibly for future generations" },
			{ value: "Integrity", description: "Act with ethics and transparency" },
		] as CompanyValue[],
		cultureOverallScore: 80,
		reviews: [
			{
				id: generateId(),
				title: "Excellent experience early in career",
				position: "HSE Engineer",
				rating: 4.5,
				date: "2025-01-15",
				pros: "Continuous training, good social benefits, interesting projects on an international scale",
				cons: "Decision-making processes sometimes slow, bureaucracy in some departments",
				advice: "Continue modernizing processes and accelerating digital transformation",
				recommend: true,
				approveOfCEO: true,
			},
			{
				id: generateId(),
				title: "Stable company with good prospects",
				position: "Maintenance Technician",
				rating: 4.0,
				date: "2024-12-20",
				pros: "Job security, competitive salaries, safe work environment",
				cons: "Geographic remoteness for some sites, rotations required",
				advice: "Improve housing conditions at remote sites",
				recommend: true,
				approveOfCEO: true,
			},
			{
				id: generateId(),
				title: "Good company but can do better",
				position: "Financial Analyst",
				rating: 3.5,
				date: "2024-11-10",
				pros: "International reputation, advancement opportunities",
				cons: "High workload, inter-department communication needs improvement",
				advice: "Invest more in collaborative tools",
				recommend: true,
				approveOfCEO: false,
			},
		] as CompanyEmployeeReview[],
		reviewsAverageRating: 4.0,
		reviewsTotalCount: 342,
		reviewsRecommendRate: 85,
		reviewsCeoApprovalRate: 78,
		interviewQuestions: [
			{
				id: generateId(),
				question: "Describe an HSE project you have led",
				category: "behavioral" as const,
				difficulty: "medium" as const,
				frequency: 85,
			},
			{
				id: generateId(),
				question: "How do you handle emergency situations on site?",
				category: "situational" as const,
				difficulty: "hard" as const,
				frequency: 78,
			},
			{
				id: generateId(),
				question: "Which ISO standards are you familiar with?",
				category: "technical" as const,
				difficulty: "medium" as const,
				frequency: 92,
			},
			{
				id: generateId(),
				question: "Why do you want to join OCP?",
				category: "general" as const,
				difficulty: "easy" as const,
				frequency: 98,
			},
			{
				id: generateId(),
				question: "How would you motivate a team resistant to change?",
				category: "behavioral" as const,
				difficulty: "hard" as const,
				frequency: 65,
			},
		] as CompanyInterviewQuestion[],
		interviewTips: [
			{ tip: "Prepare concrete examples of HSE projects you have led", category: "Preparation" },
			{ tip: "Research OCP's sustainable development projects", category: "Research" },
			{ tip: "Show your knowledge of the mining sector and its challenges", category: "Technical" },
			{ tip: "Be ready to discuss geographic mobility", category: "Expectations" },
		] as CompanyInterviewTip[],
		interviewDifficulty: 3.5,
		interviewAverageDuration: "2-3 weeks",
		interviewProcessSteps: [
			"Online application",
			"Resume screening",
			"Technical test",
			"HR interview",
			"Manager interview",
			"Offer",
		],
		salaries: [
			{
				role: "HSE Engineer",
				minSalary: 12000,
				maxSalary: 22000,
				medianSalary: 16000,
				totalComp: 19000,
				sampleSize: 45,
			},
			{
				role: "Maintenance Technician",
				minSalary: 6000,
				maxSalary: 12000,
				medianSalary: 8500,
				totalComp: 10000,
				sampleSize: 120,
			},
			{
				role: "Project Manager",
				minSalary: 18000,
				maxSalary: 35000,
				medianSalary: 25000,
				totalComp: 30000,
				sampleSize: 28,
			},
			{
				role: "Data Analyst",
				minSalary: 10000,
				maxSalary: 18000,
				medianSalary: 14000,
				totalComp: 16000,
				sampleSize: 35,
			},
			{
				role: "Production Manager",
				minSalary: 15000,
				maxSalary: 28000,
				medianSalary: 20000,
				totalComp: 24000,
				sampleSize: 42,
			},
		] as CompanySalaryRange[],
		benefits: [
			{
				category: "Health",
				items: ["Comprehensive health insurance", "Dental coverage", "Specialist consultations"],
				rating: 4.5,
			},
			{
				category: "Retirement",
				items: ["Supplementary retirement plan", "Company savings plan", "End-of-career bonus"],
				rating: 4.2,
			},
			{
				category: "Leave",
				items: ["25 days of leave", "Additional seniority leave", "Paid sick days"],
				rating: 4.0,
			},
			{
				category: "Perks",
				items: ["Performance bonus", "13th month salary", "Profit sharing", "Company housing"],
				rating: 4.3,
			},
			{
				category: "Training",
				items: ["Annual training budget", "Certified training programs", "International mobility"],
				rating: 4.6,
			},
		] as CompanyBenefit[],
		news: [
			{
				id: generateId(),
				title: "OCP launches new training program for 5,000 young people",
				summary:
					"OCP Group announces a vocational training program aimed at training 5,000 young people in mining industry trades.",
				date: "2025-01-20",
				source: "L'Economiste",
				type: "announcement" as const,
			},
			{
				id: generateId(),
				title: "OCP wins the 2024 Sustainable Innovation Award",
				summary:
					"International recognition for the group's efforts in sustainable development and technological innovation.",
				date: "2024-12-15",
				source: "Reuters",
				type: "award" as const,
			},
			{
				id: generateId(),
				title: "Strategic partnership with Mohammed VI University",
				summary: "Collaboration agreement for research and development in the field of sustainable agriculture.",
				date: "2024-11-28",
				source: "MAP",
				type: "partnership" as const,
			},
		] as CompanyNewsItem[],
		keyPeople: [
			{
				id: generateId(),
				name: "Mostafa Terrab",
				title: "Chairman & CEO",
				department: "Executive Leadership",
				yearsAtCompany: 18,
				linkedIn: "https://linkedin.com/in/mostafa-terrab",
			},
			{
				id: generateId(),
				name: "Hanane Mourchid",
				title: "Chief Human Capital Officer",
				department: "Human Resources",
				yearsAtCompany: 12,
				linkedIn: "https://linkedin.com/in/hanane-mourchid",
			},
			{
				id: generateId(),
				name: "Khalid Sendide",
				title: "R&D Director",
				department: "Innovation",
				yearsAtCompany: 15,
				linkedIn: "https://linkedin.com/in/khalid-sendide",
			},
		] as CompanyKeyPerson[],
	},
	{
		name: "Renault Maroc",
		industry: "automotive" as CompanyIndustry,
		description:
			"World-renowned automobile manufacturer with a strong industrial presence in Morocco. The Tangier plant is one of the most modern in Africa.",
		mission: "Make sustainable mobility accessible to all",
		vision: "Leader of electric mobility in Africa",
		location: "Tanger, Casablanca",
		headquarters: "Tanger",
		employeeCount: "9,000+",
		founded: 2012,
		website: "https://www.renault.ma",
		linkedIn: "https://linkedin.com/company/renault-maroc",
		revenue: "2.1 billion USD",
		cultureInsights: [
			{
				category: "Work-Life Balance",
				score: 68,
				description: "Structured factory hours, limited flexibility for production positions",
			},
			{
				category: "Diversity & Inclusion",
				score: 78,
				description: "Diversity programs in place, continuous improvement",
			},
			{
				category: "Career Opportunities",
				score: 82,
				description: "Good advancement possibilities within the global Renault group",
			},
			{ category: "Management", score: 70, description: "Structured management, performance-driven culture" },
			{
				category: "Innovation",
				score: 85,
				description: "Strong investment in innovation and electric vehicles",
			},
		] as CompanyCultureInsight[],
		cultureValues: [
			{ value: "Quality", description: "Commitment to manufacturing excellence" },
			{ value: "Teamwork", description: "Collaboration and team spirit" },
			{ value: "Safety", description: "Employee safety is paramount" },
			{ value: "Innovation", description: "Pioneers of tomorrow's mobility" },
		] as CompanyValue[],
		cultureOverallScore: 76,
		reviews: [
			{
				id: generateId(),
				title: "Good production experience",
				position: "Quality Technician",
				rating: 4.0,
				date: "2025-01-10",
				pros: "Quality training, international environment, modern technologies",
				cons: "Shift work, pressure on production targets",
				advice: "Improve working conditions for rotating shifts",
				recommend: true,
				approveOfCEO: true,
			},
			{
				id: generateId(),
				title: "Great training company",
				position: "Process Engineer",
				rating: 4.3,
				date: "2024-12-05",
				pros: "Excellent training, international mobility opportunities, competitive salaries",
				cons: "Location far from Casablanca, stress during new model launches",
				advice: "Continue investing in employee well-being",
				recommend: true,
				approveOfCEO: true,
			},
		] as CompanyEmployeeReview[],
		reviewsAverageRating: 4.1,
		reviewsTotalCount: 218,
		reviewsRecommendRate: 82,
		reviewsCeoApprovalRate: 75,
		interviewQuestions: [
			{
				id: generateId(),
				question: "Describe your experience in an industrial environment",
				category: "behavioral" as const,
				difficulty: "medium" as const,
				frequency: 90,
			},
			{
				id: generateId(),
				question: "How do you ensure quality in a production process?",
				category: "technical" as const,
				difficulty: "medium" as const,
				frequency: 88,
			},
			{
				id: generateId(),
				question: "What do you know about Renault's electric strategy?",
				category: "general" as const,
				difficulty: "easy" as const,
				frequency: 75,
			},
			{
				id: generateId(),
				question: "How would you react to a major quality defect?",
				category: "situational" as const,
				difficulty: "hard" as const,
				frequency: 70,
			},
		] as CompanyInterviewQuestion[],
		interviewTips: [
			{ tip: "Know the models produced in Tangier (Dacia, Renault)", category: "Research" },
			{ tip: "Prepare examples of continuous improvement initiatives", category: "Preparation" },
			{ tip: "Show your flexibility for shift work", category: "Expectations" },
		] as CompanyInterviewTip[],
		interviewDifficulty: 3.2,
		interviewAverageDuration: "2-4 weeks",
		interviewProcessSteps: [
			"Application",
			"Psychometric test",
			"HR interview",
			"Technical interview",
			"Factory tour",
			"Offer",
		],
		salaries: [
			{ role: "Quality Technician", minSalary: 5500, maxSalary: 10000, medianSalary: 7500, sampleSize: 85 },
			{ role: "Process Engineer", minSalary: 10000, maxSalary: 18000, medianSalary: 13000, sampleSize: 45 },
			{ role: "Team Leader", minSalary: 8000, maxSalary: 14000, medianSalary: 11000, sampleSize: 60 },
			{ role: "Production Manager", minSalary: 15000, maxSalary: 25000, medianSalary: 19000, sampleSize: 25 },
		] as CompanySalaryRange[],
		benefits: [
			{ category: "Health", items: ["Health insurance", "On-site occupational physician"], rating: 4.0 },
			{ category: "Transport", items: ["Free shuttle buses", "Employee parking", "Transport allowance"], rating: 4.5 },
			{ category: "Dining", items: ["Subsidized company restaurant", "Meal vouchers"], rating: 4.2 },
			{ category: "Bonuses", items: ["13th month salary", "Performance bonus", "Seniority bonus"], rating: 4.0 },
		] as CompanyBenefit[],
		news: [
			{
				id: generateId(),
				title: "Renault Maroc surpasses 400,000 vehicles produced in 2024",
				summary: "The Tangier plant sets a new annual production record.",
				date: "2025-01-08",
				source: "Medias24",
				type: "announcement" as const,
			},
			{
				id: generateId(),
				title: "Launch of electric Renault 5 production in Tangier",
				summary: "Renault Maroc prepares to produce the brand's new electric icon.",
				date: "2024-11-20",
				source: "Le Matin",
				type: "announcement" as const,
			},
		] as CompanyNewsItem[],
		keyPeople: [
			{
				id: generateId(),
				name: "Marc Nassif",
				title: "General Manager",
				department: "Executive Leadership",
				yearsAtCompany: 8,
				linkedIn: "https://linkedin.com/in/marc-nassif",
			},
			{
				id: generateId(),
				name: "Fatima Zahra Ammor",
				title: "HR Director",
				department: "Human Resources",
				yearsAtCompany: 6,
				linkedIn: "https://linkedin.com/in/fz-ammor",
			},
		] as CompanyKeyPerson[],
	},
	{
		name: "CHU Ibn Rochd",
		industry: "healthcare" as CompanyIndustry,
		description:
			"Leading University Hospital Center in Casablanca. A major institution for training and specialized care in Morocco.",
		mission: "Provide quality care and train tomorrow's healthcare professionals",
		vision: "Become a recognized center of medical excellence in Africa",
		location: "Casablanca",
		headquarters: "Casablanca",
		employeeCount: "5,000+",
		founded: 1954,
		website: "https://www.chuibnrochd.ma",
		cultureInsights: [
			{
				category: "Work-Life Balance",
				score: 55,
				description: "Demanding hours in the hospital sector, frequent on-call shifts",
			},
			{
				category: "Diversity & Inclusion",
				score: 80,
				description: "Diverse environment with multidisciplinary teams",
			},
			{ category: "Career Opportunities", score: 75, description: "Specialization and advancement possibilities" },
			{ category: "Management", score: 65, description: "Traditional hierarchical structure" },
			{ category: "Mission", score: 90, description: "Strong sense of mission and public service" },
		] as CompanyCultureInsight[],
		cultureValues: [
			{ value: "Public Service", description: "Commitment to patients and the community" },
			{ value: "Medical Excellence", description: "Pursuing the highest standards of care" },
			{ value: "Training", description: "Passing on medical knowledge" },
			{ value: "Humanity", description: "Placing the patient at the heart of care" },
		] as CompanyValue[],
		cultureOverallScore: 73,
		reviews: [
			{
				id: generateId(),
				title: "Educational but demanding experience",
				position: "Nurse",
				rating: 3.5,
				date: "2025-01-05",
				pros: "Continuous training, varied medical cases, supportive team",
				cons: "High workload, sometimes outdated equipment",
				advice: "Invest in modernizing equipment",
				recommend: true,
				approveOfCEO: false,
			},
		] as CompanyEmployeeReview[],
		reviewsAverageRating: 3.6,
		reviewsTotalCount: 156,
		reviewsRecommendRate: 70,
		reviewsCeoApprovalRate: 60,
		interviewQuestions: [
			{
				id: generateId(),
				question: "Describe an emergency situation you have managed",
				category: "situational" as const,
				difficulty: "hard" as const,
				frequency: 95,
			},
			{
				id: generateId(),
				question: "How do you handle stress at work?",
				category: "behavioral" as const,
				difficulty: "medium" as const,
				frequency: 88,
			},
			{
				id: generateId(),
				question: "What are your emergency care skills?",
				category: "technical" as const,
				difficulty: "medium" as const,
				frequency: 90,
			},
		] as CompanyInterviewQuestion[],
		interviewTips: [
			{ tip: "Prepare concrete clinical case examples", category: "Preparation" },
			{ tip: "Show your resilience to stress", category: "Behavior" },
			{ tip: "Know the standard care protocols", category: "Technical" },
		] as CompanyInterviewTip[],
		interviewDifficulty: 3.0,
		interviewAverageDuration: "1-2 weeks",
		interviewProcessSteps: ["Application", "Interview with department head", "Observation period", "Decision"],
		salaries: [
			{ role: "Nurse", minSalary: 4500, maxSalary: 8000, medianSalary: 6000, sampleSize: 200 },
			{ role: "General Practitioner", minSalary: 8000, maxSalary: 15000, medianSalary: 11000, sampleSize: 80 },
			{ role: "Specialist Physician", minSalary: 12000, maxSalary: 25000, medianSalary: 18000, sampleSize: 60 },
			{ role: "Laboratory Technician", minSalary: 4000, maxSalary: 7000, medianSalary: 5500, sampleSize: 45 },
		] as CompanySalaryRange[],
		benefits: [
			{ category: "Employment", items: ["Public sector job stability", "Statutory protection"], rating: 4.5 },
			{ category: "Training", items: ["Free continuing education", "Access to medical conferences"], rating: 4.0 },
			{ category: "Leave", items: ["Generous annual leave", "Training leave"], rating: 3.8 },
		] as CompanyBenefit[],
		news: [
			{
				id: generateId(),
				title: "Inauguration of a new state-of-the-art operating suite",
				summary: "CHU Ibn Rochd equips itself with latest-generation surgical equipment.",
				date: "2024-12-10",
				source: "Le360",
				type: "announcement" as const,
			},
		] as CompanyNewsItem[],
		keyPeople: [
			{
				id: generateId(),
				name: "Pr. Ahmed Benali",
				title: "General Director",
				department: "Executive Leadership",
				yearsAtCompany: 12,
				bio: "Specialist in hospital administration",
			},
			{
				id: generateId(),
				name: "Pr. Nadia Chadli",
				title: "Head of Emergency Services",
				department: "Emergency",
				yearsAtCompany: 15,
			},
		] as CompanyKeyPerson[],
	},
];
