import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const basePath = resolve('src/routes/dashboard/interview/-components');

function fixFile(filename, replacements) {
  const filePath = resolve(basePath, filename);
  let content = readFileSync(filePath, 'utf8');
  let count = 0;
  for (const [from, to] of replacements) {
    if (content.includes(from)) {
      content = content.replaceAll(from, to);
      count++;
    } else {
      // console.log(`  NOT FOUND: ${from.substring(0, 60)}`);
    }
  }
  writeFileSync(filePath, content, 'utf8');
  console.log(`${filename}: ${count} replacements applied`);
}

// ===== review-components.tsx =====
fixFile('review-components.tsx', [
  ['Structure de la reponse', 'Answer structure'],
  ['Corps de reponse', 'Answer body'],
  ['Methode STAR', 'STAR Method'],
  ['Mots de remplissage detectes', 'Filler words detected'],
  ["Reponse ideale (exemple)", "Ideal answer (example)"],
  ['Score Global', 'Overall Score'],
  ['"Rythme de parole"', '"Speaking pace"'],
  ['"Clarte"', '"Clarity"'],
  ['"Qualite du contenu"', '"Content quality"'],
  ['"Langage corporel"', '"Body language"'],
  ['"Structure des reponses"', '"Answer structure"'],
  ['>Mots de remplissage<', '>Filler words<'],
  ['>Rythme<', '>Pace<'],
  ['>Contenu<', '>Content<'],
  ["Analyse de l'Enregistrement", "Recording Analysis"],
  ["Revue des Enregistrements d'Entretien", "Interview Recording Review"],
  ["Revue des Enregistrements", "Recording Review"],
  ["Mots de remplissage</Trans>", "Filler words</Trans>"],
  ["Langage corporel</Trans>", "Body language</Trans>"],
  ["Analyse par question", "Analysis by question"],
  ["Tout replier</Trans>", "Collapse all</Trans>"],
  ["Detection des mots de remplissage", "Filler word detection"],
  [`Les mots de remplissage comme "euh", "donc", "en fait" peuvent diminuer l'impact de vos reponses.`, `Filler words like "uh", "so", "actually" can diminish the impact of your answers.`],
  ["Total detecte</Trans>", "Total detected</Trans>"],
  ["Par minute</Trans>", "Per minute</Trans>"],
  ['"Eleve"', '"High"'],
  ['"Modere"', '"Moderate"'],
  ['"Faible"', '"Low"'],
  ["Mots detectes</Trans>", "Words detected</Trans>"],
  ["Conseils pour reduire les mots de remplissage", "Tips for reducing filler words"],
  ["Analyse du langage corporel", "Body language analysis"],
  ["Conseils bases sur l'analyse video pour ameliorer votre presence et votre confiance.", "Tips based on video analysis to improve your presence and confidence."],
  ["Analyse video (placeholder)", "Video analysis (placeholder)"],
  ["L'analyse video complete sera disponible dans une prochaine mise a jour.", "Full video analysis will be available in a future update."],
  ['"Prioritaire"', '"Priority"'],
  ['"A ameliorer"', '"To improve"'],
  ['"Mineur"', '"Minor"'],
  ["Points forts</Trans>", "Strengths</Trans>"],
  ["Axes d'amelioration</Trans>", "Areas for improvement</Trans>"],
  ["Suggestions d'amelioration</Trans>", "Improvement suggestions</Trans>"],
  ["Recommandations personnalisees basees sur votre performance", "Personalized recommendations based on your performance"],
  ["Analyse Video IA</Trans>", "AI Video Analysis</Trans>"],
  ["Analysez vos enregistrements d'entretien avec notre IA. Recevez des feedbacks detailles sur votre rythme", "Analyze your interview recordings with our AI. Receive detailed feedback on your speaking"],
  ["de parole, clarte, contenu et langage corporel.", "pace, clarity, content, and body language."],
  ["Enregistrements</Trans>", "Recordings</Trans>"],
  ["Score Moyen</Trans>", "Average Score</Trans>"],
  ['Rechercher..."', 'Search..."'],
  ['placeholder="Domaine"', 'placeholder="Field"'],
  ["Tous les domaines", "All fields"],
  ["Telechargez votre enregistrement d'entretien pour une analyse IA detaillee.", "Upload your interview recording for a detailed AI analysis."],
  ["Analyse IA en cours...", "AI analysis in progress..."],
  ["Notre IA analyse votre enregistrement pour fournir des feedbacks detailles.", "Our AI is analyzing your recording to provide detailed feedback."],
  ["Telechargement en cours...", "Uploading..."],
  ['placeholder="Ex: Entretien Simulation - Infirmier"', 'placeholder="E.g.: Mock Interview - Nurse"'],
  ["Programme (optionnel)", "Program (optional)"],
  ['placeholder="Ex: Infirmier Polyvalent"', 'placeholder="E.g.: General Nurse"'],
  ["Fichier video</Trans>", "Video file</Trans>"],
  ["Glissez votre fichier ici ou cliquez pour parcourir", "Drag your file here or click to browse"],
  ["Parcourir</Trans>", "Browse</Trans>"],
  ["Telecharger et analyser</Trans>", "Upload and analyze</Trans>"],
  ["Progression au fil du temps</Trans>", "Progress over time</Trans>"],
  ["Evolution de vos scores sur les dernieres semaines", "Evolution of your scores over recent weeks"],
  ["Vos enregistrements</Trans>", "Your recordings</Trans>"],
  ["Une erreur est survenue lors du chargement des enregistrements.", "An error occurred while loading recordings."],
  ["Telechargez votre premier enregistrement d'entretien pour recevoir une analyse detaillee par notre IA.", "Upload your first interview recording to receive a detailed analysis by our AI."],
  ["Conseils pour de meilleurs enregistrements</Trans>", "Tips for better recordings</Trans>"],
  ["Voir l'analyse</Trans>", "View analysis</Trans>"],
  [">Transcription<", ">Transcript<"],
]);

// ===== question-bank-components.tsx =====
fixFile('question-bank-components.tsx', [
  ["Mode Pratique", "Practice Mode"],
  ["Prenez le temps de reflechir avant de repondre", "Take time to think before answering"],
  ["Quitter la pratique</Trans>", "Exit practice</Trans>"],
  ["Temps de reponse recommande:</Trans>", "Recommended answer time:</Trans>"],
  ["Demarrer</Trans>", "Start</Trans>"],
  ["Duree:</Trans>", "Duration:</Trans>"],
  ["Structurez votre reponse avec la methode STAR", "Structure your answer with the STAR method"],
  ["Aleatoire</Trans>", "Random</Trans>"],
  ["Voir la reponse modele</Trans>", "View model answer</Trans>"],
  ["Exemple STAR detaille</Trans>", "Detailed STAR example</Trans>"],
  ["Banque de Questions d'Entretien", "Interview Question Bank"],
  ["Erreur lors du chargement</Trans>", "Loading error</Trans>"],
  ["Une erreur s'est produite lors du chargement de vos favoris. Veuillez reessayer.", "An error occurred while loading your favorites. Please try again."],
  ["Banque de Questions</Trans>", "Question Bank</Trans>"],
  ["Preparez-vous avec notre Banque de Questions", "Prepare with our Question Bank"],
  ["Explorez notre collection complete de questions d'entretien categorizees par type, difficulte et secteur.", "Explore our complete collection of interview questions categorized by type, difficulty, and industry."],
  ["Chaque question inclut une reponse modele et un exemple STAR detaille.", "Each question includes a model answer and a detailed STAR example."],
  ["Guide STAR</Trans>", "STAR Guide</Trans>"],
  ["favoris</Trans>", "favorites</Trans>"],
  ["Favori</Trans>", "Favorite</Trans>"],
  ["La Methode STAR - Votre Cle pour des Reponses Structurees", "The STAR Method - Your Key to Structured Answers"],
  ["La methode STAR est une technique de communication structuree pour repondre aux questions", "The STAR method is a structured communication technique for answering"],
  ["comportementales. Elle vous aide a donner des reponses claires, concises et percutantes.", "behavioral questions. It helps you give clear, concise, and impactful answers."],
  ["Conseils pour utiliser STAR efficacement</Trans>", "Tips for using STAR effectively</Trans>"],
  ["Preparez 5-6 histoires STAR que vous pouvez adapter a differentes questions", "Prepare 5-6 STAR stories that you can adapt to different questions"],
  ["Gardez chaque partie courte: 1-2 phrases pour S et T, 2-3 pour A, 1-2 pour R", "Keep each part short: 1-2 sentences for S and T, 2-3 for A, 1-2 for R"],
  ["Quantifiez vos resultats quand c'est possible (%, temps, argent)", "Quantify your results when possible (%, time, money)"],
  ["Pratiquez a voix haute pour que vos reponses soient naturelles", "Practice out loud so your answers feel natural"],
  ["Filtres actifs:</Trans>", "Active filters:</Trans>"],
  ["Secteur:</Trans>", "Industry:</Trans>"],
  ["Difficulte:</Trans>", "Difficulty:</Trans>"],
  ["Conseils pour Repondre</Trans>", "Tips for Answering</Trans>"],
  ["Mots-cles a utiliser</Trans>", "Keywords to use</Trans>"],
  ["Mes Questions Favorites</Trans>", "My Favorite Questions</Trans>"],
  ["Continuez votre Preparation</Trans>", "Continue your Preparation</Trans>"],
  ["Entretien Simule IA</Trans>", "AI Mock Interview</Trans>"],
  ["Pratiquez avec l'IA</Trans>", "Practice with AI</Trans>"],
  ["Tous les outils</Trans>", "All tools</Trans>"],
  ["Pret a vous entrainer?</Trans>", "Ready to practice?</Trans>"],
  ["Lancez le mode pratique avec minuteur pour simuler un vrai entretien", "Launch practice mode with a timer to simulate a real interview"],
  ["Demarrer la Pratique</Trans>", "Start Practice</Trans>"],
]);

// ===== outfit-components.tsx =====
fixFile('outfit-components.tsx', [
  ["Guide Vestimentaire</Trans>", "Outfit Guide</Trans>"],
  ["Conseiller Vestimentaire pour Entretien</Trans>", "Interview Outfit Advisor</Trans>"],
  ["Decouvrez comment vous habiller pour faire une excellente premiere impression lors de votre entretien", "Discover how to dress to make an excellent first impression during your job"],
  ["d'embauche. Des conseils adaptes a chaque secteur d'activite.", "interview. Tips adapted to each industry."],
  ["Tenue Homme</Trans>", "Men's Outfit</Trans>"],
  ["Tenue Femme</Trans>", "Women's Outfit</Trans>"],
  ["Couleurs recommandees</Trans>", "Recommended colors</Trans>"],
  ["Niveau de formalite:</Trans>", "Formality level:</Trans>"],
  ["Conseils supplementaires</Trans>", "Additional tips</Trans>"],
  ["Evaluation de la culture d'entreprise</Trans>", "Company culture assessment</Trans>"],
  ["Repondez a ces questions pour obtenir une recommandation vestimentaire personnalisee", "Answer these questions to get a personalized outfit recommendation"],
  ["Obtenir ma recommandation</Trans>", "Get my recommendation</Trans>"],
  ["Votre recommandation</Trans>", "Your recommendation</Trans>"],
  ["Checklist rapide - Entretien virtuel</Trans>", "Quick checklist - Virtual interview</Trans>"],
  ["Tester la connexion internet", "Test internet connection"],
  ["Verifier la camera et le micro", "Check camera and microphone"],
  ["Preparer l'arriere-plan", "Prepare the background"],
  ["Ajuster l'eclairage", "Adjust the lighting"],
  ["Se positionner correctement", "Position yourself correctly"],
  ["Avoir un verre d'eau a portee", "Have a glass of water nearby"],
  ["Prevenir les personnes autour", "Notify people around you"],
  ["t`Hommes`", "t`Men`"],
  ["t`Femmes`", "t`Women`"],
  ["Progression de la preparation</Trans>", "Preparation progress</Trans>"],
  ["Erreur lors du chargement des donnees</Trans>", "Error loading data</Trans>"],
  ["etapes completees</Trans>", "steps completed</Trans>"],
  ["Impossible de charger la checklist. Veuillez reessayer.", "Unable to load the checklist. Please try again."],
  ["Parfait!</Trans>", "Perfect!</Trans>"],
  ["Votre tenue est prete! Vous avez complete toutes les etapes de preparation vestimentaire.", "Your outfit is ready! You have completed all outfit preparation steps."],
  ["Ressources Complementaires</Trans>", "Additional Resources</Trans>"],
  ["Checklist complete pour le jour J", "Complete checklist for the big day"],
]);

// ===== notes-components.tsx =====
fixFile('notes-components.tsx', [
  ["Point cle</Trans>", "Key point</Trans>"],
  ["Liste</Trans>", "List</Trans>"],
  ["Horodatage</Trans>", "Timestamp</Trans>"],
  ['toLocaleTimeString("fr-FR"', 'toLocaleTimeString("en-US"'],
  ['toLocaleDateString("fr-FR"', 'toLocaleDateString("en-US"'],
  ["Modifie</Trans>", "Modified</Trans>"],
  ["Voir</Trans>", "View</Trans>"],
  ["Erreur lors de la mise a jour", "Error updating"],
  ["Notes sauvegardees", "Notes saved"],
  ["Exporter PDF</Trans>", "Export PDF</Trans>"],
  ["Export PDF en cours de developpement", "PDF export is under development"],
  ["Recruteurs</Trans>", "Recruiters</Trans>"],
  ["Points cles</Trans>", "Key points</Trans>"],
  ["Informations sur les Recruteurs</Trans>", "Recruiter Information</Trans>"],
  ["Details des personnes rencontrees pendant l'entretien", "Details of people met during the interview"],
  ["Points Cles de l'Entretien</Trans>", "Interview Key Points</Trans>"],
  ["Elements importants a retenir de cet entretien", "Important elements to remember from this interview"],
  ["Questions et Reponses</Trans>", "Questions and Answers</Trans>"],
  ["Journal des questions posees et de vos reponses", "Log of questions asked and your answers"],
  ["Ma reponse:</Trans>", "My answer:</Trans>"],
  ["Taches a accomplir suite a cet entretien", "Tasks to complete following this interview"],
  ["Prochaines Etapes</Trans>", "Next Steps</Trans>"],
  ['Echeance: ', 'Due: '],
  ['"Haute"', '"High"'],
  ['"Moyenne"', '"Medium"'],
  ['"Basse"', '"Low"'],
  ["Notes Generales</Trans>", "General Notes</Trans>"],
  ["Vos observations et reflexions sur cet entretien", "Your observations and reflections on this interview"],
  ["Ajoutez vos notes ici...", "Add your notes here..."],
  ["Notes d'Entretiens</Trans>", "Interview Notes</Trans>"],
  ["Capturez chaque detail important de vos entretiens. Enregistrez les questions, suivez vos actions et gardez", "Capture every important detail of your interviews. Record questions, track your actions, and keep"],
  ["une trace de vos impressions pour mieux vous preparer.", "a record of your impressions for better preparation."],
  ["Termines</Trans>", "Completed</Trans>"],
  ["Planifies</Trans>", "Scheduled</Trans>"],
  ["Enregistrez les informations de base pour votre prochain entretien.", "Record the basic information for your upcoming interview."],
  ["Titre (optionnel)</Trans>", "Title (optional)</Trans>"],
  ["Ex: Entretien Infirmier - Hopital Central", "E.g.: Nurse Interview - Central Hospital"],
  ["Nom de l'entreprise", "Company name"],
  ["Intitule du poste", "Job title"],
  ["Lieu (optionnel)</Trans>", "Location (optional)</Trans>"],
  ["Adresse ou lien visio", "Address or video link"],
  ["Toutes les entreprises</Trans>", "All companies</Trans>"],
  ['placeholder={t`Entreprise`}', 'placeholder={t`Company`}'],
  ['placeholder={t`Statut`}', 'placeholder={t`Status`}'],
  ["Conseils pour Bien Noter vos Entretiens</Trans>", "Tips for Good Interview Note-Taking</Trans>"],
  ["Notez les noms et titres de tous les recruteurs des le debut", "Write down the names and titles of all recruiters from the start"],
  ["Utilisez les horodatages pour retrouver facilement les moments cles", "Use timestamps to easily find key moments"],
  ["Creez des actions de suivi avec des dates limites claires", "Create follow-up actions with clear deadlines"],
  ["Evaluez vos reponses pour identifier les points a ameliorer", "Evaluate your answers to identify areas for improvement"],
  // NoteCard inline French
  [" recruteur", " recruiter"],
  [" points cles", " key points"],
]);

// ===== confidence-components.tsx =====
fixFile('confidence-components.tsx', [
  ['t`Pret`', 't`Ready`'],
  ['t`Inspirez`', 't`Inhale`'],
  ['t`Retenez`', 't`Hold`'],
  ['t`Expirez`', 't`Exhale`'],
  ['t`Repos`', 't`Rest`'],
  ['t`Termine`', 't`Done`'],
  ["temps restant</Trans>", "time remaining</Trans>"],
  ["Exercice termine!</Trans>", "Exercise complete!</Trans>"],
  ["Bien-etre Mental</Trans>", "Mental Wellness</Trans>"],
  ["Exercices de Confiance en Soi</Trans>", "Self-Confidence Exercises</Trans>"],
  ["Preparez votre mental pour reussir vos entretiens. Respirations guidees, affirmations positives, poses de", "Prepare your mind for successful interviews. Guided breathing, positive affirmations, power"],
  ["pouvoir et techniques de visualisation pour booster votre confiance.", "poses, and visualization techniques to boost your confidence."],
  ["Jours de suite</Trans>", "Consecutive days</Trans>"],
  ['t`Respiration`', 't`Breathing`'],
  ['t`Poses de Pouvoir`', 't`Power Poses`'],
  ['t`Visualisation`', 't`Visualization`'],
  ["Exercices de Respiration</Trans>", "Breathing Exercises</Trans>"],
  ["Techniques de respiration pour calmer le stress et l'anxiete", "Breathing techniques to calm stress and anxiety"],
  ["Fait</Trans>", "Done</Trans>"],
  ["Affirmations Positives</Trans>", "Positive Affirmations</Trans>"],
  ["Renforcez votre confiance avec des affirmations puissantes", "Strengthen your confidence with powerful affirmations"],
  ["Bibliotheque d'Affirmations</Trans>", "Affirmation Library</Trans>"],
  ["Des poses qui augmentent votre confiance et reduisent le cortisol. Tenez chaque pose 2 minutes.", "Poses that increase your confidence and reduce cortisol. Hold each pose for 2 minutes."],
  ["Techniques de Visualisation</Trans>", "Visualization Techniques</Trans>"],
  ["Utilisez le pouvoir de votre imagination pour preparer votre succes", "Use the power of your imagination to prepare for success"],
  ["Gestion de l'Anxiete</Trans>", "Anxiety Management</Trans>"],
  ["Strategies pratiques pour gerer le stress et l'anxiete avant un entretien", "Practical strategies for managing stress and anxiety before an interview"],
  ["Marquer comme fait</Trans>", "Mark as done</Trans>"],
  ["Ma Routine Quotidienne</Trans>", "My Daily Routine</Trans>"],
  ["Construisez une routine quotidienne pour maintenir votre confiance", "Build a daily routine to maintain your confidence"],
  ["Progres d'aujourd'hui</Trans>", "Today's progress</Trans>"],
  ["exercices termines</Trans>", "exercises completed</Trans>"],
  ["Faire</Trans>", "Do it</Trans>"],
  ["Ajoutez des exercices depuis les autres onglets pour creer votre routine quotidienne", "Add exercises from other tabs to create your daily routine"],
  ["Minuteur de Meditation</Trans>", "Meditation Timer</Trans>"],
  ["Un minuteur simple pour vos sessions de meditation ou de respiration libre", "A simple timer for your meditation or free breathing sessions"],
  ["Choisir la duree</Trans>", "Choose duration</Trans>"],
  ["Commencer la meditation</Trans>", "Start meditation</Trans>"],
  ["Conseils pour mediter</Trans>", "Tips for meditating</Trans>"],
  ["Trouvez un endroit calme et confortable", "Find a quiet and comfortable place"],
  ["Asseyez-vous ou allongez-vous confortablement", "Sit or lie down comfortably"],
  ["Fermez les yeux et concentrez-vous sur votre respiration", "Close your eyes and focus on your breathing"],
  ["Laissez passer les pensees sans les juger", "Let thoughts pass without judging them"],
  ["Revenez doucement a votre respiration si vous vous egarrez", "Gently return to your breathing if you wander"],
  ["Etapes a suivre:</Trans>", "Steps to follow:</Trans>"],
  ["Session de Meditation</Trans>", "Meditation Session</Trans>"],
  ["Detendez-vous et concentrez-vous sur votre respiration", "Relax and focus on your breathing"],
  ["Gestion du Stress</Trans>", "Stress Management</Trans>"],
  ["Ma Routine</Trans>", "My Routine</Trans>"],
  [">Respiration</Trans>", ">Breathing</Trans>"],
]);

// ===== analytics-components.tsx =====
fixFile('analytics-components.tsx', [
  ["Analyse de Performance", "Performance Analysis"],
  ["Niveau de Preparation</Trans>", "Readiness Level</Trans>"],
  ["Environ {readiness.estimatedSessionsNeeded} sessions pour atteindre le niveau optimal", "About {readiness.estimatedSessionsNeeded} sessions to reach the optimal level"],
  ["Vous etes pret pour votre entretien!", "You are ready for your interview!"],
  [">Pret<", ">Ready<"],
  ["Vue d'ensemble</Trans>", "Overview</Trans>"],
  ["Faiblesses</Trans>", "Weaknesses</Trans>"],
  ["Progres</Trans>", "Progress</Trans>"],
  ["Plan d'action</Trans>", "Action plan</Trans>"],
  ["Confiance</Trans>", "Confidence</Trans>"],
  ["Technique</Trans>", "Technical</Trans>"],
  ["Comportemental</Trans>", "Behavioral</Trans>"],
  ["Comparaison aux candidats reussis</Trans>", "Comparison to successful candidates</Trans>"],
  ["Votre performance par rapport aux candidats qui ont reussi leurs entretiens", "Your performance compared to candidates who passed their interviews"],
  ["Votre score</Trans>", "Your score</Trans>"],
  ["Moyenne des reussis</Trans>", "Successful average</Trans>"],
  ["Ecarts a combler</Trans>", "Gaps to close</Trans>"],
  ["Performance par type de question</Trans>", "Performance by question type</Trans>"],
  [" questions repondues", " questions answered"],
  ["Critiques</Trans>", "Critical</Trans>"],
  ["En amelioration</Trans>", "Improving</Trans>"],
  ["Completez plus de sessions pour identifier les domaines a ameliorer", "Complete more sessions to identify areas for improvement"],
  ["Erreurs frequentes</Trans>", "Common mistakes</Trans>"],
  ["Evolution de vos scores</Trans>", "Score evolution</Trans>"],
  [">Cette semaine<", ">This week<"],
  [">Ce mois<", ">This month<"],
  [">Tout le temps<", ">All time<"],
  [">Avant<", ">Before<"],
  [">Maintenant<", ">Now<"],
  [" sessions completees", " sessions completed"],
  ["Completez plusieurs sessions pour voir votre progression", "Complete multiple sessions to see your progress"],
  ["Commencer une session</Trans>", "Start a session</Trans>"],
  ["Vos points forts</Trans>", "Your strengths</Trans>"],
  ["Generez votre plan personnalise</Trans>", "Generate your personalized plan</Trans>"],
  ["Completez quelques sessions pour generer un plan d'amelioration adapte", "Complete a few sessions to generate a tailored improvement plan"],
  ["Domaines prioritaires</Trans>", "Priority areas</Trans>"],
  ["Objectifs hebdomadaires</Trans>", "Weekly goals</Trans>"],
  ["Semaine ", "Week "],
  ["Programme de pratique</Trans>", "Practice program</Trans>"],
  ["Jalons</Trans>", "Milestones</Trans>"],
  ["Temps estime pour atteindre vos objectifs</Trans>", "Estimated time to reach your goals</Trans>"],
  ["En suivant le plan de pratique recommande", "By following the recommended practice plan"],
  [">jours<", ">days<"],
  ["Pratiquer maintenant</Trans>", "Practice now</Trans>"],
  ["Vu ", "Seen "],
  [" fois<", " times<"],
  ["Ressources suggerees:", "Suggested resources:"],
  ['toLocaleDateString("fr-FR")', 'toLocaleDateString("en-US")'],
]);

console.log('All files processed!');
