import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";
import type { Template } from "@/schema/templates";

export type TemplateMetadata = {
	name: string;
	description: MessageDescriptor;
	imageUrl: string;
	tags: string[];
	sidebarPosition: "left" | "right" | "none";
};

export const templates = {
	avicenne: {
		name: "Avicenne Académique",
		description: msg`French CV style designed for the Moroccan job market; includes support for CIN, nationality, and military service status. Ideal for IMTA students and French-speaking professionals.`,
		imageUrl: "/templates/jpg/avicenne.jpg",
		tags: ["Morocco", "French CV", "IMTA", "Professional", "Two-column", "ATS friendly"],
		sidebarPosition: "right",
	},
	azurill: {
		name: "Atlas Corporate",
		description: msg`Two-column with a bold colored sidebar and skill bars; great for creative or tech roles where visual flair is welcome.`,
		imageUrl: "/templates/jpg/azurill.jpg",
		tags: ["Two-column", "Creative", "Tech", "Visual flair"],
		sidebarPosition: "left",
	},
	bronzor: {
		name: "Finance Conseil",
		description: msg`Two-column, clean and professional with subtle section dividers; suits corporate, finance, or consulting positions.`,
		imageUrl: "/templates/jpg/bronzor.jpg",
		tags: ["Two-column", "Clean", "Professional", "Corporate", "Finance", "Consulting"],
		sidebarPosition: "none",
	},
	chikorita: {
		name: "Relation Client",
		description: msg`Two-column with a soft header accent and circular profile photo; ideal for marketing, HR, or client-facing roles.`,
		imageUrl: "/templates/jpg/chikorita.jpg",
		tags: ["Two-column", "Soft accent", "Marketing", "HR", "Client-facing"],
		sidebarPosition: "right",
	},
	ditgar: {
		name: "Digital Product",
		description: msg`Two-column with a dark teal sidebar and skills grid; modern feel for developers, data scientists, or technical PMs.`,
		imageUrl: "/templates/jpg/ditgar.jpg",
		tags: ["Two-column", "Modern", "Developer", "Data science", "Technical PM", "Dark sidebar"],
		sidebarPosition: "left",
	},
	fes: {
		name: "Fès Administratif",
		description: msg`Traditional French CV style for formal sectors; designed for government, banking, and corporate positions in Morocco. Shows CIN, nationality, and personal details prominently.`,
		imageUrl: "/templates/jpg/fes.jpg",
		tags: ["Morocco", "French CV", "Formal", "Government", "Banking", "Traditional", "IMTA"],
		sidebarPosition: "right",
	},
	ditto: {
		name: "Standard ATS",
		description: msg`Two-column, minimal and text-dense with no decorative elements; perfect for traditional industries or ATS-heavy applications.`,
		imageUrl: "/templates/jpg/ditto.jpg",
		tags: ["Two-column", "ATS friendly", "Minimal", "Text-dense", "Traditional", "No decoration"],
		sidebarPosition: "left",
	},
	gengar: {
		name: "Business Operations",
		description: msg`Two-column with accent colors and clean typography; balanced choice for business analysts or operations roles.`,
		imageUrl: "/templates/jpg/gengar.jpg",
		tags: ["Two-column", "Accent colors", "Clean typography", "Business analyst", "Operations"],
		sidebarPosition: "left",
	},
	glalie: {
		name: "Juridique Minimal",
		description: msg`Two-column, minimal with light gray sidebar and subtle icons; professional and understated for legal, finance, or executive roles.`,
		imageUrl: "/templates/jpg/glalie.jpg",
		tags: ["Two-column", "Minimal", "Professional", "Legal", "Finance", "Executive", "Understated"],
		sidebarPosition: "left",
	},
	kakuna: {
		name: "Stage Compact",
		description: msg`Single-column with a magenta left border accent; compact and efficient for entry-level or internship applications.`,
		imageUrl: "/templates/jpg/kakuna.jpg",
		tags: ["Single-column", "ATS friendly", "Compact", "Efficient", "Entry level", "Internship", "Magenta accent"],
		sidebarPosition: "none",
	},
	lapras: {
		name: "Senior Entreprise",
		description: msg`Single-column; polished and serious for senior or enterprise-level positions.`,
		imageUrl: "/templates/jpg/lapras.jpg",
		tags: ["Single-column", "ATS friendly", "Polished", "Senior", "Enterprise"],
		sidebarPosition: "none",
	},
	leafish: {
		name: "Santé & Social",
		description: msg`Two-column with a muted color sidebar; earthy and calm, suits sustainability, healthcare, or nonprofit sectors.`,
		imageUrl: "/templates/jpg/leafish.jpg",
		tags: ["Two-column", "Muted sidebar", "Earthy", "Calm", "Sustainability", "Healthcare", "Nonprofit"],
		sidebarPosition: "right",
	},
	onyx: {
		name: "Direction Executive",
		description: msg`Single-column with a sidebar and clean grid layout; versatile for any professional or technical role.`,
		imageUrl: "/templates/jpg/onyx.jpg",
		tags: ["Single-column", "ATS friendly", "Sidebar", "Grid layout", "Versatile", "Professional", "Technical"],
		sidebarPosition: "none",
	},
	pikachu: {
		name: "Communication Junior",
		description: msg`Two-column with a left margin color; simple and approachable for creative, editorial, or junior roles.`,
		imageUrl: "/templates/jpg/pikachu.jpg",
		tags: ["Two-column", "Simple", "Creative", "Editorial", "Junior", "Accent colors"],
		sidebarPosition: "left",
	},
	rhyhorn: {
		name: "Portfolio Moderne",
		description: msg`Single-column with a minimal top header and lots of whitespace; clean and modern for designers or content creators.`,
		imageUrl: "/templates/jpg/rhyhorn.jpg",
		tags: ["Single-column", "ATS friendly", "Minimal", "Clean", "Modern", "Designer", "Content creator", "Whitespace"],
		sidebarPosition: "none",
	},
	casablanca: {
		name: "Casablanca Corporate",
		description: msg`Modern corporate design with clean lines and professional blue tones; ideal for business, finance, and corporate roles in Morocco.`,
		imageUrl: "/templates/jpg/casablanca.jpg",
		tags: ["Morocco", "Corporate", "Modern", "Professional", "Two-column", "Business"],
		sidebarPosition: "left",
	},
	rabat: {
		name: "Rabat Administratif",
		description: msg`Formal structured layout designed for government, diplomatic, and administrative positions; Morocco-specific fields prominently displayed.`,
		imageUrl: "/templates/jpg/rabat.jpg",
		tags: ["Morocco", "Government", "Formal", "Diplomatic", "Structured", "Two-column"],
		sidebarPosition: "right",
	},
	marrakech: {
		name: "Marrakech Créatif",
		description: msg`Vibrant and warm design with accent sidebar; suits creative sectors, marketing, and communication roles.`,
		imageUrl: "/templates/jpg/marrakech.jpg",
		tags: ["Morocco", "Creative", "Vibrant", "Warm", "Two-column", "Marketing"],
		sidebarPosition: "left",
	},
	tangier: {
		name: "Tanger ATS",
		description: msg`International and clean single-column layout optimized for ATS scanners; ideal for multilingual professionals and international applications.`,
		imageUrl: "/templates/jpg/tangier.jpg",
		tags: ["Morocco", "International", "ATS friendly", "Clean", "Single-column", "Multilingual"],
		sidebarPosition: "none",
	},
	meknes: {
		name: "Meknès Banque & Droit",
		description: msg`Traditional elegant design with refined typography and subtle borders; perfect for classic industries, banking, and legal sectors.`,
		imageUrl: "/templates/jpg/meknes.jpg",
		tags: ["Morocco", "Traditional", "Elegant", "Classic", "Two-column", "Banking", "Legal"],
		sidebarPosition: "right",
	},
	oujda: {
		name: "Oujda Industrie",
		description: msg`Bold industrial design with dark sidebar and strong visual hierarchy; suited for engineering, technical, and industrial roles.`,
		imageUrl: "/templates/jpg/oujda.jpg",
		tags: ["Morocco", "Industrial", "Technical", "Bold", "Two-column", "Engineering", "Dark sidebar"],
		sidebarPosition: "left",
	},
	kenitra: {
		name: "Kénitra Logistique",
		description: msg`Modern industrial layout with geometric accents and clean structure; designed for manufacturing, logistics, and technical management.`,
		imageUrl: "/templates/jpg/kenitra.jpg",
		tags: ["Morocco", "Modern", "Industrial", "Geometric", "Two-column", "Manufacturing"],
		sidebarPosition: "left",
	},
	safi: {
		name: "Safi Technique",
		description: msg`Data-dense single-column layout with prominent header band; optimized for engineering, maritime, and technical professional CVs.`,
		imageUrl: "/templates/jpg/safi.jpg",
		tags: ["Morocco", "Engineering", "Technical", "Single-column", "Dense", "Maritime", "Professional"],
		sidebarPosition: "none",
	},
	ifrane: {
		name: "Ifrane Académique",
		description: msg`Scholarly and refined design with centered header and elegant typography; ideal for academic, research, and education positions.`,
		imageUrl: "/templates/jpg/ifrane.jpg",
		tags: ["Morocco", "Academic", "Scholarly", "Research", "Two-column", "Education", "Elegant"],
		sidebarPosition: "right",
	},
	mohammedia: {
		name: "Mohammedia Executive",
		description: msg`Premium executive layout with generous whitespace and distinguished typography; designed for C-suite, director, and senior management roles.`,
		imageUrl: "/templates/jpg/mohammedia.jpg",
		tags: ["Morocco", "Executive", "Premium", "C-Suite", "Two-column", "Senior", "Management"],
		sidebarPosition: "left",
	},
	chefchaouen: {
		name: "Chefchaouen Créatif",
		description: msg`Artistic blue-toned design inspired by the Blue City of Morocco; perfect for creative professionals, designers, and artists.`,
		imageUrl: "/templates/jpg/chefchaouen.jpg",
		tags: ["Morocco", "Artistic", "Blue", "Creative", "Two-column", "Designer"],
		sidebarPosition: "right",
	},
	essaouira: {
		name: "Essaouira Freelance",
		description: msg`Airy coastal-inspired single-column layout with generous whitespace; ideal for freelancers, designers, and creative professionals.`,
		imageUrl: "/templates/jpg/essaouira.jpg",
		tags: ["Morocco", "Creative", "Freelancer", "Airy", "Minimal", "Single-column", "Designer"],
		sidebarPosition: "none",
	},
	tetouan: {
		name: "Tétouan Artisanat",
		description: msg`Artisan-inspired design with decorative geometric elements; reflects Moroccan craftsmanship for traditional and cultural sector roles.`,
		imageUrl: "/templates/jpg/tetouan.jpg",
		tags: ["Morocco", "Artisan", "Decorative", "Traditional", "Two-column", "Geometric", "Cultural"],
		sidebarPosition: "left",
	},
	agadir: {
		name: "Agadir Hôtellerie",
		description: msg`Bright and welcoming design for tourism and hospitality industries; highlights languages and certifications prominently.`,
		imageUrl: "/templates/jpg/agadir.jpg",
		tags: ["Morocco", "Tourism", "Hospitality", "Welcoming", "Two-column", "Languages"],
		sidebarPosition: "right",
	},
	dakhla: {
		name: "Dakhla Business Tech",
		description: msg`Bold modern design with high-contrast dark sidebar and dynamic layout; ideal for ambitious professionals in tech and business.`,
		imageUrl: "/templates/jpg/dakhla.jpg",
		tags: ["Morocco", "Modern", "Bold", "Dynamic", "Two-column", "Dark sidebar", "Tech"],
		sidebarPosition: "left",
	},
	settat: {
		name: "Settat Étudiant",
		description: msg`Clean and approachable single-column layout designed for students and first-time job seekers; compact and ATS-friendly.`,
		imageUrl: "/templates/jpg/settat.jpg",
		tags: ["Morocco", "Student", "Entry-level", "First Job", "ATS friendly", "Single-column", "Compact"],
		sidebarPosition: "none",
	},
	jadida: {
		name: "El Jadida Polyvalent",
		description: msg`Versatile modern professional design with balanced proportions; the most adaptable template suitable for any industry or role level.`,
		imageUrl: "/templates/jpg/jadida.jpg",
		tags: ["Morocco", "Modern", "Professional", "Versatile", "Two-column", "Clean", "Balanced"],
		sidebarPosition: "right",
	},
	nador: {
		name: "Nador Bilingue",
		description: msg`Cross-cultural bilingual layout with RTL-aware design; ideal for professionals working across French and Arabic speaking environments.`,
		imageUrl: "/templates/jpg/nador.jpg",
		tags: ["Morocco", "Bilingual", "Cross-cultural", "International", "Two-column", "RTL", "Arabic"],
		sidebarPosition: "left",
	},
	"beni-mellal": {
		name: "Béni Mellal ONG",
		description: msg`Earthy natural design for NGO, development, and agricultural sectors; wider sidebar highlights skills, certifications, and volunteer work.`,
		imageUrl: "/templates/jpg/beni-mellal.jpg",
		tags: ["Morocco", "NGO", "Development", "Agriculture", "Two-column", "Rural", "Earthy"],
		sidebarPosition: "right",
	},
	taza: {
		name: "Taza ATS Compact",
		description: msg`Ultra-compact ATS-optimized layout with maximum content density; pure text structure with no decorative elements for guaranteed ATS compatibility.`,
		imageUrl: "/templates/jpg/taza.jpg",
		tags: ["Morocco", "ATS optimized", "Compact", "Dense", "Text-only", "Single-column", "No decoration"],
		sidebarPosition: "none",
	},
} satisfies Record<Template, TemplateMetadata>;
